(function(g){var window=this;/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var r3=function(a){a.Z("cardstatechange",a.yh()&&a.jk()?1:0)},s3=function(a,b){var c=g.La(b),d=c?b:arguments;
for(c=c?0:1;c<d.length;c++){if(null==a)return;a=a[d[c]]}return a},zMa=function(a){var b=g.Vl(a);
a=g.am(a);return new g.Fl(b.x,b.y,a.width,a.height)},AMa=function(a){return Math.pow(a,3)},BMa=function(a){return 3*a*a-2*a*a*a},v3=function(a){a=g.Oa(a);
delete t3[a];g.Wb(t3)&&u3&&u3.stop()},DMa=function(){u3||(u3=new g.K(function(){CMa()},20));
var a=u3;a.isActive()||a.start()},CMa=function(){var a=g.Qa();
g.Gb(t3,function(b){EMa(b,a)});
g.Wb(t3)||DMa()},w3=function(a,b,c,d){g.Oq.call(this);
if(!Array.isArray(a)||!Array.isArray(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.i=a;this.K=b;this.duration=c;this.D=d;this.coords=[];this.progress=this.J=0;this.B=null},EMa=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);1<a.progress&&(a.progress=1);a.J=1E3/(b-a.B);a.B=b;FMa(a,a.progress);1==a.progress?(a.Ra=0,v3(a),a.onFinish(),a.Vv()):a.yc()&&a.hB()},FMa=function(a,b){"function"===typeof a.D&&(b=a.D(b));
a.coords=Array(a.i.length);for(var c=0;c<a.i.length;c++)a.coords[c]=(a.K[c]-a.i[c])*b+a.i[c]},GMa=function(a,b){g.nf.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.J;this.state=b.Ra},x3=function(a,b,c,d,e){w3.call(this,b,c,d,e);
this.element=a},y3=function(a,b,c,d,e){if(2!=b.length||2!=c.length)throw Error("Start and end points must be 2D");
x3.call(this,a,b,c,d,e)},z3=function(a){g.H.call(this);
this.u=a||window;this.i=[]},A3=function(a){return a.baseUrl||null},B3=function(a,b){return g.Go(g.Se(a,b,void 0),function(c){return!!c})},HMa=function(a,b,c){function d(ha){var za,yb,xc,Fb=ha.hovercardButton;
if(!Fb)return null;Fb=Fb.subscribeButtonRenderer;if(!Fb)return null;var Qb=f(Fb.unsubscribedButtonText),Rb=f(Fb.subscribedButtonText);if(Fb.subscribed){var Ne=f(Fb.subscriberCountWithUnsubscribeText);var Oe=f(Fb.subscriberCountText)}else Ne=f(Fb.subscriberCountText),Oe=f(Fb.subscriberCountWithSubscribeText);var bc=null;return ha.signinEndpoint&&(bc=s3(ha,"signinEndpoint","webNavigationEndpointData","url"),bc||(bc=null===(xc=null===(yb=null===(za=Fb.signInEndpoint)||void 0===za?void 0:za.commandMetadata)||
void 0===yb?void 0:yb.webCommandMetadata)||void 0===xc?void 0:xc.url),!bc)?null:Qb&&(Rb||bc)?{subscribed:Fb.subscribed,subscribeText:Qb,subscribeCount:Ne,unsubscribeText:Rb,unsubscribeCount:Oe,enabled:Fb.enabled,signinUrl:bc,classic:ha.useClassicSubscribeButton}:null}
function e(ha){if(ha){var za=[],yb=ha.videoId;yb&&za.push("v="+yb);(yb=ha.playlistId)&&za.push("list="+yb);(ha=ha.startTimeSeconds)&&za.push("t="+ha);return"/watch?"+za.join("&")}}
function f(ha){if(!ha)return null;var za=ha.simpleText;return za?za:ha.runs?g.Se(ha.runs,function(yb){return yb.text}).join(""):null}
b=b.endscreenElementRenderer;if(!b)return null;var h=b.style,l=b.endpoint||{},m=null,n=null,p=null,q=null,t=null,u=null,x=!1,y=null,B=null,F=null,G=null,I=null;if("VIDEO"===h)l.urlEndpoint?m=l.urlEndpoint.url:m=e(l.watchEndpoint),n=!1,p=a,q=f(b.videoDuration);else if("PLAYLIST"===h)l.urlEndpoint?m=l.urlEndpoint.url:m=e(l.watchEndpoint),n=!1,p=a,t=f(b.playlistLength);else if("CHANNEL"===h){if(x=s3(l,"browseEndpoint","browseId"))u=x,m="/channel/"+u;n=!1;p="new";(x=!!b.isSubscribe)?y=d(b):B=f(b.subscribersText)}else"WEBSITE"===
h?((F=s3(l,"urlEndpoint","url"))&&(m=F),n=!0,p="new",F=b.icon.thumbnails[0].url):"CREATOR_MERCHANDISE"===h&&(b.productPrice&&(G=f(b.productPrice)),b.additionalFeesText&&(I=f(b.additionalFeesText)),(n=s3(l,"urlEndpoint","url"))&&(m=n),n=!0,p="new");a=s3(b,"title","accessibility","accessibilityData","label");var L=b.endpoint?b.endpoint.clickTrackingParams:null,da="";if(b.metadata){var M=f(b.metadata);M&&(da=M)}return{id:"element-"+c,type:h,title:f(b.title),metadata:da,callToAction:f(b.callToAction),
wI:b.image,iconUrl:F,left:Number(b.left),width:Number(b.width),top:Number(b.top),aspectRatio:Number(b.aspectRatio),startMs:Math.floor(Number(b.startMs)),endMs:Math.floor(Number(b.endMs)),videoDuration:q,playlistLength:t,channelId:u,subscribeButton:y,subscribersText:B,isSubscribe:x,targetUrl:m||null,pR:n,sessionData:L?{itct:L}:null,dW:p,Xt:a?a:null,sR:b.isPlaceholder,impressionUrls:B3(b.impressionUrls||[],A3),iR:B3(b.hovercardShowUrls||[],A3),clickUrls:B3(l.loggingUrls||[],A3),visualElement:g.$x(b.trackingParams),
productPrice:G,additionalFeesText:I}},C3=function(a,b){var c={startMs:Math.floor(Number(a.startMs)),
impressionUrls:B3(a.impressionUrls||[],A3),elements:B3(a.elements||[],function(d,e){return HMa(b,d,e)})};
a.trackingParams&&(c.visualElement=g.$x(a.trackingParams));return c},D3=function(a){g.kN.call(this,a);
this.B=this.endscreen=null;this.i={};this.D={};this.C=this.u=null;this.K=[];this.V=!0;this.J=0;a=a.U();this.N=g.rF(a)||g.vF(a);this.events=new g.aN(this);g.J(this,this.events);this.events.S(this.player,g.kA("creatorendscreen"),this.Bd);this.events.S(this.player,g.lA("creatorendscreen"),this.nf);this.events.S(this.player,"resize",this.xb);this.events.S(window,"focus",this.lV);this.load();var b=g.sg("STYLE");(g.eg("HEAD")[0]||document.body).appendChild(b);g.mf(this,function(){g.wg(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},IMa=function(a){return a.player.getVideoData().D?"current":a.N?"new":"current"},E3=function(a){return"creator-endscreen-editor"===a.player.U().playerStyle},JMa=function(a){var b=a.player.getVideoData(),c=b.videoId;
a.B&&a.B.abort();c={method:"POST",onFinish:function(e){var f=a.B=null;200===e.status&&(e=e.responseText,")]}"===e.substring(0,3)&&(e=e.substring(3),f=JSON.parse(e),f=C3(f,IMa(a))));F3(a,f)},
urlParams:{v:c},withCredentials:!0};a.N&&(c.urlParams.ptype="embedded");var d=b.Kp;d&&(c.postParams={ad_tracking:d});if(b=g.ioa(b))if(b=g.Pc(b),b=g.Lc(b))a.B=g.lt(b,c)},F3=function(a,b,c){c=void 0===c?!0:c;
a.player.We("creatorendscreen");a.u&&(a.u.dispose(),a.u=null,a.C.dispose(),a.C=null);for(var d=g.r(Object.values(a.i)),e=d.next();!e.done;e=d.next())e.value.dispose();a.i={};a.D={};0<a.K.length&&(a.K.forEach(function(l){l.dispose()}),a.K.length=0);
a.J=0;if((a.endscreen=b)&&b.elements){c&&KMa(a);c=[];d=new g.hA(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);a.player.U().i||(a.u=new g.W({G:"div",L:"ytp-ce-shadow"}),g.YM(a.player,a.u.element,4),a.C=new g.LL(a.u,200));for(d=0;d<b.elements.length;++d){e=b.elements[d];var f=LMa(a,e);if(f){a.i[e.id]=f;a.D[e.id]=e;g.YM(a.player,f.element,4);var h=new g.hA(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(h);MMa(a,f,e)}else g.cz(new g.$v("buildEndscreenElement null",
e))}a.player.Hd(c);a.xb()}},KMa=function(a){var b=g.dy(),c=g.fy();
c&&b&&a.endscreen.visualElement&&g.jz(void 0,c,b,[a.endscreen.visualElement])},LMa=function(a,b){var c=null;
switch(b.type){case "VIDEO":c=a.player.Y("player_endscreen_ellipsis_fix")?["ytp-webkit-ellipsis"]:["yt-ui-ellipsis","yt-ui-ellipsis-2"];a={G:"div",Ga:["ytp-ce-element","ytp-ce-video"],W:{tabindex:"0","aria-label":b.Xt||"","aria-hidden":"true"},T:[{G:"div",L:"ytp-ce-element-shadow"},{G:"div",L:"ytp-ce-covering-image",W:G3(b)},{G:"div",L:"ytp-ce-covering-shadow-top"},{G:"a",L:"ytp-ce-covering-overlay",W:{href:H3(a,b.targetUrl),tabindex:"-1"},T:[{G:"div",Ga:["ytp-ce-video-title"].concat(g.v(c)),W:{dir:g.Xq(b.title||
"")},va:b.title},{G:"div",L:"ytp-ce-video-duration",va:b.videoDuration||void 0}]}]};c=new g.W(a);break;case "PLAYLIST":c=a.player.Y("player_endscreen_ellipsis_fix")?["ytp-webkit-ellipsis"]:["yt-ui-ellipsis","yt-ui-ellipsis-2"];a={G:"div",Ga:["ytp-ce-element","ytp-ce-playlist"],W:{tabindex:"0","aria-label":b.Xt||"","aria-hidden":"true"},T:[{G:"div",L:"ytp-ce-element-shadow"},{G:"div",L:"ytp-ce-covering-image",W:G3(b)},{G:"div",L:"ytp-ce-covering-shadow-top"},{G:"a",L:"ytp-ce-covering-overlay",W:{href:H3(a,
b.targetUrl),tabindex:"-1"},T:[{G:"div",Ga:["ytp-ce-playlist-title"].concat(g.v(c)),W:{dir:g.Xq(b.title||"")},va:b.title},{G:"div",L:"ytp-ce-playlist-count",T:[{G:"div",L:"ytp-ce-playlist-icon"},{G:"div",L:"ytp-ce-playlist-count-text",va:b.playlistLength||void 0}]}]}]};c=new g.W(a);break;case "CHANNEL":c={G:"div",Ga:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],W:{tabindex:"0","aria-label":b.Xt||"","aria-hidden":"true"},T:[{G:"div",L:"ytp-ce-element-shadow"},
{G:"div",L:"ytp-ce-expanding-overlay",T:[{G:"div",L:"ytp-ce-expanding-overlay-hider"},{G:"div",L:"ytp-ce-expanding-overlay-background"},{G:"div",L:"ytp-ce-expanding-overlay-content",T:[{G:"div",L:"ytp-ce-expanding-overlay-body",T:[{G:"div",L:"ytp-ce-expanding-overlay-body-padding",T:[{G:"a",Ga:["ytp-ce-channel-title","ytp-ce-link"],W:{href:H3(a,b.targetUrl),target:"_blank",tabindex:"-1",dir:g.Xq(b.title||"")},va:b.title},b.subscribeButton?{G:"div",L:"ytp-ce-subscribe-container",T:[{G:"div",L:"ytp-ce-channel-subscribe"}]}:
"",b.subscribersText?{G:"div",L:"ytp-ce-channel-subscribers-text",va:b.subscribersText}:"",b.metadata?{G:"div",Ga:["ytp-ce-channel-metadata","yt-ui-ellipsis","yt-ui-ellipsis-3"],va:b.metadata}:""]}]}]}]},{G:"div",L:"ytp-ce-expanding-image",W:G3(b)}]};c=new g.W(c);var d=g.fg(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton&&b.channelId){g.N(d,"ytp-ce-subscribe-button");if(a.player.U().i){var e=null;var f=b.sessionData.itct}else e="endscreen",f=null;e=new g.pO(b.subscribeButton.subscribeText,
b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,!!b.subscribeButton.enabled,!!b.subscribeButton.classic,b.channelId,!!b.subscribeButton.subscribed,e,f,b.subscribeButton.signinUrl,a.player);d.appendChild(e.element);a.K.push(e)}break;case "WEBSITE":a={G:"div",Ga:["ytp-ce-element","ytp-ce-website"],W:{tabindex:"0","aria-label":b.Xt||"","aria-hidden":"true"},T:[{G:"div",L:"ytp-ce-element-shadow"},{G:"div",L:"ytp-ce-expanding-overlay",T:[{G:"div",L:"ytp-ce-expanding-overlay-hider"},
{G:"div",L:"ytp-ce-expanding-overlay-background"},{G:"div",L:"ytp-ce-expanding-overlay-content",T:[{G:"div",L:"ytp-ce-expanding-overlay-body",T:[{G:"div",L:"ytp-ce-expanding-overlay-body-padding",T:[{G:"div",L:"ytp-ce-website-title",W:{dir:g.Xq(b.title||"")},va:b.title},{G:"div",L:"ytp-ce-website-metadata",va:b.metadata},{G:"a",Ga:["ytp-ce-website-goto","ytp-ce-link"],W:{href:H3(a,b.targetUrl),target:"_blank",tabindex:"-1"},va:b.callToAction}]}]}]}]},{G:"div",L:"ytp-ce-expanding-image",W:G3(b)},{G:"div",
L:"ytp-ce-expanding-icon",W:NMa(b.iconUrl)}]};c=new g.W(a);break;case "CREATOR_MERCHANDISE":c="",b.productPrice&&(c={G:"div",L:"ytp-ce-merchandise-price-container",T:[{G:"div",L:"ytp-ce-merchandise-price",va:b.productPrice}]},b.additionalFeesText&&c.T.push({G:"div",L:"ytp-ce-merchandise-additional-fees",va:b.additionalFeesText})),a={G:"div",Ga:["ytp-ce-element","ytp-ce-merchandise"],W:{tabindex:"0","aria-label":b.Xt||"","aria-hidden":"true"},T:[{G:"div",L:"ytp-ce-element-shadow"},{G:"div",L:"ytp-ce-expanding-overlay",
T:[{G:"div",L:"ytp-ce-expanding-overlay-hider"},{G:"div",L:"ytp-ce-expanding-overlay-background"},{G:"div",L:"ytp-ce-expanding-overlay-content",T:[{G:"div",L:"ytp-ce-expanding-overlay-body",T:[{G:"div",L:"ytp-ce-expanding-overlay-body-padding",T:[{G:"div",L:"ytp-ce-merchandise-title",W:{dir:g.Xq(b.title||"")},va:b.title},c,{G:"div",L:"ytp-ce-merchandise-metadata",va:b.metadata},{G:"a",Ga:["ytp-ce-merchandise-goto","ytp-ce-link"],W:{href:H3(a,b.targetUrl),target:"_blank",tabindex:"-1"},va:b.callToAction}]}]}]}]},
{G:"div",L:"ytp-ce-expanding-image",W:G3(b)},{G:"div",L:"ytp-ce-merchandise-invideo-cta-container",T:[{G:"div",L:"ytp-ce-merchandise-invideo-cta",va:b.callToAction||void 0}]}]},c=new g.W(a)}b.sR&&g.N(c.element,"ytp-ce-placeholder");return c},G3=function(a){if(a.wI)var b=a.wI.thumbnails;
return NMa(b?b[b.length-1].url:null)},NMa=function(a){return a?{style:"background-image: url("+a+")"}:{}},MMa=function(a,b,c){function d(m){m&&(b.Sa("blur",function(){"none"!=m.style.display&&a.V&&m.focus()}),b.S(m,"focus",f),b.S(m,"blur",h))}
function e(m){a.J+=m;0<a.J?(g.N(b.element,"ytp-ce-force-expand"),I3(a,c.id,!0)):(g.Lq(b.element,"ytp-ce-force-expand"),g.Lq(b.element,"ytp-ce-element-hover"),I3(a,c.id,!1))}
function f(){e(1)}
function h(){e(-1)}
b.Sa("mouseenter",function(){J3(a,b,c)});
b.Sa("mouseleave",function(){K3(a,b,c)});
a.player.U().i||b.Sa("click",function(){g.N(b.element,"ytp-ce-element-hover")});
b.Sa("click",function(m){OMa(a,c,m)});
b.Sa("keypress",function(m){OMa(a,c,m)});
b.Sa("focus",function(){J3(a,b,c)});
b.Sa("blur",function(){K3(a,b,c)});
b.Sa("touchstart",function(){J3(a,b,c)});
var l=g.hg("ytp-ce-expanding-overlay-hider",b.element);l&&b.S(l,"touchstart",function(m){m=m||window.event;m.cancelBubble=!0;m.stopPropagation&&m.stopPropagation();g.Lq(b.element,"ytp-ce-element-hover");g.Lq(b.element,"ytp-ce-force-expand")});
b.Sa("keydown",function(m){a.V=9===m.keyCode&&!m.shiftKey});
d(g.hg("ytp-sb-subscribe",b.element));d(g.hg("ytp-sb-unsubscribe",b.element));b.Sa("focus",f);b.Sa("blur",h)},OMa=function(a,b,c){if(b.targetUrl&&(!c||"keypress"!==c.type||13===c.keyCode)){for(var d=c.target;d&&!g.Jq(d,"ytp-ce-element");){g.Jq(d,"subscribe-label")&&L3(a,b);
if(g.Jq(d,"ytp-ce-channel-subscribe"))return;d=g.xg(d)}if(!d||g.Jq(d,"ytp-ce-element-hover")){c.preventDefault();c.stopPropagation();if(d=a.i[b.id])K3(a,d,b),d.element.blur();if(c.ctrlKey||c.metaKey||"new"===b.dW)L3(a,b),a.player.sendVideoStatsEngageEvent(17,void 0),a.player.pauseVideo(),c=g.Pc(H3(a,b.targetUrl)),c=g.Lc(c),g.NJ(c,void 0,b.sessionData);else{var e=a.player.getVideoData().D,f=function(){var h=H3(a,b.targetUrl),l=b.sessionData,m=g.vs(h);e&&m&&(m.v||m.list)?a.player.Lj(m.v,l,m.list,!1):
g.MJ(h,l)};
L3(a,b,function(){a.player.sendVideoStatsEngageEvent(17,f)})}}}},H3=function(a,b){a=a.player.U();
if(b){if(b.startsWith("//"))return a.protocol+":"+b;if(b.startsWith("/"))return g.VF(a)+b}else return"";return b},J3=function(a,b,c){g.Jq(b.element,"ytp-ce-element-hover")||("VIDEO"===c.type||"PLAYLIST"===c.type?g.N(b.element,"ytp-ce-element-hover"):a.player.U().i?(new g.K(function(){g.N(b.element,"ytp-ce-element-hover")},200)).start():g.N(b.element,"ytp-ce-element-hover"),M3(a,c.iR),I3(a,c.id,!0))},K3=function(a,b,c){g.Lq(b.element,"ytp-ce-element-hover");
g.Lq(b.element,"ytp-ce-force-expand");I3(a,c.id,!1)},I3=function(a,b,c){a.u&&(c?a.C.show():a.C.hide());
for(var d=g.r(Object.keys(a.i)),e=d.next();!e.done;e=d.next())e=e.value,e!==b&&g.O(a.i[e].element,"ytp-ce-element-shadow-show",c)},M3=function(a,b,c){function d(){f||(e++,e===b.length&&(h.stop(),c&&c()))}
if(!b||0===b.length||E3(a))c&&c();else{b=PMa(a,b);var e=0,f=!1,h=new g.K(function(){f=!0;c&&c()},1E3,a);
h.start();for(a=0;a<b.length;a++)g.Mu(b[a],d)}},L3=function(a,b,c){M3(a,b.clickUrls,c);
(a=g.fy())&&b.pR&&g.sz(a,b.visualElement)},PMa=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce;
a=a.player.getCurrentTime().toFixed(2);c={CPN:c,AD_CPN:c,MT:a};a=[];for(var d=0;d<b.length;d++)a.push(QMa(b[d],c));return a},QMa=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(c){var d=unescape(c);
d=d.substring(1,d.length-1);return b[d]?escape(b[d]):c})},RMa=function(a){return Array.isArray(a)&&a.length?a[0]:a},N3=function(a){return"string"===typeof a?a:""},O3=function(a,b,c){for(var d in b)if(b[d]===a)return a;
return c},SMa=function(a){this.externalId=a},TMa=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.i=d},P3=function(a){return a.value?a.value:null},Q3=function(a){if(!a)return null;
var b=g.Pc(N3(a.value));b=g.Lc(b);if(!b)return null;var c=O3(a.target,UMa,"current");if(null==c)a=null;else{var d=a.show_link_icon;a=new TMa(b,c,"true"===d||"false"===d?"true"===d:!0,null!=a.pause_on_navigation?a.pause_on_navigation:!0)}return a},VMa=function(a,b,c,d){this.type=a;
this.trigger=b;this.url=c;this.subscribeData=d},YMa=function(a){if(!a)return null;
var b=O3(a.type,WMa),c=O3(a.trigger,XMa),d=RMa(a.url);d=Q3(d?d:null);a=RMa(a.subscribeData);var e=a?a:null;e?(a=N3(e.external_user_id),e=N3(e.subscription_token),a=a&&e?new SMa(a):null):a=null;return b?new VMa(b,c,d,a):null},R3=function(a,b,c,d,e){this.id=a;
this.type=b;this.style=c;this.data=e;this.action=d||[]},ZMa=function(a,b){return g.fb(a.action,b,void 0)},$Ma=function(a,b){this.context=a;
this.i=b},T3=function(a){return a.customMessage?S3("div","iv-card-message",a.customMessage):""},U3=function(a,b){a="background-image: url("+a+");";
var c=[];b&&c.push(b);return{G:"div",L:"iv-card-image",W:{style:a},T:c}},V3=function(a){if(!a.metaInfo||0===a.metaInfo.length)return"";
var b=[];a=g.r(a.metaInfo);for(var c=a.next();!c.done;c=a.next())b.push(S3("li","",c.value));return{G:"ul",L:"iv-card-meta-info",T:b}},S3=function(a,b,c){b?"string"===typeof b?b={"class":b}:Array.isArray(b)&&(b={"class":b.join(" ")}):b={};
b.dir=g.Xq(c);return{G:a,W:b,va:c}},aNa=function(a){if(!a.customMessage)return"";
var b=["iv-card-action","iv-card-primary-link"],c={};a.ox&&(b.push("iv-card-action-icon"),c.style="background-image: url("+a.ox+");");c.dir=g.Xq(a.customMessage);var d=[{G:"span",va:a.customMessage}];a.showLinkIcon&&(d.push("\u00a0"),d.push({G:"span",L:"iv-card-link-icon"}));return{G:"div",Ga:b,W:c,T:d}},W3=function(a,b,c,d){if(d){b=g.r(b);
for(var e=b.next();!e.done;e=b.next())a.i(e.value,d,c.id,c.sessionData,c.tracking.click,5)}},bNa=function(a,b){this.merchant=a;
this.price=b},cNa=function(a){var b;
(b=a)&&!(b=1<a.length?"/"===a.charAt(0)&&"/"!==a.charAt(1):"/"===a)&&(b=a.replace(/^(https?:)?\/\//,""),b=b.split("/",1),b=!b||1>b.length||!b[0]?[]:b[0].toLowerCase().split(".").reverse(),b="com"===b[0]&&"youtube"===b[1]||"be"===b[0]&&"youtu"===b[1]);return b?-1===a.indexOf("/redirect?"):!1},dNa=function(a,b){return b?b:cNa(a)?"current":"new"},X3=function(a,b){g.H.call(this);
var c=this;this.element=a;this.context=b;this.fb=!1;this.Qa=new Map;this.Ta=new Map;this.context.I.addEventListener(g.kA("annotations_module"),function(d){(d=c.Qa.get(d))&&d.apply(c)});
this.context.I.addEventListener(g.lA("annotations_module"),function(d){(d=c.Ta.get(d))&&d.apply(c)})},Y3=function(a,b,c,d,e,f,h){a.context.i.Sa(b,"click",function(l){a.iB(c,d,e,f||[],h||0,l)});
a.context.i.Sa(b,"touchstart",function(){a.fb=!1});
a.context.i.Sa(b,"touchmove",function(){a.fb=!0})},eNa=function(a){if(a.urlEndpoint&&a.urlEndpoint.url)return a.urlEndpoint.url;
if(a.watchEndpoint&&a.watchEndpoint.videoId){var b="/watch?v="+a.watchEndpoint.videoId;a.watchEndpoint.playlistId&&(b+="&list="+a.watchEndpoint.playlistId);a.watchEndpoint.index&&(b+="&index="+a.watchEndpoint.index);a.watchEndpoint.startTimeSeconds&&(b+="&t="+a.watchEndpoint.startTimeSeconds);return b}return null},Z3=function(a,b,c){return{uJ:(a.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
click:(c.loggingUrls||[]).map(function(d){return d.baseUrl||""}),
close:(b.dismissLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
qM:(b.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
hA:(b.clickLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""})}},b4=function(a,b,c){X3.call(this,b,c);
var d=this;this.I=a;this.eventId=null;this.La=this.ob=this.B=this.Sd=!1;this.ya=null;this.cards=[];this.kb=this.N=this.Ha=this.D=this.Ka=this.i=null;this.ea=[];this.K=this.re=this.Ca=null;this.J=0;this.Aa=new g.K(g.Ia,c.X.hd?4E3:3E3);g.J(this,this.Aa);this.bb=new g.K(g.Ia);g.J(this,this.bb);this.ma=new $Ma(c,function(e,f,h,l,m,n){Y3(d,e,f,h,l,m,n)});
this.V=new g.W({G:"div",L:"iv-drawer",W:{id:"iv-drawer"},T:[{G:"div",L:"iv-drawer-header",W:{"aria-role":"heading"},T:[{G:"span",L:"iv-drawer-header-text"},{G:"button",Ga:["iv-drawer-close-button","ytp-button"],W:{"aria-label":"Sembunyikan kartu",tabindex:"0"}}]},{G:"div",L:"iv-drawer-content"}]});g.J(this,this.V);this.C=this.V.element;this.Xa=new g.LL(this.V,330);g.J(this,this.Xa);this.gb=g.hg("iv-drawer-header-text",this.C);this.u=g.hg("iv-drawer-content",this.C);this.addCueRange(0,1E3*c.videoData.lengthSeconds,
"",function(){d.ob&&$3(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.ob=d.B)&&a4(d)})},fNa=function(a,b){b=b.data;
b.autoOpenMs&&a.addCueRange(b.autoOpenMs,0x8000000000000,"",function(){$3(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
b.autoCloseMs&&a.addCueRange(b.autoCloseMs,0x8000000000000,"",function(){a4(a)});
var c=b.headerText;g.zg(a.gb,c);a.N&&a.N.setAttribute("title",c);b.eventId&&(a.eventId=b.eventId);a.Ca=g.$x(b.trackingParams);a.K=g.$x(b.closeTrackingParams);a.re=g.$x(b.iconTrackingParams)},gNa=function(a,b){var c=b.cardId?b.cardId:"cr:"+a.J;
if(b.content.simpleCardContentRenderer){if(!b.cueRanges.length)return;var d=b.content.simpleCardContentRenderer,e=b.teaser.simpleCardTeaserRenderer,f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.J,type:"simple",teaserText:g.rA(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:c4(a,c,b,d),sponsored:!1,tracking:Z3(d,e,d.command),xl:d.trackingParams?g.$x(d.trackingParams):null,Oi:e.trackingParams?
g.$x(e.trackingParams):null,re:f&&f.trackingParams?g.$x(f.trackingParams):null,imageUrl:d4(d.image.thumbnails,290).url,displayDomain:d.displayDomain?g.rA(d.displayDomain):null,showLinkIcon:!!d.showLinkIcon,ox:null,title:d.title?g.rA(d.title):"",customMessage:d.callToAction?g.rA(d.callToAction):"",url:d.command.urlEndpoint.url?Q3({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:d.command.urlEndpoint.url}):null};e4(a,b)}else if(b.content.collaboratorInfoCardContentRenderer){if(!b.cueRanges.length)return;
d=b.content.collaboratorInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.J,type:"collaborator",teaserText:g.rA(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:c4(a,c,b,d),sponsored:!1,tracking:Z3(d,e,d.endpoint),xl:d.trackingParams?g.$x(d.trackingParams):null,Oi:e.trackingParams?g.$x(e.trackingParams):null,re:f&&f.trackingParams?
g.$x(f.trackingParams):null,channelId:d.endpoint.browseEndpoint.browseId,customMessage:d.customText?g.rA(d.customText):null,profileImageUrl:d4(d.channelAvatar.thumbnails,290).url,title:d.channelName?g.rA(d.channelName):"",metaInfo:[d.subscriberCountText?g.rA(d.subscriberCountText):""],url:Q3({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:d.endpoint.browseEndpoint.canonicalBaseUrl?d.endpoint.browseEndpoint.canonicalBaseUrl:"/channel/"+d.endpoint.browseEndpoint.browseId})};
e4(a,b)}else if(b.content.playlistInfoCardContentRenderer){if(!b.cueRanges.length)return;d=b.content.playlistInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.J,type:"playlist",teaserText:g.rA(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:c4(a,c,b,d),sponsored:!1,tracking:Z3(d,e,d.action),xl:d.trackingParams?g.$x(d.trackingParams):
null,Oi:e.trackingParams?g.$x(e.trackingParams):null,re:f&&f.trackingParams?g.$x(f.trackingParams):null,Lw:d4(d.playlistThumbnail.thumbnails,258).url,customMessage:d.customMessage?g.rA(d.customMessage):null,playlistVideoCount:g.rA(d.playlistVideoCount),title:d.playlistTitle?g.rA(d.playlistTitle):"",metaInfo:[d.channelName?g.rA(d.channelName):"",d.videoCountText?g.rA(d.videoCountText):""],url:Q3({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:eNa(d.action)})};e4(a,b)}else if(b.content.videoInfoCardContentRenderer){if(!b.cueRanges.length)return;
d=b.content.videoInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.J,type:"video",teaserText:g.rA(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:c4(a,c,b,d),sponsored:!1,tracking:Z3(d,e,d.action),xl:d.trackingParams?g.$x(d.trackingParams):null,Oi:e.trackingParams?g.$x(e.trackingParams):null,re:f&&f.trackingParams?g.$x(f.trackingParams):
null,Lw:d4(d.videoThumbnail.thumbnails,258).url,videoDuration:d.lengthString?g.rA(d.lengthString):null,customMessage:d.customMessage?g.rA(d.customMessage):null,title:d.videoTitle?g.rA(d.videoTitle):"",metaInfo:[d.channelName?g.rA(d.channelName):"",d.viewCountText?g.rA(d.viewCountText):""],isLiveNow:!!d.badge,url:Q3({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:eNa(d.action)})};e4(a,b)}a.J++},d4=function(a,b){for(var c=-1,d=-1,e=0;e<a.length;e++){if(a[e].height===b||290===
a[e].width)return a[e];
((a[e].height||0)<b||290>(a[e].width||0))&&(0>c||(a[c].height||0)<(a[e].height||0)||(a[c].width||0)<(a[e].width||0))?c=e:((a[e].height||0)>=b||290<=(a[e].width||0))&&(0>d||(a[d].height||0)>(a[e].height||0)||(a[d].width||0)>(a[e].width||0))&&(d=e)}return a[0<=d?d:c]},c4=function(a,b,c,d){return{feature:c.feature?c.feature:"cards",
src_vid:a.context.videoData.videoId,annotation_id:b,ei:a.context.videoData.eventId||"",itct:d.trackingParams||""}},iNa=function(a,b){if(b=hNa(a,b))b===a.i&&(a.i=null),a.I.removeCueRange(b.card.id),g.wg(b.YB),g.ob(a.cards,b),a.sx(),f4(a)},$3=function(a,b,c){if(!a.B){a.Xa.show();
a.Ka=new g.K(function(){g.N(a.context.I.getRootNode(),g.ZT.IV_DRAWER_OPEN)},0);
a.Ka.start();a.ya=g.ku(a.u,"mousewheel",function(h){a.Aa.start();h.preventDefault();h=h||window.event;var l=0;"MozMousePixelScroll"==h.type?l=0==(h.axis==h.HORIZONTAL_AXIS)?h.detail:0:window.opera?l=h.detail:l=0==h.wheelDelta%120?"WebkitTransform"in document.documentElement.style?window.chrome&&0==navigator.platform.indexOf("Mac")?h.wheelDeltaY/-30:h.wheelDeltaY/-1.2:h.wheelDelta/-1.6:h.wheelDeltaY/-3;if(h=l)a.u.scrollTop+=h});
a.B=!0;var d=g.fy();d&&a.Ca&&a.K&&g.qz(d,[a.Ca,a.K]);b={TRIGGER_TYPE:b};for(var e=g.r(a.cards),f=e.next();!f.done;f=e.next())f=f.value,f.dK||(f.dK=!0,jNa(a.context.logger,f.card.tracking.uJ,b)),d&&g.qz(d,[f.card.xl]);r3(a.I);c&&(a.D=new g.K(function(){a.Ha=a.N;a.kb.focus()},330),a.D.start())}},a4=function(a){a.B&&(a.Xa.hide(),g.lu(a.ya),a.ya=null,g.Lq(a.context.I.getRootNode(),g.ZT.IV_DRAWER_OPEN),a.B=!1,r3(a.I),a.D&&a.D.stop(),a.D=new g.K(function(){a.Ha&&(a.Ha.focus(),a.Ha=null)},330),a.D.start())},
lNa=function(a){g.Kq(a.element,[g.ZT.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.YM(a.I,a.C,5);kNa(a);a.N=g.hg("ytp-cards-button",a.I.getRootNode());a.kb=g.hg("iv-drawer-close-button",a.C);a.Sd=!0},kNa=function(a){var b=g.hg("iv-drawer-close-button",a.C);
a.context.i.Sa(b,"click",a.RP,a);a.context.i.Sa(a.u,"touchend",function(){a.Aa.start()});
a.context.i.Sa(a.u,"scroll",a.dQ,a);a.context.u.subscribe("onHideControls",function(){a.La=!0});
a.context.u.subscribe("onShowControls",function(){a.La=!1});
a.context.u.subscribe("onVideoAreaChange",function(){a.La=g.Jq(a.I.getRootNode(),"ytp-autohide")});
a.ea.push(g.Tu("iv-button-shown",a.BR,a));a.ea.push(g.Tu("iv-button-hidden",a.AR,a));a.ea.push(g.Tu("iv-teaser-shown",a.rO,a));a.ea.push(g.Tu("iv-teaser-hidden",a.DR,a));a.ea.push(g.Tu("iv-teaser-clicked",a.qO,a))},e4=function(a,b){a.Sd||lNa(a);
iNa(a,b.id);var c=mNa(a,b);if(c){var d={card:b,YB:c.element,dK:!1},e=nNa(a,d);g.ub(a.cards,e,0,d);c.Da(a.u,e);a.sx();b.autoOpen?a.addCueRange(b.startMs,0x8000000000000,b.id,function(){a.B||(a.i=d,f4(a),oNa(a,d),$3(a,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(c=1E3*a.context.I.getCurrentTime(),5E3>c&&c>b.startMs&&pNa(a,d),a.addCueRange(b.startMs,b.startMs+1,b.id,function(){pNa(a,d)}),f4(a))}},mNa=function(a,b){switch(b.type){case "simple":a=a.ma;
var c=b.displayDomain?{G:"div",L:"iv-card-image-text",va:b.displayDomain}:void 0;var d=aNa(b);c={G:"div",Ga:["iv-card"],T:[{G:"a",L:"iv-click-target",W:{href:b.url?P3(b.url)||"":""},T:[U3(b.imageUrl,c),{G:"div",L:"iv-card-content",T:[S3("h2",void 0,b.title),d]}]}]};c=new g.W(c);W3(a,g.gg("iv-click-target",c.element),b,b.url);return c;case "collaborator":return a=a.ma,c={G:"div",Ga:["iv-card","iv-card-channel"],T:[{G:"a",Ga:["iv-click-target"],W:{href:P3(b.url)||"","data-ytid":b.channelId},T:[U3(b.profileImageUrl),
{G:"div",L:"iv-card-content",T:[T3(b),{G:"h2",L:"iv-card-primary-link",va:b.title},V3(b)]}]}]},c=new g.W(c),W3(a,g.gg("iv-click-target",c.element),b,b.url),c;case "playlist":return a=a.ma,c={G:"div",Ga:["iv-card","iv-card-playlist"],T:[{G:"a",L:"iv-click-target",W:{href:P3(b.url)||""},T:[U3(b.Lw,{G:"div",L:"iv-card-image-overlay",T:[{G:"span",L:"iv-card-playlist-video-count",va:b.playlistVideoCount}]}),{G:"div",L:"iv-card-content",T:[T3(b),S3("h2","iv-card-primary-link",b.title),V3(b)]}]}]},c=new g.W(c),
W3(a,g.gg("iv-click-target",c.element),b,b.url),c;case "productListing":a=a.ma;var e=!g.kb(b.offers);c=["iv-card"];d="";var f=aNa(b);e&&(c.push("iv-card-product-listing"),d="iv-card-primary-link",f=b.offers[0],e=[],f.price&&e.push({G:"div",L:"iv-card-offer-price",va:f.price}),f.merchant&&e.push({G:"div",L:"iv-card-offer-merchant",va:f.merchant}),f={G:"div",T:e});e=b.url?P3(b.url)||"":"";c={G:"div",Ga:c,W:{tabindex:"0"},T:[{G:"a",Ga:["iv-card-image","iv-click-target"],W:{style:"background-image: url("+
b.imageUrl+");",href:e,"aria-hidden":"true",tabindex:"-1"}},{G:"div",L:"iv-card-content",T:[b.sponsored?{G:"div",L:"iv-card-sponsored",T:["Bersponsor",{G:"div",L:"iv-ad-info-container",T:[{G:"div",L:"iv-ad-info",va:"{{adInfo}}"},{G:"div",L:"iv-ad-info-icon-container",T:[{G:"div",L:"iv-ad-info-icon"},{G:"div",L:"iv-ad-info-callout"}]}]}]}:"",{G:"a",L:"iv-click-target",W:{href:e},T:[S3("h2",d,b.title),f]}]}]};c=new g.W(c);d=g.sg("span");g.zg(d,"Anda melihat produk ini karena menurut kami relevan dengan video tersebut. Google dapat menerima kompensasi dari penjual.");
c.fd(d,"adInfo");W3(a,g.gg("iv-click-target",c.element),b,b.url);return c;case "video":return a=a.ma,d=b.videoDuration?{G:"span",L:"iv-card-video-duration",va:b.videoDuration}:void 0,f=b.isLiveNow?{G:"span",Ga:["yt-badge","yt-badge-live"],va:"LIVE SEKARANG"}:null,e={G:"div",Ga:["iv-card","iv-card-video"],T:[{G:"a",L:"iv-click-target",W:{href:(null===(c=b.url)||void 0===c?void 0:P3(c))||""},T:[U3(b.Lw,d),{G:"div",L:"iv-card-content",T:[T3(b),S3("h2","iv-card-primary-link",b.title),V3(b),f]}]}]},c=
new g.W(e),W3(a,g.gg("iv-click-target",c.element),b,b.url),c;default:return null}},nNa=function(a,b){if(0===a.cards.length)return 0;
a=g.gb(a.cards,function(c){return b.card.startMs>c.card.startMs||b.card.startMs===c.card.startMs&&b.card.timestamp>=c.card.timestamp?!0:!1});
return-1===a?0:a+1},qNa=function(a){return a.i?"productListing"===a.i.card.type:g.vm(a.cards,function(b){return"productListing"===b.card.type})},f4=function(a){g.O(a.I.getRootNode(),"ytp-cards-shopping-active",qNa(a))},pNa=function(a,b){if(!g.Jq(a.I.getRootNode(),"ytp-cards-teaser-shown")){if(a.i!==b){var c=g.fy(),d=a.i?a.i.card.re:a.re;
c&&d&&g.rz(c,[d]);a.i=b;f4(a)}if(c="none"!=a.element.style.display)g.T(a.context.I.U().experiments,"html5_enable_single_video_vod_ivar_on_pacf")||2!==a.context.I.getPresentingPlayerType()?(c=a.context.I.getPlayerState(),d=0===c&&0===a.context.I.getCurrentTime(),c=1===c||3===c||d):c=1===a.context.I.getAdState();c&&b.card.teaserDurationMs&&a.I.Js(!0,{teaserText:b.card.teaserText,durationMs:b.card.teaserDurationMs});a.bb.isActive()||((!a.B||!a.Aa.isActive()&&a.La)&&oNa(a,b),a.bb.start(910+b.card.teaserDurationMs))}},
oNa=function(a,b){a.V.zb?(b=new w3([0,
a.u.scrollTop],[0,b.YB.offsetTop],600,BMa),a.context.B.Sa(b,"animate",function(c){a.u.scrollTop=c.y}),a.context.B.Sa(b,"finish",function(c){a.u.scrollTop=c.y}),b.play()):(g.bL(a.V,!0),a.u.scrollTop=b.YB.offsetTop,g.bL(a.V,!1))},g4=function(a){return a.i&&a.i.card?a.i.card:a.cards[0]&&a.cards[0].card?a.cards[0].card:null},hNa=function(a,b){return g.fb(a.cards,function(c){return c.card.id===b})},h4=function(a,b,c){X3.call(this,a,b);
this.annotation=c;this.isActive=!1},rNa=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&a.addCueRange(b.start_ms,b.end_ms,a.annotation.id,function(){a.show()},function(){a.hide()})},i4=function(a,b,c){h4.call(this,a,b,c);
this.u=null;this.K=!1;this.B=null;this.C=!1;this.i=this.J=this.D=null},sNa=function(a,b){var c=void 0===c?0:c;
var d=zMa(b).width;g.Tl(b,d);c=new y3(b,[d,b.offsetTop],[d-d-c,b.offsetTop],200,AMa);g.J(a,c);a.context.B.Sa(c,"begin",function(){g.bm(b,!0)});
c.play()},vNa=function(a,b){if(b.channel_name){var c=a.createElement({G:"div",
Ga:["iv-branding-context-name"],va:b.channel_name}),d=a.createElement({G:"div",Ga:["iv-branding-context-subscribe"]}),e=b.standalone_subscribe_button_data;e&&(a.i=new g.pO(e.subscribeText,e.subscribeCount,e.unsubscribeText,e.unsubscribeCount,!!e.enabled,!!e.classic,b.channel_id,!!e.subscribed,e.feature,b.session_data.itct,e.signInUrl,a.context.I),a.i.Da(d));var f=a.createElement({G:"div",Ga:["iv-branding-context-subscribe-caret"]}),h=a.createElement({G:"div",Ga:["branding-context-container-inner"]});
h.appendChild(f);h.appendChild(c);h.appendChild(d);g.bm(h,!1);var l=a.createElement({G:"div",Ga:["branding-context-container-outer"]});l.appendChild(h);g.Ml(l,"right",b.image_width+"px");a.element.appendChild(l);a.B=new g.K(function(){tNa(a,h,l)},500);
g.J(a,a.B);a.context.i.Sa(a.element,"mouseover",function(){uNa(a,h,l,f,b.image_height)});
a.context.i.Sa(a.element,"mouseout",function(){a.B.start()})}},uNa=function(a,b,c,d,e){a.B.stop();
if(!a.C){var f=g.am(b);a.i||(b.style.width=g.Sl(f.width,!0),c.style.width=g.Sl(f.width,!0));g.Ml(d,"top",f.height-Math.max(Math.min(f.height,e)/2+10,20)+"px");g.Ml(d,"right","1px");a.C=!0;g.bm(b,!0);a.D=new g.K(function(){g.N(this.element,"iv-branding-active")},0,a);
a.D.start()}},tNa=function(a,b,c){g.Lq(a.element,"iv-branding-active");
a.J=new g.K(function(){g.bm(b,!1);a.i||(c.style.width=g.Sl(0,!0))},250);
a.J.start();a.C=!1},wNa=function(a,b,c,d,e,f,h){this.i=a;
this.B=b;this.X=c;this.videoData=d;this.logger=e;this.I=f;this.u=h},j4=function(a,b,c){h4.call(this,a,b,c);
var d=this;this.N=this.isCollapsed=this.V=!1;this.J=5E3;this.u=this.B=this.i=this.C=null;this.K=this.createElement({G:"div",Ga:["iv-promo-contents"]});this.D=new g.K(function(){d.i.setAttribute("aria-hidden","true");g.bm(d.B,!1);g.bm(d.u,!0)},700,this);
g.J(this,this.D)},xNa=function(a){var b=a.annotation.data;
if("cta"===a.annotation.style)var c=6;else if("video"===a.annotation.style||"playlist"===a.annotation.style)c=7;a.J=b.collapsedelay_ms||a.J;var d=["iv-promo","iv-promo-inactive"];a.element.setAttribute("aria-hidden","true");a.element.setAttribute("aria-label","Promosi");a.element.tabIndex=0;var e=a.annotation.Qd(),f=b.image_url;if(f){var h=a.createElement({G:"div",Ga:["iv-promo-img","iv-click-target"]});f=a.createElement({G:"img",W:{src:f,"aria-hidden":"true"}});h.appendChild(f);b.video_duration&&
!b.is_live?(f=a.createElement({G:"span",L:"iv-promo-video-duration",va:b.video_duration}),h.appendChild(f)):b.playlist_length&&(f=a.createElement({G:"span",L:"iv-promo-playlist-length",va:b.playlist_length.toString()}),h.appendChild(f));e&&Y3(a,h,e,a.annotation.id,b.session_data,void 0,c)}e?(f=a.createElement({G:"a",L:"iv-promo-txt"}),g.pd(f,P3(e)),a.i=f):a.i=a.createElement({G:"div",L:"iv-promo-txt"});switch(a.annotation.style){case "cta":case "website":var l=a.createElement({G:"p",T:[{G:"strong",
va:b.text_line_1}]});var m=a.createElement({G:"p",T:[{G:"span",L:"iv-promo-link",va:b.text_line_2}]});if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");var n=a.createElement({G:"button",Ga:["iv-promo-round-expand-icon","ytp-button"]});f=a.createElement({G:"button",Ga:["iv-button","iv-promo-button"],T:[{G:"span",L:"iv-button-content",va:f}]});var p=a.createElement({G:"div",L:"iv-promo-button-container"});p.appendChild(f);e&&Y3(a,a.element,e,a.annotation.id,b.session_data,void 0,c)}g.N(a.i,
"iv-click-target");e&&Y3(a,a.i,e,a.annotation.id,b.session_data,void 0,c);break;case "playlist":case "video":l=a.createElement({G:"p",T:[{G:"span",va:b.text_line_1}]}),m=a.createElement({G:"p",T:[{G:"strong",va:b.text_line_2}]}),b.is_live&&(l=m,m=a.createElement({G:"span",Ga:["yt-badge","iv-promo-badge-live"],va:"LIVE SEKARANG"})),g.N(a.i,"iv-click-target"),e&&Y3(a,a.i,e,a.annotation.id,b.session_data,void 0,c),d.push("iv-promo-video")}l&&a.i.appendChild(l);m&&a.i.appendChild(m);a.K.appendChild(a.i);
p&&a.K.appendChild(p);c=a.createElement({G:"div",L:"iv-promo-actions"});a.u=a.createElement({G:"button",Ga:["iv-promo-expand","ytp-button"]});a.u.title="Luaskan";a.context.i.Sa(a.u,"click",function(q){k4(a,5E3,q)});
c.appendChild(a.u);g.bm(a.u,!1);a.context.i.Sa(a.element,"mouseover",a.LQ,a);a.context.i.Sa(a.element,"mouseout",a.KQ,a);a.context.i.Sa(a.element,"touchend",function(q){k4(a,5E3,q)});
a.B=a.createElement({G:"button",Ga:["iv-promo-close","ytp-button"]});a.B.title="Tutup";a.context.i.Sa(a.B,"click","cta"===a.annotation.style&&b.text_line_3?a.GQ:a.FQ,a);c.appendChild(a.B);g.Kq(a.element,d);h&&(a.element.appendChild(h),n&&h.appendChild(n));a.element.appendChild(a.K);a.element.appendChild(c)},k4=function(a,b,c){c.stopPropagation();
yNa(a);zNa(a,b);a.i.focus()},ANa=function(a){a.isCollapsed||a.N||a.C||(g.N(a.element,"iv-promo-collapsed"),a.isCollapsed=!0,a.D.start())},yNa=function(a){a.D.stop();
a.isCollapsed&&(g.Mq(a.element,["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.isCollapsed=!1,a.i&&a.i.removeAttribute("aria-hidden"),g.bm(a.u,!1),g.bm(a.B,!0))},zNa=function(a,b){a.C||(a.C=g.lh(function(){l4(this);
ANa(this)},b,a))},l4=function(a){a.C&&(g.C.clearTimeout(a.C),a.C=null)},BNa=function(a){this.I=a},jNa=function(a,b,c){b&&(c?m4(a,b.map(function(d){return g.xq(d,c)})):m4(a,b))},m4=function(a,b,c,d){var e=1,f=void 0,h=-1;
if(c){var l=!1;f=function(){e--;e||l||(clearTimeout(h),l=!0,c())};
h=setTimeout(function(){l=!0;c()},1E3)}b=g.r(b||[]);
for(var m=b.next();!m.done;m=b.next())m=m.value,e++,g.Mu(m,f);d&&(e++,0!==d&&a.I.sendVideoStatsEngageEvent(d,f))},n4=function(a){g.kN.call(this,a);
var b=this;this.V=!1;this.loadNumber=0;this.K={};this.logger=new BNa(this.player);this.D=new g.aN(this);this.J=this.B=null;this.events=new g.aN(this);this.N=this.i=null;this.ea=[];g.J(this,this.D);this.D.S(this.player,"onVideoAreaChange",function(){b.Z("onVideoAreaChange")});
this.D.S(this.player,"onHideControls",function(){b.Z("onHideControls")});
this.D.S(this.player,"onShowControls",function(){b.Z("onShowControls")});
this.D.S(this.player,"resize",function(d){b.Z("resize",d)});
this.D.S(this.player,"presentingplayerstatechange",function(d){b.Z("presentingplayerstatechange",d)});
this.subscribe("presentingplayerstatechange",this.sO,this);this.subscribe("resize",this.oz,this);this.player.U().V.subscribe("vast_info_card_add",this.rL,this);g.J(this,this.events);this.ma=this.createElement({G:"div",L:"video-custom-annotations"});this.u=new g.W({G:"div",Ga:["ytp-player-content","ytp-iv-player-content"]});g.J(this,this.u);g.YM(this.player,this.u.element,4);this.u.hide();this.C=new g.W({G:"div",Ga:["ytp-iv-video-content"]});g.J(this,this.C);a=this.createElement({G:"div",L:"video-annotations"});
a.appendChild(this.ma);this.C.element.appendChild(a);this.oq()&&this.load();var c=this.createElement({G:"style"});(g.eg("HEAD")[0]||document.body).appendChild(c);g.mf(this,function(){g.wg(c)});
if(a=c.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},CNa=function(a){a=a.createElement({G:"div",
Ga:["annotation","annotation-type-custom"]});g.bm(a,!1);return a},DNa=function(a,b){b=!b.isCued()&&!g.V(b,1024);
g.bL(a.u,b);g.bL(a.C,b)},ENa=function(a,b,c){a.V=!0;
a.J=g.lt(b,c)},FNa=function(a,b){for(var c={},d=g.r(b.attributes),e=d.next();!e.done;e=d.next())e=e.value,c[e.name]=e.nodeValue;
for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],g.Ma(e)&&1==e.nodeType){if(c[e.tagName])var f=c[e.tagName];else if("data"===e.tagName){0<e.childNodes.length&&(f=e.childNodes[0].nodeValue,c[e.tagName]="string"===typeof f?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&"TEXT"===e.tagName?1===e.childNodes.length&&3===e.childNodes[0].nodeType?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push(FNa(a,e))}return c},INa=function(a){var b=a.player.getVideoData();
if(b.Ka){var c=a.player.U().V.get(b.videoId);if(c){var d={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:function(e,f,h){e=b.videoId;a.loaded&&a.loadNumber===a.loadNumber&&a.player.getVideoData().videoId===e&&(h=g.dt(h)&&h.responseXML?h.responseXML:null)&&o4(a,h)}};
g.Du()&&(d.onFinish=GNa(a,d.onFinish));d.postParams={ic_only:"1"};HNa(d,c);a.V=!0;g.lt(b.Ka,d)}}},HNa=function(a,b){a.method="POST";
a.postParams=a.postParams||{};b.tu&&(a.postParams.ic_coll=b.tu);b.xx&&(a.postParams.ic_xml=b.xx);b.Ow&&(a.postParams.ic_track=b.Ow)},JNa=function(a){var b=new g.W({G:"div"});
g.bm(b.element,!1);var c=new b4(a.player,b.element,p4(a));g.J(c,b);b.Da(a.u.element);c.Aw();return c},p4=function(a){if(!a.N){var b=new z3(a);
g.J(a,b);var c=new g.ek(a);g.J(a,c);a.N=new wNa(b,c,a.player.U(),a.player.getVideoData(),a.logger,a.player,a.hd)}return a.N},o4=function(a,b){var c=!1,d=b.getElementsByTagName("annotations");
if(d&&!(1>d.length)&&(d=d[0].getAttribute("itct"))){var e=g.fy();if(e){var f=g.dy();f&&g.jz(void 0,e,f,[g.$x(d)])}}b=b.getElementsByTagName("annotation");for(d=0;d<b.length;d++){f=FNa(a,b[d]);e=null;try{if(f){var h=f.id,l=/.+/;var m="string"===typeof h&&null!=l&&null!=h&&h.match(l)?h:"";var n=O3(f.type,KNa),p=O3(f.style,LNa),q=N3(f.data),t=0!==q.length?JSON.parse(q):{};var u=f.action;f=YMa;if(null==u)var x=null;else if(g.La(u)){l=[];for(var y=g.r(u),B=y.next();!B.done;B=y.next()){var F=f(B.value);
F&&l.push(F)}x=l}else{var G=f(u);x=G?[G]:[]}e=m&&n?new R3(m,n,p,x,t):null}else e=null}catch(za){}if(e)if("branding"===e.type||"promotion"===e.type){f=a;l=e;var I=CNa(f),L=null;switch(l.type){case "branding":if(f.player.U().Eb)break;f.u.element.appendChild(I);L=new i4(I,p4(f),l);break;case "promotion":g.YM(f.player,I,4),L=new j4(I,p4(f),l)}L&&L.Aw();if(f=L)g.J(a,f),a.K[e.id]=f}else if("card"===e.type||"drawer"===e.type){a.i||(a.i=JNa(a),g.J(a,a.i));if("card"===e.type){c=a.i;var da=e&&e.data&&e.data.card_type;
f=e.data;if(da)switch(l=f.tracking||{},l={uJ:l.impression,click:l.click,close:l.close,qM:l.teaser_impression,hA:l.teaser_click},I=f.tracking_params||{},L=null,da){case "collaborator":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,xl:I.card?g.$x(I.card):null,Oi:I.teaser?g.$x(I.teaser):null,re:I.icon?g.$x(I.icon):null,channelId:f.channel_id,
customMessage:f.custom_message?f.custom_message:null,profileImageUrl:f.image_url,title:f.title,metaInfo:f.meta_info,url:Q3({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url})};e4(c,e);break;case "playlist":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,xl:I.card?g.$x(I.card):null,Oi:I.teaser?
g.$x(I.teaser):null,re:I.icon?g.$x(I.icon):null,Lw:f.image_url,playlistVideoCount:f.playlist_video_count,customMessage:f.custom_message?f.custom_message:null,title:f.title,metaInfo:f.meta_info,url:Q3({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url})};e4(c,e);break;case "productListing":f.signin_url&&(L=Q3({target:"current",value:f.signin_url}));da=[];for(var M=f.offers||[],ha=0;ha<M.length;ha++)da.push(new bNa(g.wd(M[ha].merchant),g.wd(M[ha].price)));e={id:e.id,timestamp:f.timestamp||
0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,xl:I.card?g.$x(I.card):null,Oi:I.teaser?g.$x(I.teaser):null,re:I.icon?g.$x(I.icon):null,imageUrl:f.image_url,displayDomain:f.display_domain?f.display_domain:null,showLinkIcon:!!f.show_link_icon,ox:f.button_icon_url?f.button_icon_url:null,title:f.title,customMessage:f.custom_message?f.custom_message:null,url:Q3({pause_on_navigation:f.pause_on_navigation,
target:f.target||"new",value:f.url}),s$:L,r$:f.signin_title?f.signin_title:void 0,q$:f.signin_message?f.signin_message:void 0,offers:da};e4(c,e);break;case "simple":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,xl:I.card?g.$x(I.card):null,Oi:I.teaser?g.$x(I.teaser):null,re:I.icon?g.$x(I.icon):null,imageUrl:f.image_url,
displayDomain:f.display_domain?f.display_domain:null,showLinkIcon:!!f.show_link_icon,ox:f.button_icon_url?f.button_icon_url:null,title:f.title,customMessage:f.custom_message?f.custom_message:null,url:Q3({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url})};e4(c,e);break;case "video":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},
sponsored:f.sponsored||!1,tracking:l,xl:I.card?g.$x(I.card):null,Oi:I.teaser?g.$x(I.teaser):null,re:I.icon?g.$x(I.icon):null,Lw:f.image_url,videoDuration:f.video_duration||null,customMessage:f.custom_message?f.custom_message:null,title:f.title,metaInfo:f.meta_info,isLiveNow:!!f.is_live_now,url:Q3({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url})},e4(c,e)}}else fNa(a.i,e);c=!0}}c&&(r3(a.player),a.oz())},MNa=function(a,b){var c=!1;
a.i||(a.i=JNa(a),g.J(a,a.i));for(var d=g.r(b.cards||[]),e=d.next();!e.done;e=d.next())e=e.value,e.cardRenderer&&(gNa(a.i,e.cardRenderer),c=!0);c&&(c=a.i,d=b.headerText?g.rA(b.headerText):"",g.zg(c.gb,d),c.N&&c.N.setAttribute("title",d),c.context.videoData.eventId&&(c.eventId=c.context.videoData.eventId),c.Ca=b.trackingParams?g.$x(b.trackingParams):null,c.K=b.closeButton.infoCardIconRenderer.trackingParams?g.$x(b.closeButton.infoCardIconRenderer.trackingParams):null,c.re=b.icon.infoCardIconRenderer.trackingParams?
g.$x(b.icon.infoCardIconRenderer.trackingParams):null,r3(a.player),a.oz())},NNa=function(a,b,c,d,e){if(!a.player.U().Eb){var f=[];
b.navigationEndpoint&&b.navigationEndpoint.browseEndpoint&&b.navigationEndpoint.browseEndpoint.browseId&&f.push(new VMa("openUrl","click",new TMa("/channel/"+b.navigationEndpoint.browseEndpoint.browseId,"new",!0,!0),null));var h=b.watermark.thumbnails[0];d={channel_name:b.channelName,end_ms:b.endTimeMs,image_height:h.height,image_type:1,image_url:h.url,image_width:h.width,is_mobile:!1,session_data:{annotation_id:c,ei:e,feature:"iv",itct:b.trackingParams,src_vid:d},start_ms:b.startTimeMs};if(b.subscribeButton&&
b.subscribeButton.subscribeButtonRenderer){d.channel_id=b.subscribeButton.subscribeButtonRenderer.channelId;var l;b=b.subscribeButton.subscribeButtonRenderer;var m,n;h=e=null;b.subscribed?(b.subscriberCountWithUnsubscribeText&&(e=g.rA(b.subscriberCountWithUnsubscribeText)),b.subscriberCountText&&(h=g.rA(b.subscriberCountText))):(b.subscriberCountText&&(e=g.rA(b.subscriberCountText)),b.subscriberCountWithSubscribeText&&(h=g.rA(b.subscriberCountWithSubscribeText)));var p=b.signInEndpoint&&b.signInEndpoint.webNavigationEndpointData&&
b.signInEndpoint.webNavigationEndpointData.url?b.signInEndpoint.webNavigationEndpointData.url:(null===(n=null===(m=null===(l=b.signInEndpoint)||void 0===l?void 0:l.commandMetadata)||void 0===m?void 0:m.webCommandMetadata)||void 0===n?void 0:n.url)||"";l={subscribeText:g.rA(b.unsubscribedButtonText),subscribeCount:e||"",unsubscribeText:g.rA(b.subscribedButtonText),unsubscribeCount:h||"",enabled:b.enabled||!1,classic:!1,subscribed:b.subscribed||!1,feature:"iv",signInUrl:p};d.standalone_subscribe_button_data=
l}f=new R3(c,"branding","branding",f,d);l=CNa(a);a.u.element.appendChild(l);f=new i4(l,p4(a),f);f.Aw();g.J(f,f);a.K[c]=f}},GNa=function(a,b){return function(c){for(var d=[],e=0;e<arguments.length;++e)d[e-0]=arguments[e];
a.isDisposed()||a.ea.push(g.Au(0,function(){b.apply(null,g.v(d))}))}},ONa=function(a){return"annotation-editor"===a||"live-dashboard"===a};
g.RM.prototype.Js=g.ca(17,function(a,b){var c=g.BN(this.ub());c&&c.Js(a,b)});
var t3={},u3=null;g.Ra(w3,g.Oq);g.k=w3.prototype;g.k.getDuration=function(){return this.duration};
g.k.play=function(a){if(a||0==this.Ra)this.progress=0,this.coords=this.i;else if(this.yc())return!1;v3(this);this.startTime=a=g.Qa();-1==this.Ra&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.B=this.startTime;this.progress||this.lz();this.ji("play");-1==this.Ra&&this.ji("resume");this.Ra=1;var b=g.Oa(this);b in t3||(t3[b]=this);DMa();EMa(this,a);return!0};
g.k.stop=function(a){v3(this);this.Ra=0;a&&(this.progress=1);FMa(this,this.progress);this.ji("stop");this.Vv()};
g.k.pause=function(){this.yc()&&(v3(this),this.Ra=-1,this.ji("pause"))};
g.k.xa=function(){0==this.Ra||this.stop(!1);this.ji("destroy");w3.Xd.xa.call(this)};
g.k.destroy=function(){this.dispose()};
g.k.hB=function(){this.ji("animate")};
g.k.ji=function(a){this.dispatchEvent(new GMa(a,this))};
g.Ra(GMa,g.nf);g.Ra(x3,w3);x3.prototype.u=g.Ia;x3.prototype.hB=function(){this.u();x3.Xd.hB.call(this)};
x3.prototype.Vv=function(){this.u();x3.Xd.Vv.call(this)};
x3.prototype.lz=function(){this.u();x3.Xd.lz.call(this)};
g.Ra(y3,x3);y3.prototype.u=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};g.w(z3,g.H);z3.prototype.Sa=function(a,b,c,d){c=(0,g.D)(c,d||this.u);a=g.ku(a,b,c);this.i.push(a);return a};
z3.prototype.Oy=function(a,b,c,d){c=(0,g.D)(c,d||this.u);a=g.uu(a,b,c);this.i.push(a);return a};
z3.prototype.kc=function(a){g.lu(a);g.ob(this.i,a)};
z3.prototype.xa=function(){g.lu(this.i);this.i.length=0;g.H.prototype.xa.call(this)};g.w(D3,g.kN);g.k=D3.prototype;g.k.load=function(){g.kN.prototype.load.call(this);if(!E3(this)){var a=g.joa(this.player.getVideoData());a?(a=C3(a,IMa(this)),F3(this,a,!1)):JMa(this)}};
g.k.unload=function(){F3(this,null);this.B&&(this.B.abort(),this.B=null);g.kN.prototype.unload.call(this)};
g.k.Ze=function(a,b){return E3(this)?"loadCustomEndscreenRenderer"===a?(a=C3(b,"new"),F3(this,a),!0):null:null};
g.k.getOptions=function(){return E3(this)?["loadCustomEndscreenRenderer"]:[]};
g.k.xb=function(){if(this.endscreen&&this.endscreen.elements){var a=this.player.getVideoContentRect();if(a&&0!==a.width&&0!==a.height){var b=this.player.getPlayerSize();if(b&&0!==b.width&&0!==b.height){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<PNa.length;f++){var h=Math.abs(b.width-PNa[f]);if(-1===e||d>=h)e=f,d=h}d=QNa[e];this.u&&g.Ml(this.u.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.endscreen.elements.length;++b)if(f=this.endscreen.elements[b].id,e=this.i[f],
h=this.D[f],e&&h){var l=h.width*c/h.aspectRatio;f=Math.round(l*a.height);var m=a.left+Math.round(h.left*a.width),n=a.top+Math.round(h.top*a.height);g.$l(e.element,Math.round(h.width*a.width),f);g.Tl(e.element,m,n);g.Mq(e.element,RNa);m=h.left+h.width/2;h=h.top+l/2;g.N(e.element,.5>=m&&.5>=h?"ytp-ce-top-left-quad":.5<m&&.5>=h?"ytp-ce-top-right-quad":.5>=m&&.5<h?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.Mq(e.element,QNa);g.N(e.element,d);(e=g.fg(document,"div","ytp-ce-expanding-overlay-body",
e.element)[0])&&g.Ml(e,"height",f+"px")}}}}};
g.k.Bd=function(a){if(this.endscreen)if("ytp-ce-in-endscreen"===a.getId())M3(this,this.endscreen.impressionUrls),(a=g.fy())&&this.endscreen.visualElement&&g.kz(a,this.endscreen.visualElement,void 0);else{a=a.getId().substring(15);var b=this.i[a],c=this.D[a];g.N(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");b=this.player.getRootNode();g.N(b,"ytp-ce-shown");M3(this,c.impressionUrls);(b=g.fy())&&g.kz(b,c.visualElement,void 0);this.player.U().B&&this.player.Ma("endscreenelementshown",
a)}};
g.k.nf=function(a){if("ytp-ce-in-endscreen"!==a.getId()){a=a.getId().substring(15);var b=this.i[a];g.Lq(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden","true");b=this.player.getRootNode();g.Lq(b,"ytp-ce-shown");this.player.U().B&&this.player.Ma("endscreenelementhidden",a)}};
g.k.lV=function(a){var b=this;a.target===window&&(new g.K(function(){for(var c=g.r(Object.values(b.i)),d=c.next();!d.done;d=c.next())g.Mq(d.value.element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
var PNa=[346,426,470,506,570,640,853,1280,1920],QNa="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),RNa=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"];var UMa={D_:"current",o5:"new"};var WMa={CLOSE:"close",G5:"openUrl",tP:"subscribe"},XMa={ZX:"click",CLOSE:"close",V0:"hidden",Q6:"rollOut",R6:"rollOver",G7:"shown"};R3.prototype.Qd=function(){var a=ZMa(this,function(b){return"openUrl"===b.type&&null!=b.url});
return a?a.url:null};
var LNa={rX:"anchored",dN:"branding",CHANNEL:"channel",B_:"cta",Y0:"highlightText",Z1:"label",PLAYLIST:"playlist",m6:"popup",P7:"speech",tP:"subscribe",h8:"title",VIDEO:"video",q9:"website"},KNa={dN:"branding",LX:"card",R_:"drawer",X0:"highlight",H3:"marker",w6:"promotion",TEXT:"text",w9:"widget"};g.w(X3,g.H);g.k=X3.prototype;g.k.addCueRange=function(a,b,c,d,e){a=new g.hA(a,b,{id:c});a.namespace="annotations_module";d&&this.Qa.set(a,d);e&&this.Ta.set(a,e);this.context.I.Hd([a])};
g.k.Aw=function(){this.context.u.subscribe("resize",this.sx,this)};
g.k.iB=function(a,b,c,d,e,f){if(this.fb)return!1;f&&(f.stopPropagation(),f.preventDefault());this.navigate(a,c,d,e);return!1};
g.k.show=function(){};
g.k.hide=function(){};
g.k.destroy=function(){g.wg(this.element)};
g.k.sx=function(){};
g.k.navigate=function(a,b,c,d){var e=this,f=P3(a);if(f){var h=dNa(f,a.target),l=function(){a.i&&e.context.I.pauseVideo();var m=e.context.videoData.D||!1,n=g.vs(f||"");m&&n&&(n.v||n.list)?e.context.I.Lj(n.v,b,n.list,!1):g.NJ(f||"","current"===h?"_top":void 0,b)};
"new"===h&&(l(),l=null);m4(this.context.logger,c,l,d);cNa(f)||(c=g.fy(),d=b.itct,c&&d&&g.sz(c,g.$x(d)))}};
g.k.xa=function(){this.Qa.clear();this.Ta.clear();g.H.prototype.xa.call(this)};
g.k.createElement=function(a){a=new g.W(a);g.J(this,a);return a.element};g.w(b4,X3);g.k=b4.prototype;g.k.isAvailable=function(){var a;if(a=!!this.cards.length)(a=this.I.getRootNode())?(a=g.am(a),a=173<a.width&&173<a.height):a=!1;return a};
g.k.sx=function(){var a=this.isAvailable();g.bm(this.element,a);g.O(this.context.I.getRootNode(),g.ZT.IV_DRAWER_ENABLED,a);r3(this.I)};
g.k.destroy=function(){this.I.Js(!1);try{this.I.getRootNode().removeChild(this.C)}catch(a){}g.Uu(this.ea);g.lu(this.ya);this.Ka&&this.Ka.dispose();this.D&&this.D.dispose();X3.prototype.destroy.call(this)};
g.k.RP=function(){if(this.B){m4(this.context.logger,g4(this).tracking.close);var a=g.fy();a&&this.K&&g.sz(a,this.K);a4(this)}};
g.k.dQ=function(){g.O(this.C,"iv-drawer-scrolled",0<this.u.scrollTop)};
g.k.BR=function(){var a=g.fy(),b=g4(this);b=b?b.re:this.re;a&&b&&g.qz(a,[b])};
g.k.AR=function(){var a=g.fy(),b=g4(this);b=b?b.re:this.re;a&&b&&g.rz(a,[b])};
g.k.rO=function(){var a=g4(this);m4(this.context.logger,a.tracking.qM);var b=g.fy();b&&a&&g.qz(b,[a.Oi,a.re])};
g.k.DR=function(){var a=g.fy(),b=g4(this);a&&b&&g.rz(a,[b.Oi])};
g.k.qO=function(a){var b=g4(this),c=g.fy();this.i?a?(a=this.context.logger,m4(a,b.tracking.hA),a.I.sendVideoStatsEngageEvent(4,void 0),c&&b.Oi&&g.sz(c,b.Oi)):(a=this.context.logger,m4(a,b.tracking.hA),a.I.sendVideoStatsEngageEvent(4,void 0),c&&b.re&&g.sz(c,b.re)):(a=this.context.logger,m4(a,b.tracking.hA),a.I.sendVideoStatsEngageEvent(4,void 0),c&&this.re&&g.sz(c,this.re))};g.w(h4,X3);h4.prototype.Aw=function(){X3.prototype.Aw.call(this);rNa(this)};
h4.prototype.show=function(){X3.prototype.show.call(this);var a=g.fy(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.qz(a,[g.$x(b.itct)])};
h4.prototype.hide=function(){X3.prototype.hide.call(this);var a=g.fy(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.rz(a,[g.$x(b.itct)])};g.w(i4,h4);
i4.prototype.show=function(){if(!this.isActive){h4.prototype.show.call(this);if(!this.K){g.N(this.element,"iv-branding");var a=this.annotation.data;this.u=this.createElement({G:"img",Ga:["branding-img","iv-click-target"],W:{"aria-label":"Watermark channel",src:a.image_url,width:a.image_width,height:a.image_height}});g.bm(this.u,!1);var b=this.createElement({G:"div",Ga:["branding-img-container"]});b.appendChild(this.u);this.element.appendChild(b);(b=this.annotation.Qd())&&Y3(this,this.u,b,this.annotation.id,
a.session_data);vNa(this,a);this.K=!0}g.bm(this.element,!0);this.isActive=!0;this.u&&sNa(this,this.u)}};
i4.prototype.hide=function(){this.isActive&&(h4.prototype.hide.call(this),g.bm(this.element,!1),this.isActive=!1)};
i4.prototype.destroy=function(){this.i&&(this.i.dispose(),this.i=null);h4.prototype.destroy.call(this)};g.w(j4,h4);g.k=j4.prototype;g.k.show=function(){this.isActive||(h4.prototype.show.call(this),this.V||(xNa(this),this.V=!0),g.bm(this.element,!0),g.lh(function(){g.Lq(this.element,"iv-promo-inactive")},100,this),this.element.removeAttribute("aria-hidden"),this.isActive=!0,l4(this),yNa(this),zNa(this,this.J))};
g.k.hide=function(){this.isActive&&(g.N(this.element,"iv-promo-inactive"),this.isActive=!1,this.element.setAttribute("aria-hidden","true"))};
g.k.iB=function(a,b,c,d,e,f){return this.isCollapsed?!1:h4.prototype.iB.call(this,a,b,c,d,e,f)};
g.k.LQ=function(a){this.N=!0;k4(this,500,a)};
g.k.KQ=function(){this.N=!1;ANa(this)};
g.k.FQ=function(a){a.stopPropagation();this.hide()};
g.k.GQ=function(a){a.stopPropagation();l4(this);this.isCollapsed=!0;g.N(this.element,"iv-promo-collapsed-no-delay");this.D.start()};
g.k.destroy=function(){this.D.dispose();h4.prototype.destroy.call(this)};g.w(n4,g.kN);g.k=n4.prototype;g.k.Ze=function(a,b){if(!ONa(this.player.U().playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":return(a=g.U1(b))&&o4(this,a),!0;case "removeCustomAnnotationById":return b&&this.i&&(iNa(this.i,b),r3(this.player)),!0}return null};
g.k.getOptions=function(){return ONa(this.player.U().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.k.oq=function(){var a=this.player.U(),b=this.player.getVideoData();return b.D&&a.pfpChazalUi?!1:1===(a.annotationsLoadPolicy||b.annotationsLoadPolicy)&&!b.ZH||a.V.get(b.videoId)||g.sH(b)||g.tH(b)?!0:!1};
g.k.oz=function(){if(this.C){var a=this.player.eb().getVideoContentRect(!0);g.$l(this.C.element,a.width,a.height);g.Tl(this.C.element,a.left,a.top)}if(this.i){var b=this.player.ej();a=this.i;b=b.width;g.O(a.C,"iv-drawer-small",426>=b);g.O(a.C,"iv-drawer-big",1280<=b)}};
g.k.sO=function(a){DNa(this,a.state);g.V(a.state,2)&&(this.yh()&&this.jk()&&2!==this.player.getPresentingPlayerType()&&this.setCardsVisible(!1),this.Js(!1))};
g.k.load=function(){function a(h){var l=b.loadNumber;b.J=null;b.loaded&&b.loadNumber===l&&b.player.getVideoData().videoId===d&&(h=g.dt(h)&&h.responseXML?h.responseXML:null)&&(o4(b,h),g.N(b.player.getRootNode(),"iv-module-loaded"))}
var b=this;g.kN.prototype.load.call(this);DNa(this,this.player.vb());this.loadNumber++;var c=this.player.getVideoData(),d=c.videoId;g.Du()&&(a=GNa(this,a));var e={format:"XML",onFinish:a,onError:function(){b.J=null},
urlParams:{}};c.isPharma&&(e.urlParams.pharma="1");e.method="POST";e.withCredentials=!0;var f=this.player.U().V.get(d);f&&HNa(e,f);f=f&&(f.xx||f.tu);if(!c.rl||f)c.Ka?ENa(this,c.Ka,e):(this.B=function(){b.qb(e)},this.player.addEventListener("videodatachange",this.B));
g.YM(this.player,this.C.element,4);this.oz();(f=g.sH(c))&&MNa(this,f);(f=g.tH(c))&&f.featuredChannel&&NNa(this,f.featuredChannel,f.annotationId||"branding",c.videoId||null,c.eventId||null)};
g.k.qb=function(a){var b=this.player.getVideoData();b.Ka&&(this.B&&(this.player.removeEventListener("videodatachange",this.B),this.B=null),ENa(this,b.Ka,a))};
g.k.unload=function(){this.player.We("annotations_module");for(var a=g.r(Object.keys(this.K)),b=a.next();!b.done;b=a.next())this.K[b.value].destroy();this.N=null;this.i&&(this.i.destroy(),this.i=null,r3(this.player));this.V=!1;this.J&&(this.J.abort(),this.J=null);this.K={};this.u.hide();g.kN.prototype.unload.call(this);this.C.detach();this.B&&(this.player.removeEventListener("videodatachange",this.B),this.B=null)};
g.k.rL=function(a){a===this.player.getVideoData().videoId&&(this.loaded?INa(this):this.load())};
g.k.yh=function(){return!!this.i&&this.i.isAvailable()};
g.k.jk=function(){this.yh();return!!this.i&&this.i.B};
g.k.setCardsVisible=function(a,b,c){b=void 0===b?!1:b;this.yh();this.i&&(a?c?$3(this.i,c,b):$3(this.i,"YOUTUBE_DRAWER_AUTO_OPEN",b):a4(this.i))};
g.k.Js=function(a,b){this.player.Z(a?"cardsteasershow":"cardsteaserhide",b)};
g.k.xa=function(){this.player.U().V.unsubscribe("vast_info_card_add",this.rL,this);g.Lq(this.player.getRootNode(),g.ZT.IV_DRAWER_OPEN);for(var a=this.ea,b=0,c=a.length;b<c;b++)g.Eu(a[b]);this.ea.length=0;g.kN.prototype.xa.call(this)};
g.k.createElement=function(a){a=new g.W(a);g.J(this,a);return a.element};g.vN.annotations_module=n4;g.vN.creatorendscreen=D3;})(_yt_player);
