(function(g){var window=this;'use strict';var t4=function(a,b){return b?a.captionsInitialState:"CAPTIONS_INITIAL_STATE_UNKNOWN"},u4=function(a){return g.LF(a)&&a.Y("web_player_i_see_captions_3")},SNa=function(a,b){return g.E(this,function d(){var e,f,h;
return g.A(d,function(l){if(1==l.i)return e=a+"|"+b,g.z(l,g.Vw(),2);if(3!=l.i){f=l.u;if(!f)throw g.iw("gct");return g.z(l,(0,g.gG)(),3)}h=l.u;return l.return(h.get("captions",e))})})},TNa=function(a,b){var c=new g.jG;
c.languageCode=a.languageCode;c.languageName=a.languageName;c.name=a.name;c.kind=a.kind;c.isDefault=!1;c.i=a.i;c.isTranslateable=a.isTranslateable;c.vssId=a.vssId;c.url=a.url;c.translationLanguage=b;return c},UNa=function(a,b,c){SNa(a,b).then(function(d){d&&c(d.trackData,new g.jG(d.metadata))})},v4=function(){this.segments=[]},VNa=function(a,b){var c=g.xb(a.segments,b);
0<=c||0>c&&1===(-c-1)%2||(c=-c-1,0<c&&1===b-a.segments[c-1]&&c<a.segments.length&&1===a.segments[c]-b?(g.nb(a.segments,c),g.nb(a.segments,c-1)):0<c&&1===b-a.segments[c-1]?a.segments[c-1]=b:c<a.segments.length&&1===a.segments[c]-b?a.segments[c]=b:(g.ub(a.segments,c,0,b),g.ub(a.segments,c+1,0,b)))},w4=function(a,b,c,d,e,f){g.H.call(this);
this.policy=a;this.player=b;this.V=c;this.K=d;this.D=e;this.N=f;this.X=this.player.U();this.C=new v4;this.u=this.B=this.i=null;this.J=new g.K(this.bK,1E3,this);this.events=new g.aN(this);g.J(this,this.J);g.J(this,this.events);this.events.S(b,"SEEK_COMPLETE",this.pG);this.pG();this.bK()},WNa=function(a){return a.i&&a.i.D?a.i.D+a.player.Rc()<a.player.getCurrentTime():!1},XNa=function(a,b){var c=g.bD(b,a.policy,{}).Qd(),d={format:"RAW",
withCredentials:!0};a.D&&(d.responseType="arraybuffer");a.u=g.ch(g.qt(c,d,3,100).then(function(e){a:{e=e.xhr;a.isDisposed();if(a.B){var f=!(a.D?e.response:e.responseText)||400<=e.status,h=g.Rka(e);if(h){e=g.bD(a.B,a.policy,{});a.B.hj(e,h);XNa(a,a.B);break a}f||null==a.K||(h=a.B.i[0],a.D?a.K(e.response,1E3*(h.startTime+a.player.Rc())):a.K(e.responseText,1E3*(h.startTime+a.player.Rc())))}a.B=null;a.u=null}}),function(){a.B=null;
a.u=null;a.oa()});
a.B=b;VNa(a.C,a.B.i[0].Na)},x4=function(a,b){g.nN.call(this,b.U());
this.i=a;this.I=b;this.B=null;this.D=!1;this.J=g.NF(this.I.U())&&!this.i.isManifestless},ZNa=function(a,b){var c=[],d;
for(d in a.i.i)if(a.i.i.hasOwnProperty(d)){var e=a.i.i[d];if(g.pN(e,b||null)){var f=e.info.id,h=f,l="."+f,m="";if(e=e.info.captionTrack)f=e.languageCode,h=e.displayName,l=e.vssId,m=e.kind;else{e=f;var n=g.eMa.get(e);null==n&&(n=YNa[e]||YNa[e.replace(/-/g,"_")],g.eMa.set(e,n));h=n||h}c.push(new g.jG({id:d,languageCode:f,languageName:h,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:l,kind:m}))}}return c},$Na=function(a,b){return null!=b&&b in a.i.i?a.i.i[b]:null},aOa=function(a,b,c){var d=
[],e;
for(e in a.i.i)if(a.i.i.hasOwnProperty(e)){var f=a.i.i[e];if(g.pN(f,c||null)){var h=f.info.captionTrack;h&&h.languageCode===b&&d.push(f)}}return d.length?d[0]:null},y4=function(a){if(!bOa.test(a))throw Error("'"+a+"' is not a valid hex color");
4==a.length&&(a=a.replace(cOa,"#$1$1$2$2$3$3"));a=a.toLowerCase();a=parseInt(a.substr(1),16);return[a>>16,a>>8&255,a&255]},z4=function(a,b,c,d,e,f){var h={};
Object.assign(h,b);Object.assign(h,a.params);Object.assign(h,c);var l={};Object.assign(l,b.jd);a.params.jd&&Object.assign(l,a.params.jd);Object.assign(l,c.jd);h.jd=l;g.W.call(this,{G:"div",L:"caption-window",W:{id:"caption-window-"+a.id,dir:1===h.Ff?"rtl":"ltr",tabindex:"0",lang:h.lang},T:[{G:"span",L:"captions-text",W:{style:"word-wrap: normal; display: block;"}}]});this.D=[];this.ya=!1;this.u=a;this.Ca=this.Aa=null;this.playerWidth=e;this.playerHeight=f;this.J=null;this.maxWidth=.96*e;this.Ta=.96*
f;this.i=h;this.wb=c;this.Ha=b;this.C=this.Fa("captions-text");this.ob=""!==this.C.style.getPropertyValue("box-decoration-break")||""!==this.C.style.getPropertyValue("-webkit-box-decoration-break");this.La=d/360*16;this.type=0;this.Xa=this.La*dOa(l);a=new g.Px(this.element,!0);g.J(this,a);a.subscribe("dragstart",this.vO,this);a.subscribe("dragmove",this.uO,this);a.subscribe("dragend",this.tO,this);this.fb=this.bb=0;b="";this.i.windowOpacity&&(a=y4(this.i.windowColor),b="rgba("+a[0]+","+a[1]+","+a[2]+
","+this.i.windowOpacity+")");a={"background-color":b,display:!1===this.i.isVisible?"none":"","text-align":eOa[this.i.textAlign]};this.ob&&(a["border-radius"]=b?this.Xa/8+"px":"");if(this.B=2===this.u.params.Ff||3===this.u.params.Ff)b=this.element,c="vertical-rl",1===this.i.kF&&(c="vertical-lr"),g.ke&&(c="vertical-lr"===c?"tb-lr":"tb-rl"),g.Ml(b,"-o-writing-mode",c),g.Ml(b,"-webkit-writing-mode",c),g.Ml(b,"writing-mode",c),g.Ml(b,"text-orientation","upright"),g.N(b,"ytp-vertical-caption"),3===this.u.params.Ff&&
(g.Ml(b,"text-orientation",""),g.Ml(b,"transform","rotate(180deg)"));g.Ml(this.element,a);switch(this.i.di){case 0:case 1:case 2:g.N(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.N(this.element,"ytp-caption-window-bottom")}},dOa=function(a){var b=1+.25*(a.fontSizeIncrement||0);
if(0===a.offset||2===a.offset)b*=.8;return b},fOa=function(a,b){var c={},d=b.background?b.background:a.i.jd.background;
if(null!=b.backgroundOpacity||b.background){var e=null!=b.backgroundOpacity?b.backgroundOpacity:a.i.jd.backgroundOpacity;d=y4(d);c.background="rgba("+d[0]+","+d[1]+","+d[2]+","+e+")";a.ob&&(c["box-decoration-break"]="clone",c["border-radius"]=a.Xa/8+"px")}if(null!=b.fontSizeIncrement||null!=b.offset)c["font-size"]=a.La*dOa(b)+"px";d=1;e=b.color||a.i.jd.color;if(b.color||null!=b.textOpacity)e=y4(e),d=null==b.textOpacity?a.i.jd.textOpacity:b.textOpacity,e="rgba("+e[0]+","+e[1]+","+e[2]+","+d+")",c.color=
e,c.fill=e;var f=b.charEdgeStyle;0===f&&(f=void 0);if(f){e="rgba(34, 34, 34, "+d+")";var h="rgba(204, 204, 204, "+d+")";b.bC&&(h=e=b.bC);var l=a.La/16/2,m=Math.max(l,1),n=Math.max(2*l,1),p=Math.max(3*l,1),q=Math.max(5*l,1);d=[];switch(f){case 4:for(;p<=q;p+=l)d.push(n+"px "+n+"px "+p+"px "+e);break;case 1:n=2<=window.devicePixelRatio?.5:1;for(f=m;f<=p;f+=n)d.push(f+"px "+f+"px "+e);break;case 2:d.push(m+"px "+m+"px "+h);d.push("-"+m+"px -"+m+"px "+e);break;case 3:for(p=0;5>p;p++)d.push("0 0 "+n+"px "+
e)}c["text-shadow"]=d.join(", ")}e="";switch(b.fontFamily){case 1:e='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:e='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:e='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:e='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:e='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:e=g.Ht()?'"Carrois Gothic SC", sans-serif-smallcaps':
'"Arial Unicode Ms", Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:e='"YouTube Noto", Roboto, "Arial Unicode Ms", Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}e&&(c["font-family"]=e);e=b.offset;null==e&&(e=a.i.jd.offset);switch(e){case 0:c["vertical-align"]="sub";break;case 2:c["vertical-align"]="super"}7===b.fontFamily&&(c["font-variant"]="small-caps");b.bold&&(c["font-weight"]="bold");b.lj&&(c["font-style"]="italic");b.underline&&(c["text-decoration"]="underline");
b.gR&&(c.visibility="hidden");1===b.sJ&&a.B&&(c["text-combine-upright"]="all",c["text-orientation"]="mixed",e=g.RF||g.fj,3===a.u.params.Ff?c.transform=e?"rotate(90deg)":"rotate(180deg)":e&&(c.transform="rotate(-90deg)"));if(1===b.Ej||2===b.Ej||3===b.Ej||4===b.Ej||5===b.Ej)if(g.RF)c["font-weight"]="bold";else switch(c["text-emphasis-style"]="filled circle",c["text-emphasis-color"]="currentcolor",c["webkit-text-emphasis"]="filled circle",b.Ej){case 4:case 3:c["text-emphasis-position"]="under left";
c["webkit-text-emphasis-position"]="under left";break;case 5:case 2:c["text-emphasis-position"]="over right",c["webkit-text-emphasis-position"]="over right"}return c},gOa=function(a){a.J=g.sg("SPAN");
g.Ml(a.J,{display:"block"});g.N(a.J,"caption-visual-line");a.C.appendChild(a.J)},hOa=function(a,b){var c=g.sg("SPAN");
g.Ml(c,{display:"inline-block","white-space":"pre-wrap"});g.Ml(c,fOa(a,b));c.classList.add("ytp-caption-segment");a.J.appendChild(c);c.previousElementSibling&&(g.Ml(c.previousElementSibling,{"border-top-right-radius":"0","border-bottom-right-radius":"0"}),g.Ml(c,{"border-top-left-radius":"0","border-bottom-left-radius":"0"}));return c},iOa=function(a,b,c){a.ya=a.ya||!!c;
var d={};Object.assign(d,a.i.jd);Object.assign(d,c||b.i);Object.assign(d,a.wb.jd);(c=!a.J)&&gOa(a);for(var e=a.Aa&&a.Ca&&g.Zb(d,a.Ca)?a.Aa:hOa(a,d),f="string"===typeof b.text,h=f?b.text.split("\n"):[b.text],l=0;l<h.length;l++){var m=0<l||!b.append,n=h[l];m&&!c?(gOa(a),e=hOa(a,d)):m&&c&&(c=!1);n&&(e.appendChild(f?g.tg(n):n),f||"RUBY"!==n.tagName||4!==n.childElementCount||g.RF||!g.Pl(n.children[2],"text-emphasis")||(m=a.B?"padding-right":"padding-top",g.Pl(n.children[2],"text-emphasis-position")&&(m=
a.B?"padding-left":"padding-bottom"),g.ng?g.Ml(e,m,"1em"):g.Ml(e,m,"0.5em")))}a.Ca=d;a.Aa=e;a.D.push(b)},A4=function(a,b,c){g.nN.call(this,a);
this.videoData=b;this.audioTrack=c;this.C=b.BB},B4=function(a,b,c,d,e,f,h){z4.call(this,a,b,c,d,e,f,h);
this.type=1},C4=function(a,b,c,d,e,f,h){z4.call(this,a,b,c,d,e,f,h);
this.type=2;this.K=[];this.V=this.N=this.Ka=0;this.ma=NaN;this.gb=0;this.tb=null;this.Qa=new g.K(this.sU,433,this);g.N(this.element,"ytp-caption-window-rollup");g.J(this,this.Qa);g.Ml(this.element,"overflow","hidden")},jOa=function(a,b){if(!b)return"";
a.B&&1!==a.u.params.kF&&(b*=-1);return"translate"+(a.B?"X":"Y")+"("+b+"px)"},kOa=function(a){a.K=Array.from(document.getElementsByClassName("caption-visual-line"));
for(var b=a.u.params.lm,c=0,d=0,e=a.K.length-1;c<b&&-1<e;){var f=a.K[e];d+=a.B?f.offsetWidth:f.offsetHeight;c++;e--}a.K.length<b&&(d*=b/a.K.length);a.N=d;b=Math;c=b.max;isNaN(a.ma)&&((d=a.i.Mm)?(e=g.sg("SPAN"),g.zg(e,"\u2013".repeat(d)),g.Ml(e,fOa(a,a.i.jd)),a.C.appendChild(e),a.ma=e.offsetWidth,a.C.removeChild(e)):a.ma=0);d=a.C;a.V=c.call(b,a.ma,a.gb,(a.B?d.offsetHeight:d.offsetWidth)+1)},lOa=function(a,b){kOa(a);
var c=a.K.reduce(function(e,f){return(a.B?f.offsetWidth:f.offsetHeight)+e},0);
c=a.N-c;if(c!==a.Ka){var d=0<c&&0===a.Ka;b||isNaN(c)||d||(g.N(a.element,"ytp-rollup-mode"),g.Dq(a.Qa));g.Ml(a.C,"transform",jOa(a,c));a.Ka=c}kOa(a)},D4=function(a,b,c,d,e,f,h){f=void 0===f?!1:f;
h=void 0===h?null:h;g.hA.call(this,a,a+b,{priority:c,namespace:"captions"});this.windowId=d;this.text=e;this.append=f;this.i=h},E4=function(a,b,c,d,e){g.hA.call(this,a,a+b,{priority:c,
namespace:"captions"});this.id=d;this.params=e;this.i=[]},mOa=function(a){var b="_"+F4++;
return new E4(0,0x8000000000000,0,b,a)},oOa=function(a,b,c,d,e,f,h){var l=f[0],m=h[l.getAttribute("p")];
if(1===m.Wd){var n=f[1],p=f[2];f=f[3];l.getAttribute("t");n.getAttribute("t");p.getAttribute("t");f.getAttribute("t");l.getAttribute("p");n.getAttribute("p");f.getAttribute("p");h=h[p.getAttribute("p")];l=nOa(l.textContent,n.textContent,p.textContent,f.textContent,h);return new D4(a,b,e,c,l,d,m)}switch(m.Wd){case 9:case 10:m.Ej=1;break;case 11:m.Ej=2;break;case 12:m.Ej=3;break;case 13:m.Ej=4;break;case 14:m.Ej=5}return new D4(a,b,e,c,l.textContent||"",d,m)},nOa=function(a,b,c,d,e){var f=g.Ht(),h=
f?g.sg("DIV"):g.sg("RUBY"),l=g.sg("SPAN");
l.textContent=a;h.appendChild(l);a=f?g.sg("DIV"):g.sg("RP");a.textContent=b;h.appendChild(a);b=f?g.sg("DIV"):g.sg("RT");b.textContent=c;h.appendChild(b);c=e.Wd;if(10===c||11===c||12===c||13===c||14===c)if(g.Ml(b,"text-emphasis-style","filled circle"),g.Ml(b,"text-emphasis-color","currentcolor"),g.Ml(b,"webkit-text-emphasis","filled circle"),11===e.Wd||13===e.Wd)g.Ml(b,"webkit-text-emphasis-position","under left"),g.Ml(b,"text-emphasis-position","under left");c=!0;if(4===e.Wd||7===e.Wd||12===e.Wd||
14===e.Wd)g.Ml(h,"ruby-position","over"),g.Ml(h,"-webkit-ruby-position","before");else if(5===e.Wd||6===e.Wd||11===e.Wd||13===e.Wd)g.Ml(h,"ruby-position","under"),g.Ml(h,"-webkit-ruby-position","after"),c=!1;e=f?g.sg("DIV"):g.sg("RP");e.textContent=d;h.appendChild(e);f&&(d=c,g.Ml(h,{display:"inline-block",position:"relative"}),f=h.firstElementChild.nextElementSibling,g.Ml(f,"display","none"),f=f.nextElementSibling,g.Ml(f,{"font-size":"0.5em","line-height":"1.2em","text-align":"center",position:"absolute",
left:"50%",transform:"translateX(-50%)",width:"400%"}),g.Ml(h.lastElementChild,"display","none"),d?(g.Ml(h,"padding-top","0.6em"),g.Ml(f,"top","0")):(g.Ml(h,"padding-bottom","0.6em"),g.Ml(f,"bottom","0")));return h},G4=function(){g.H.apply(this,arguments)},H4=function(a){G4.call(this);
this.D=a;this.C={};this.V={};this.ea={};this.J="_"+F4++;this.N={};this.B=this.i=null;this.K=!0},I4=function(a,b){a=a.getAttribute(b);
if(null!=a)return Number(a)},J4=function(a,b){a=a.getAttribute(b);
if(null!=a)return"1"===a},K4=function(a,b){a=I4(a,b);
return void 0!==a?a:null},M4=function(a,b){a=a.getAttribute(b);
if(null!=a)return L4.test(a),a},pOa=function(a,b){var c={},d=b.getAttribute("ws");
Object.assign(c,d?a.ea[d]:a.D);a=K4(b,"mh");null!=a&&(c.qs=a);a=K4(b,"ju");null!=a&&(c.textAlign=a);a=K4(b,"pd");null!=a&&(c.Ff=a);a=K4(b,"sd");null!=a&&(c.kF=a);a=M4(b,"wfc");null!=a&&(c.windowColor=a);b=I4(b,"wfo");void 0!==b&&(c.windowOpacity=b/255);return c},qOa=function(a,b){var c={},d=b.getAttribute("wp");
d&&Object.assign(c,a.V[d]);a=K4(b,"ap");null!=a&&(c.di=a);a=I4(b,"cc");null!=a&&(c.Mm=a);a=I4(b,"ah");null!=a&&(c.eh=a);a=I4(b,"rc");null!=a&&(c.lm=a);b=I4(b,"av");null!=b&&(c.Fj=b);return c},rOa=function(a,b,c,d){var e={};
Object.assign(e,qOa(a,b));Object.assign(e,pOa(a,b));d?g.Zb(e,a.D)?(d=a.J,e=a.D):d="_"+F4++:d=b.getAttribute("id")||"_"+F4++;a=I4(b,"t")+c;b=I4(b,"d")||0x8000000000000;if(2===e.Ff||3===e.Ff)c=e.lm,e.lm=e.Mm,e.Mm=c;return new E4(a,b,0,d,e)},N4=function(a){G4.call(this);
this.J=a;this.i=new Map;this.C=new Map;this.D=new Map;this.B=new Map},O4=function(a){a=g.Rf(Math.round(a),0,16777215).toString(16).toUpperCase();
return"#000000".substr(0,7-a.length)+a},sOa=function(a,b,c,d,e){0===d&&(d=0x8000000000000);
var f={};b.wpWinPosId&&Object.assign(f,a.C.get(b.wpWinPosId));b.wsWinStyleId&&Object.assign(f,a.D.get(b.wsWinStyleId));a=b.rcRowCount;void 0!==a&&(f.lm=a);b=b.ccColCount;void 0!==b&&(f.Mm=b);if(2===f.Ff||3===f.Ff)b=f.lm,f.lm=f.Mm,f.Mm=b;return new E4(c,d,0,e,f)},Q4=function(){this.B=this.time=this.mode=this.u=0;
this.C=new P4(this);this.D=new P4(this);this.i=[];this.clear()},uOa=function(a,b,c){if(255===a&&255===b||!a&&!b)return{Vo:a,
Hm:b,result:0};a=tOa[a];b=tOa[b];if(a&128){var d;if(d=!(b&128))d=b,d=c.isValid()&&c.Hm===d;if(d)return{Vo:a,Hm:b,result:1}}else if(b&128&&1<=a&&31>=a)return{Vo:a,Hm:b,result:2};return{Vo:a,Hm:b,result:3}},wOa=function(a,b,c,d){255===b&&255===c||!b&&!c?(45===++a.B&&a.reset(),a.C.u.clear(),a.D.u.clear()):(a.B=0,vOa(a.C,b,c,d))},xOa=function(a,b){a.i.sort(function(e,f){var h=e.time-f.time;
return 0===h?e.order-f.order:h});
for(var c=g.r(a.i),d=c.next();!d.done;d=c.next())d=d.value,a.time=d.time,0===d.type?wOa(a,d.VH,d.WH,b):1===d.type&&a.u&496&&vOa(a.D,d.VH,d.WH,b);a.i.length=0},R4=function(){this.type=0},S4=function(){this.state=this.Hm=this.Vo=0},yOa=function(){this.timestamp=this.i=0},T4=function(a){this.D=a;
this.B=[];this.i=this.u=this.row=0;this.style=new R4;for(a=this.C=0;15>=a;a++){this.B[a]=[];for(var b=0;32>=b;b++)this.B[a][b]=new yOa}},U4=function(a,b){if(3===a.style.type){for(var c=0,d=0,e=a.D.time+0,f="",h="",l=e,m=1;15>=m;++m){for(var n=!1,p=d?d:1;32>=p;++p){var q=a.B[m][p];
if(0!==q.i){0===c&&(c=m,d=p);n=String.fromCharCode(q.i);var t=q.timestamp;t<e&&(e=t);q.timestamp=l;h&&(f+=h,h="");f+=n;n=!0}if((0===q.i||32===p)&&n){h="\n";break}else if(d&&!n)break}if(c&&!n)break}f&&b.C(c,d,e,l,f)}else for(d=c=0,f=e=a.D.time+0,h=1;15>=h;++h)for(l="",m=1;32>=m;++m)if(p=a.B[h][m],q=p.i,0!==q&&(0===c&&(c=h,d=m),n=String.fromCharCode(q),t=p.timestamp,t<=e&&(e=t),l+=n,p.reset()),32===m||0===q)l&&b.C(c,d,e,f,l),e=f,l="",d=c=0},DOa=function(a,b){switch(a){case 0:return zOa[(b&127)-32];
case 1:return AOa[b&15];case 2:return BOa[b&31];case 3:return COa[b&31]}return 0},V4=function(a){return a.B[a.row][a.u]},W4=function(a,b,c){2<=b&&1<a.u&&(--a.u,V4(a).i=0);
var d=V4(a);d.timestamp=a.D.time+0;d.i=DOa(b,c);32>a.u&&a.u++},EOa=function(a,b,c,d){for(var e=0;e<d;e++)for(var f=0;32>=f;f++){var h=a.B[b+e][f],l=a.B[c+e][f];
h.i=l.i;h.timestamp=l.timestamp}},X4=function(a,b,c){for(var d=0;d<c;d++)for(var e=0;32>=e;e++)a.B[b+d][e].reset()},Y4=function(a){a.row=0<a.i?a.i:1;
a.u=1;X4(a,0,15)},Z4=function(a){this.B=a;
this.D=0;this.style=new R4;this.J=new T4(this.B);this.K=new T4(this.B);this.text=new T4(this.B);this.u=this.J;this.C=this.K;this.i=this.u},$4=function(a,b,c){var d=a.u,e=!1;
switch(a.style.get()){case 4:case 1:case 2:4===a.style.get()&&0<d.i||(U4(d,c),Y4(a.u),Y4(a.C),d.row=15,d.i=b,e=!0)}a.style.set(3);a.i=d;a.i.style=a.style;a.B.mode=1<<d.C;e?d.u=1:d.i!==b&&(d.i>b?(U4(d,c),X4(d,d.row-d.i,b)):d.row<b&&(b=d.i),d.i=b)},FOa=function(a){a.style.set(1);
a.i=a.C;a.i.i=0;a.i.style=a.style;a.B.mode=1<<a.i.C},GOa=function(a){a.style.set(4);
a.i=a.text;a.i.style=a.style;a.B.mode=1<<a.i.C},P4=function(a){this.i=a;
this.D=0;this.B=new Z4(this.i);this.J=new Z4(this.i);this.u=new S4;this.C=this.B},vOa=function(a,b,c,d){a.u.update();
b=uOa(b,c,a.u);switch(b.result){case 0:return;case 1:case 2:return}var e=b.Vo;c=b.Hm;if(32<=e||!e)a.i.mode&a.i.u&&(b=e,b&128&&(b=127),c&128&&(c=127),a=a.C.i,b&96&&W4(a,0,b),c&96&&W4(a,0,c),0!==b&&0!==c&&3===a.style.type&&U4(a,d));else if(e&16)a:if(!a.u.matches(e,c)&&(b=a.u,b.Vo=e,b.Hm=c,b.state=2,b=e&8?a.J:a.B,a.C=b,a.i.mode=1<<(a.D<<2)+(b.D<<1)+(4===b.style.type?1:0),(a.i.mode|1<<(a.D<<2)+(b.D<<1)+(4!==b.style.type?1:0))&a.i.u))if(c&64){d=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(e&7)<<1|c>>5&1];
a=c&16?4*((c&14)>>1):0;c=b.i;switch(b.style.get()){case 4:d=c.row;break;case 3:if(d!==c.row){if(d<c.i&&(d=c.i,d===c.row))break;var f=1+c.row-c.i,h=1+d-c.i;EOa(c,h,f,c.i);b=f;e=c.i;h<f?(f=h+e-f,0<f&&(b+=f,e-=f)):(f=f+e-h,0<f&&(e-=f));X4(c,b,e)}}c.row=d;c.u=a+1}else switch(e&7){case 1:switch(c&112){case 32:W4(b.i,0,32);break a;case 48:57===c?(d=b.i,V4(d).i=0,32>d.u&&d.u++):W4(b.i,1,c&15)}break;case 2:c&32&&W4(b.i,2,c&31);break;case 3:c&32&&W4(b.i,3,c&31);break;case 4:case 5:if(32<=c&&47>=c)switch(c){case 32:FOa(b);
break;case 33:d=b.i;1<d.u&&(--d.u,V4(d).i=0);break;case 36:d=b.i;b=V4(d);for(a=0;15>=a;a++)for(c=0;32>=c;c++)if(d.B[a][c]===b){for(;32>=c;c++)d.B[a][c].reset();break}break;case 37:$4(b,2,d);break;case 38:$4(b,3,d);break;case 39:$4(b,4,d);break;case 40:W4(b.i,0,32);break;case 41:b.style.set(2);b.i=b.u;b.i.i=0;b.i.style=b.style;b.B.mode=1<<b.i.C;break;case 42:d=b.text;d.i=15;d.style.set(4);Y4(d);GOa(b);break;case 43:GOa(b);break;case 44:a=b.u;switch(b.style.get()){case 1:case 2:case 3:U4(a,d)}X4(a,
0,15);break;case 45:b:{a=b.i;switch(b.style.get()){default:case 2:case 1:break b;case 4:if(15>a.row){++a.row;a.u=1;break b}case 3:}2>a.i&&(a.i=2,a.row<a.i&&(a.row=a.i));b=a.row-a.i+1;U4(a,d);EOa(a,b,b+1,a.i-1);X4(a,a.row,1)}break;case 46:X4(b.C,0,15);break;case 47:U4(b.u,d),b.C.updateTime(b.B.time+0),d=b.C,b.C=b.u,b.u=d,FOa(b)}break;case 7:switch(c){case 33:case 34:case 35:d=b.i,32<(d.u+=c&3)&&(d.u=32)}}},HOa=function(){},a5=function(a,b,c){this.trackData=a;
this.J=c;this.version=this.D=this.B=this.byteOffset=0;this.i=new DataView(this.trackData);this.u=[]},b5=function(a){var b=a.byteOffset;
a.byteOffset+=1;return a.i.getUint8(b)},c5=function(a){var b=a.byteOffset;
a.byteOffset+=4;return a.i.getUint32(b)},d5=function(a,b){G4.call(this);
this.B=a;this.C=b;this.track="CC3"===this.C.languageName?4:0;this.i=new Q4;this.i.u=1<<this.track},e5=function(a){if("string"===typeof a)return!1;
a=new a5(a,8,0);return IOa(a)},IOa=function(a){if(!(a.byteOffset<a.i.byteLength)||1380139777!==c5(a))return!1;
a.version=b5(a);if(1<a.version)return!1;b5(a);b5(a);b5(a);return!0},f5=function(){G4.call(this)},JOa=function(a,b,c,d,e,f,h,l,m){switch(h.tagName){case "b":l.bold=!0;
break;case "i":l.lj=!0;break;case "u":l.underline=!0}for(var n=0;n<h.childNodes.length;n++){var p=h.childNodes[n];if(3===p.nodeType)p=new D4(b,c,d,e.id,p.nodeValue,f||0<n,g.Wb(l)?void 0:l),m.push(p),e.i.push(p);else{var q={};Object.assign(q,l);JOa(a,b,c,d,e,!0,p,q,m)}}},g5=function(a){var b=a.split(":");
a=0;b=g.r(b);for(var c=b.next();!c.done;c=b.next())a=60*a+Number(c.value);return 1E3*a},KOa=function(a,b,c,d){d=Object.assign({qs:0},d);
return new E4(a,b,c,"_"+F4++,d)},h5=function(a){g.H.call(this);
this.X=a;this.i=null},QOa=function(a,b,c,d,e){d=d||0;
e=e||0;if(a.X.Y("enable_h5_ssdai_caption")&&b){var f=e,h=LOa(b,d),l=[];try{for(var m=g.r(h),n=m.next();!n.done;n=m.next()){var p=n.value,q=p.trackData,t=p.bF;l="string"!==typeof q?l.concat(MOa(a,c,q,t,f)):"WEBVTT"===q.substring(0,6)?l.concat(NOa(a,q,t)):l.concat(OOa(a,c,q,t))}var u=l}catch(x){g.qy(x),a.clear(),u=[]}if(0!==u.length)return u}a.X.Y("html5_disable_rawcc_killswitch")?"string"!==typeof b&&(u=new DataView(b),8<=u.byteLength&&1718909296===u.getUint32(4)&&(u=g.hC(u,0,1835295092),b=a.X.Y("html5_fix_mdat_offset_killswitch")?
b.slice(u.dataOffset,u.dataOffset+u.size):b.slice(u.dataOffset,u.offset+u.size),e5(b)||(b=g.Za(new Uint8Array(b))))):b=POa(a,b);if(!b)return[];try{return"string"!==typeof b?MOa(a,c,b,d,e):"WEBVTT"===b.substring(0,6)?NOa(a,b,d):OOa(a,c,b,d)}catch(x){return g.qy(x),a.clear(),[]}},POa=function(a,b){if("string"===typeof b||e5(b))return b;
var c=new DataView(b);if(8>=c.byteLength||1718909296!==c.getUint32(4))return"";c=g.hC(c,0,1835295092);if(!c||!c.size)return"";a=a.X.Y("html5_fix_mdat_offset_killswitch")?b.slice(c.dataOffset,c.dataOffset+c.size):b.slice(c.dataOffset,c.offset+c.size);return g.Za(new Uint8Array(a))},LOa=function(a,b){if("string"===typeof a||e5(a))return[{trackData:a,
bF:b}];var c=new DataView(a);if(8>=c.byteLength||1718909296!==c.getUint32(4))return[];var d=g.qC(c,1835295092);if(!d||!d.length||!d[0].size)return[];var e=[];d=g.r(d.entries());for(var f=d.next();!f.done;f=d.next()){var h=g.r(f.value);f=h.next().value;h=h.next().value;h=g.Za(new Uint8Array(a.slice(h.dataOffset,h.offset+h.size)));e.push({trackData:h,bF:b+1E3*f})}ROa(c,e,b);return e=e.filter(function(l){return!!l.trackData})},ROa=function(a,b,c){var d=g.hC(a,0,1836476516),e=9E4;
d&&(e=g.iC(d)||9E4);d=0;var f=g.qC(a,1836019558);f=g.r(f.entries());for(var h=f.next();!h.done;h=f.next()){var l=g.r(h.value);h=l.next().value;l=l.next().value;h<b.length&&(l=g.hC(a,l.dataOffset,1953653094))&&(l=g.hC(a,l.dataOffset,1952867444))&&(l=g.oC(l)/e*1E3,0===h&&(d=l),b[h].bF=l-d+c||c*h*1E3)}},MOa=function(a,b,c,d,e){if(!e5(c))throw Error("Invalid binary caption track data");
a.i||(a.i=new d5(e,b));return a.i.u(c,d)},NOa=function(a,b,c){a.i||(a.i=new f5);
a=a.i.u(b,c);.01>Math.random()&&g.cz(Error("Deprecated subtitles format in web player: WebVTT"));return a},OOa=function(a,b,c,d){if("{"===c[0])try{return a.i||(a.i=new N4(SOa(b))),a.i.u(c,d)}catch(f){return g.qy(f),[]}var e=g.U1(c);
if(!e||!e.firstChild)throw a=Error("Invalid caption track data"),a.params=c,a;if("timedtext"===e.firstChild.tagName){if(3===Number(e.firstChild.getAttribute("format")))return a.i||(a.i=new H4(SOa(b),a.X)),a.i.u(e,d);a=Error("Unsupported subtitles format in web player (Format2)");a.params=c;throw a;}if("transcript"===e.firstChild.tagName)throw a=Error("Unsupported subtitles format in web player (Format1)"),a.params=c,a;a=Error("Invalid caption track data");a.params=c;throw a;},SOa=function(a){var b=
{};
if(a=g.mG(a))b.lang=a,g.BKa.test(a)&&(b.Ff=1);return b},k5=function(a){g.kN.call(this,a);
var b=this;this.I=a;this.X=this.I.U();this.videoData=this.I.getVideoData();this.kb=this.I.eb();this.C={jd:{}};this.D={jd:{}};this.ya=[];this.N={};this.La={};this.ea=!1;this.tb=g.BH(this.videoData);this.bb=g.Kta(this.videoData,this.I);this.ob=!!this.videoData.captionTracks.length;this.wb=!!this.videoData.Xb;this.Ka="3"===this.X.controlsType;this.u=this.J=this.K=this.Ha=this.Xa=null;this.Qa=new h5(this.X);this.i=null;this.ma=new g.aN(this);this.Ta=new g.W({G:"div",L:"ytp-caption-window-container",W:{id:"ytp-caption-window-container"}});
var c=null,d=g.ur("yt-html5-player-modules::subtitlesModuleData");d&&(c=new g.er(d));this.storage=c;c=a.dd();this.fb=!(null===c||void 0===c||!c.Jw());this.B=TOa(this);this.V=!this.B&&this.Ka&&this.fb&&this.bb;g.J(this,this.Qa);this.B?this.Ca=this.Aa=null:(this.Aa=new g.zq(this.BF,void 0,this),g.J(this,this.Aa),this.Ca=new g.K(this.BV,2E3,this),g.J(this,this.Ca));g.J(this,this.ma);this.X.Y("caption_window_container_killswitch")||g.YM(this.player,this.Ta.element,4);g.J(this,this.Ta);this.B||this.ma.S(a,
"resize",this.DF);(this.gb=!g.Ex()&&!this.I.isFullscreen()&&!this.B&&!this.V&&!this.X.Y("switch_captions_to_track_tag_when_fullscreen_api_unavailable_killswitch"))&&this.ma.S(a,"resize",this.vT);this.ma.S(a,"onPlaybackAudioChange",this.xS);this.ma.S(a,g.kA("captions"),function(e){b.Bd(e)});
this.ma.S(a,g.lA("captions"),function(e){b.nf(e)});
i5(this,j5(this,"display-settings")||{})},VOa=function(a){if(1===a.X.Ta||1===a.videoData.Nt||"alwayson"===g.kH(a.videoData,"yt:cc"))return!0;
if(2===a.X.Ta){var b;g.PF(a.X)?b=UOa(a):b=j5(a,"module-enabled");if(null!=b)return!!b}if(a.videoData.captionTracks.length)var c=a.player.getAudioTrack().u;b=t4(a.player.getAudioTrack(),u4(a.X));var d=g.kH(a.videoData,"yt:cc");if(void 0===l5(a)){if("CAPTIONS_INITIAL_STATE_ON_RECOMMENDED"===b)return d?"on"===d:!0;if("CAPTIONS_INITIAL_STATE_OFF_RECOMMENDED"===b)return"on"===d}else return"on"===d;return"ON"===c||"on"===g.kH(a.videoData,"yt:cc")},m5=function(a,b){if(a.i&&(void 0===b||!b)||!a.videoData.captionTracks.length)return!1;
a=a.player.getAudioTrack();return!!a.i||"FORCED_ON"===a.u},l5=function(a){var b=void 0,c=g.wv(g.uv.getInstance(),65);
if(g.PF(a.X)&&null!=c){if(null!=UOa(a))return!1;b=!c}return b},WOa=function(a){var b;
a.tb?b=new A4(a.X,a.videoData,a.player.getAudioTrack(),a.player):a.bb?b=new x4(a.videoData.i,a.player):a.ob?b=new g.oN(a.X,a.videoData,a.player.getAudioTrack()):b=new g.qN(a.X,a.videoData.Xb,a.videoData.videoId,g.noa(a.videoData),a.videoData.Nj);return b},o5=function(a,b){if(a.u){if(a.J&&a.J.C)return a.J.C;
b||(b=a.wb?!1:a.ob?!1:!0);b=g.lN(a.u.u,b);for(var c=[a.videoData.captionsLanguagePreference,a.X.captionsLanguagePreference,g.kH(a.videoData,"yt:cc_default_lang")],d=0;d<c.length;d++)for(var e=0;e<b.length;e++)if(g.mG(b[e])===c[d])return b[e];return a.J&&a.J.B?a.J.B:(c=b.find(function(f){return f.isDefault}))?c:b[0]||n5(a)}return null},n5=function(a){return a.J&&a.J.i},p5=function(a){var b=n5(a);
return!!b&&a.i===b},XOa=function(a){var b=t4(a.player.getAudioTrack(),u4(a.X)),c;
"CAPTIONS_INITIAL_STATE_UNKNOWN"===b?l5(a)||a.ea||VOa(a)?c=o5(a,a.ea):m5(a)&&(c=n5(a)):"CAPTIONS_INITIAL_STATE_ON_REQUIRED"===b?c=o5(a,a.ea):"CAPTIONS_INITIAL_STATE_OFF_REQUIRED"===b&&m5(a)&&(c=n5(a));if(a.B||a.V){var d=g.lN(a.u.u,!0);b=[];for(var e=0;e<d.length;e++){var f=d[e],h=g.sg("TRACK");h.setAttribute("kind","subtitles");h.setAttribute("label",g.kG(f));h.setAttribute("srclang",g.mG(f));h.setAttribute("id",f.toString());a.V||h.setAttribute("src",a.u.Ap(f,"vtt"));f===c&&h.setAttribute("default",
"1");b.push(h)}c=a.I.dd();c.au(b);c=c.Je();a.fb&&a.ma.S(c.textTracks,"change",a.YU)}else!a.i&&c&&q5(a,c),a.player.Ma("onCaptionsTrackListChanged"),a.player.Ma("onApiChange")},YOa=function(a,b){var c=a.I.dd().Je().textTracks;
a=a.i.toString();for(var d=0;d<c.length;d++){var e=c[d];e.id===a&&(b?"showing"!==e.mode&&(e.mode="showing"):"showing"===e.mode&&(e.mode="disabled"))}},q5=function(a,b,c){a.loaded&&a.unload();
null!=c&&(a.ea=c,a.ea&&(g.PF(a.X)?r5(a,!!b):s5(a,"module-enabled",!!b)));a.i=b;m5(a)&&(a.i=n5(a));a.load()},ZOa=function(a,b){a.X.Y("caption_window_container_killswitch")?g.YM(a.player,b,4):a.Ta.element.appendChild(b)},$Oa=function(a,b){var c=a.kb.getVideoContentRect(!0).height;
if(!c)return null;var d=a.i?g.mG(a.i):null;d&&g.BKa.test(d)&&(b.params.Ff=1);d=a.kb.getPlayerSize();switch(null!=b.params.qs?b.params.qs:1<b.i.length?1:0){case 1:return new B4(b,a.C,a.D,c,d.width,d.height,a.X.experiments);case 2:return new C4(b,a.C,a.D,c,d.width,d.height,a.X.experiments);default:return new z4(b,a.C,a.D,c,d.width,d.height,a.X.experiments)}},i5=function(a,b,c){c=void 0===c?!1:c;
var d=t5.jd;a.C={};Object.assign(a.C,t5);a.C.jd={};Object.assign(a.C.jd,d);a.D={jd:{}};var e=b.backgroundOverride?a.D:a.C,f=b.background||d.background;L4.test(f);e.jd.background=f;e=b.colorOverride?a.D:a.C;f=b.color||d.color;L4.test(f);e.jd.color=f;e=b.windowColorOverride?a.D:a.C;f=b.windowColor||t5.windowColor;L4.test(f);e.windowColor=f;e=b.backgroundOpacityOverride?a.D:a.C;f=b.backgroundOpacity;null==f&&(f=d.backgroundOpacity);e.jd.backgroundOpacity=f;e=b.fontSizeIncrementOverride?a.D:a.C;f=b.fontSizeIncrement;
null==f&&(f=d.fontSizeIncrement);e.jd.fontSizeIncrement=f;f=b.fontStyleOverride?a.D:a.C;e=b.fontStyle;null==e&&(e=d.bold&&d.lj?3:d.bold?1:d.lj?2:0);f=f.jd;switch(e){case 1:f.bold=!0;delete f.lj;break;case 2:delete f.bold;f.lj=!0;break;case 3:f.bold=!0;f.lj=!0;break;default:delete f.bold,delete f.lj}e=b.textOpacityOverride?a.D:a.C;f=b.textOpacity;null==f&&(f=d.textOpacity);e.jd.textOpacity=f;e=b.windowOpacityOverride?a.D:a.C;f=b.windowOpacity;null==f&&(f=t5.windowOpacity);e.windowOpacity=f;e=b.charEdgeStyleOverride?
a.D:a.C;f=b.charEdgeStyle;null==f&&(f=d.charEdgeStyle);e.jd.charEdgeStyle=f;e=b.fontFamilyOverride?a.D:a.C;f=b.fontFamily;null==f&&(f=d.fontFamily);e.jd.fontFamily=f;a.loaded&&a.DF();c&&s5(a,"display-settings",b)},bPa=function(a,b){b&&!a.K?(b=mOa({Ff:0,
lang:"id"}),a.K=[b,new D4(b.start,b.end-b.start,0,b.id,"Subtitel akan terlihat seperti ini")],a.player.Hd(a.K)):!b&&a.K&&(aPa(a,a.K),a.K=null)},aPa=function(a,b){a.player.Rf(b);
g.Db(b,function(c){g.ob(this.ya,c)},a);
g.Aq(a.Aa)},j5=function(a,b){if(!a.storage)return null;
try{var c=a.storage.get(b)}catch(d){a.storage.remove(b)}return c},s5=function(a,b,c){if(a.storage)try{a.storage.set(b,c)}catch(d){}},r5=function(a,b){a.I.isInline()||g.wz("yt-player-sticky-caption",b,2592E3)},UOa=function(a){if(!a.I.isInline())return g.xz("yt-player-sticky-caption")},TOa=function(a){var b=a.I.dd();
b=!(null===b||void 0===b||!b.Iw());return a.Ka&&b&&!a.bb};
g.sT.prototype.Ru=g.ca(31,function(a){var b=2;this.ma.has(a)?b=0:g.mza(this,a)&&(b=1);return b});
g.UV.prototype.Ru=g.ca(30,function(a){return this.Ed.Ru(a)});
g.EN.prototype.lr=g.ca(29,function(){this.oa();for(var a=g.fg(document,"track",void 0,this.i),b=0;b<a.length;b++)g.wg(a[b])});
g.zS.prototype.lr=g.ca(28,function(){this.ra.lr()});
g.EN.prototype.Jw=g.ca(27,function(){return!(!this.i.textTracks||!this.i.textTracks.addEventListener)});
g.zS.prototype.Jw=g.ca(26,function(){return this.ra.Jw()});
g.EN.prototype.Iw=g.ca(25,function(){return!!this.i.textTracks});
g.zS.prototype.Iw=g.ca(24,function(){return this.ra.Iw()});
g.EN.prototype.au=g.ca(23,function(a){this.oa();for(var b=0;b<a.length;b++)this.i.appendChild(a[b])});
g.zS.prototype.au=g.ca(22,function(a){this.ra.au(a)});
g.nN.prototype.vE=g.ca(21,function(){return!1});
g.nN.prototype.Fn=g.ca(20,function(){});
g.oN.prototype.Fn=g.ca(19,function(a,b,c){var d=this;this.isDisposed();b=this.Ap(a,b);this.wm();this.i=g.lt(b,{format:"RAW",onSuccess:function(e){d.i=null;c(e.responseText,a)},
withCredentials:!0})});
g.qN.prototype.Fn=g.ca(18,function(a,b,c){var d=this;this.isDisposed();b=this.Ap(a,b);this.wm();this.i=g.lt(b,{format:"RAW",onSuccess:function(e){d.i=null;c(e.responseText,a)},
withCredentials:!0})});
g.DV.prototype.hv=g.ca(6,function(){return this.K});
g.$X.prototype.hv=g.ca(5,function(){var a;return(null===(a=g.$M(this))||void 0===a?void 0:a.Yu())||null});
g.RM.prototype.Yu=g.ca(4,function(){return this.app.hv()});
g.DX.prototype.Yu=g.ca(3,function(){var a;return(null===(a=this.Ya)||void 0===a?void 0:a.hv())||null});
var YNa={aa:"Afar",ab:"Abkhazian",ace:"Achinese",ach:"Acoli",ada:"Adangme",ady:"Adyghe",ae:"Avestan",af:"Afrikaans",afh:"Afrihili",agq:"Aghem",ain:"Ainu",ak:"Akan",akk:"Akkadian",ale:"Aleut",alt:"Southern Altai",am:"Amharic",an:"Aragonese",ang:"Old English",anp:"Angika",ar:"Arabic",ar_001:"Arabic (world)",arc:"Aramaic",arn:"Mapuche",arp:"Arapaho",ars:"Najdi Arabic",arw:"Arawak",as:"Assamese",asa:"Asu",ast:"Asturian",av:"Avaric",awa:"Awadhi",ay:"Aymara",az:"Azerbaijani",az_Cyrl:"Azerbaijani (Cyrillic)",
az_Latn:"Azerbaijani (Latin)",ba:"Bashkir",bal:"Baluchi",ban:"Balinese",bas:"Basaa",bax:"Bamun",bbj:"Ghomala",be:"Belarusian",bej:"Beja",bem:"Bemba",bez:"Bena",bfd:"Bafut",bg:"Bulgarian",bho:"Bhojpuri",bi:"Bislama",bik:"Bikol",bin:"Bini",bkm:"Kom",bla:"Siksika",bm:"Bambara",bn:"Bangla",bo:"Tibetan",br:"Breton",bra:"Braj",brx:"Bodo",bs:"Bosnian",bs_Cyrl:"Bosnian (Cyrillic)",bs_Latn:"Bosnian (Latin)",bss:"Akoose",bua:"Buriat",bug:"Buginese",bum:"Bulu",byn:"Blin",byv:"Medumba",ca:"Catalan",cad:"Caddo",
car:"Carib",cay:"Cayuga",cch:"Atsam",ccp:"Chakma",ce:"Chechen",ceb:"Cebuano",cgg:"Chiga",ch:"Chamorro",chb:"Chibcha",chg:"Chagatai",chk:"Chuukese",chm:"Mari",chn:"Chinook Jargon",cho:"Choctaw",chp:"Chipewyan",chr:"Cherokee",chy:"Cheyenne",ckb:"Central Kurdish",ckb_Arab:"Central Kurdish (Arabic)",co:"Corsican",cop:"Coptic",cr:"Cree",crh:"Crimean Turkish",cs:"Czech",csb:"Kashubian",cu:"Church Slavic",cv:"Chuvash",cy:"Welsh",da:"Danish",dak:"Dakota",dar:"Dargwa",dav:"Taita",de:"German",de_AT:"German (Austria)",
de_CH:"German (Switzerland)",del:"Delaware",den:"Slave",dgr:"Dogrib",din:"Dinka",dje:"Zarma",doi:"Dogri",dsb:"Lower Sorbian",dua:"Duala",dum:"Middle Dutch",dv:"Divehi",dyo:"Jola-Fonyi",dyu:"Dyula",dz:"Dzongkha",dzg:"Dazaga",ebu:"Embu",ee:"Ewe",efi:"Efik",egy:"Ancient Egyptian",eka:"Ekajuk",el:"Greek",elx:"Elamite",en:"English",en_AU:"English (Australia)",en_CA:"English (Canada)",en_GB:"English (United Kingdom)",en_US:"English (United States)",enm:"Middle English",eo:"Esperanto",es:"Spanish",es_419:"Spanish (Latin America)",
es_ES:"Spanish (Spain)",es_MX:"Spanish (Mexico)",et:"Estonian",eu:"Basque",ewo:"Ewondo",fa:"Persian",fa_AF:"Persian (Afghanistan)",fan:"Fang",fat:"Fanti",ff:"Fulah",ff_Adlm:"Fulah (Adlam)",ff_Latn:"Fulah (Latin)",fi:"Finnish",fil:"Filipino",fj:"Fijian",fo:"Faroese",fon:"Fon",fr:"French",fr_CA:"French (Canada)",fr_CH:"French (Switzerland)",frm:"Middle French",fro:"Old French",frr:"Northern Frisian",frs:"Eastern Frisian",fur:"Friulian",fy:"Western Frisian",ga:"Irish",gaa:"Ga",gay:"Gayo",gba:"Gbaya",
gd:"Scottish Gaelic",gez:"Geez",gil:"Gilbertese",gl:"Galician",gmh:"Middle High German",gn:"Guarani",goh:"Old High German",gon:"Gondi",gor:"Gorontalo",got:"Gothic",grb:"Grebo",grc:"Ancient Greek",gsw:"Swiss German",gu:"Gujarati",guz:"Gusii",gv:"Manx",gwi:"Gwich\u02bcin",ha:"Hausa",hai:"Haida",haw:"Hawaiian",he:"Hebrew",hi:"Hindi",hil:"Hiligaynon",hit:"Hittite",hmn:"Hmong",ho:"Hiri Motu",hr:"Croatian",hsb:"Upper Sorbian",ht:"Haitian Creole",hu:"Hungarian",hup:"Hupa",hy:"Armenian",hz:"Herero",ia:"Interlingua",
iba:"Iban",ibb:"Ibibio",id:"Indonesian",ie:"Interlingue",ig:"Igbo",ii:"Sichuan Yi",ik:"Inupiaq",ilo:"Iloko","in":"Indonesian",inh:"Ingush",io:"Ido",is:"Icelandic",it:"Italian",iu:"Inuktitut",iw:"Hebrew",ja:"Japanese",jbo:"Lojban",jgo:"Ngomba",jmc:"Machame",jpr:"Judeo-Persian",jrb:"Judeo-Arabic",jv:"Javanese",ka:"Georgian",kaa:"Kara-Kalpak",kab:"Kabyle",kac:"Kachin",kaj:"Jju",kam:"Kamba",kaw:"Kawi",kbd:"Kabardian",kbl:"Kanembu",kcg:"Tyap",kde:"Makonde",kea:"Kabuverdianu",kfo:"Koro",kg:"Kongo",kha:"Khasi",
kho:"Khotanese",khq:"Koyra Chiini",ki:"Kikuyu",kj:"Kuanyama",kk:"Kazakh",kkj:"Kako",kl:"Kalaallisut",kln:"Kalenjin",km:"Khmer",kmb:"Kimbundu",kn:"Kannada",ko:"Korean",kok:"Konkani",kos:"Kosraean",kpe:"Kpelle",kr:"Kanuri",krc:"Karachay-Balkar",krl:"Karelian",kru:"Kurukh",ks:"Kashmiri",ks_Arab:"Kashmiri (Arabic)",ksb:"Shambala",ksf:"Bafia",ksh:"Colognian",ku:"Kurdish",kum:"Kumyk",kut:"Kutenai",kv:"Komi",kw:"Cornish",ky:"Kyrgyz",la:"Latin",lad:"Ladino",lag:"Langi",lah:"Lahnda",lam:"Lamba",lb:"Luxembourgish",
lez:"Lezghian",lg:"Ganda",li:"Limburgish",lkt:"Lakota",ln:"Lingala",lo:"Lao",lol:"Mongo",loz:"Lozi",lrc:"Northern Luri",lt:"Lithuanian",lu:"Luba-Katanga",lua:"Luba-Lulua",lui:"Luiseno",lun:"Lunda",luo:"Luo",lus:"Mizo",luy:"Luyia",lv:"Latvian",mad:"Madurese",maf:"Mafa",mag:"Magahi",mai:"Maithili",mak:"Makasar",man:"Mandingo",mas:"Masai",mde:"Maba",mdf:"Moksha",mdr:"Mandar",men:"Mende",mer:"Meru",mfe:"Morisyen",mg:"Malagasy",mga:"Middle Irish",mgh:"Makhuwa-Meetto",mgo:"Meta\u02bc",mh:"Marshallese",
mi:"Maori",mic:"Mi'kmaq",min:"Minangkabau",mk:"Macedonian",ml:"Malayalam",mn:"Mongolian",mnc:"Manchu",mni:"Manipuri",mni_Beng:"Manipuri (Bangla)",mo:"Romanian (Moldova)",moh:"Mohawk",mos:"Mossi",mr:"Marathi",ms:"Malay",mt:"Maltese",mua:"Mundang",mul:"Multiple languages",mus:"Muscogee",mwl:"Mirandese",mwr:"Marwari",my:"Burmese",mye:"Myene",myv:"Erzya",mzn:"Mazanderani",na:"Nauru",nap:"Neapolitan",naq:"Nama",nb:"Norwegian Bokm\u00e5l",nd:"North Ndebele",nds:"Low German",nds_NL:"Low German (Netherlands)",
ne:"Nepali","new":"Newari",ng:"Ndonga",nia:"Nias",niu:"Niuean",nl:"Dutch",nl_BE:"Dutch (Belgium)",nmg:"Kwasio",nn:"Norwegian Nynorsk",nnh:"Ngiemboon",no:"Norwegian",nog:"Nogai",non:"Old Norse",nqo:"N\u2019Ko",nr:"South Ndebele",nso:"Northern Sotho",nus:"Nuer",nv:"Navajo",nwc:"Classical Newari",ny:"Nyanja",nym:"Nyamwezi",nyn:"Nyankole",nyo:"Nyoro",nzi:"Nzima",oc:"Occitan",oj:"Ojibwa",om:"Oromo",or:"Odia",os:"Ossetic",osa:"Osage",ota:"Ottoman Turkish",pa:"Punjabi",pa_Arab:"Punjabi (Arabic)",pa_Guru:"Punjabi (Gurmukhi)",
pag:"Pangasinan",pal:"Pahlavi",pam:"Pampanga",pap:"Papiamento",pau:"Palauan",pcm:"Nigerian Pidgin",peo:"Old Persian",phn:"Phoenician",pi:"Pali",pl:"Polish",pon:"Pohnpeian",pro:"Old Proven\u00e7al",ps:"Pashto",pt:"Portuguese",pt_BR:"Portuguese (Brazil)",pt_PT:"Portuguese (Portugal)",qu:"Quechua",raj:"Rajasthani",rap:"Rapanui",rar:"Rarotongan",rm:"Romansh",rn:"Rundi",ro:"Romanian",ro_MD:"Romanian (Moldova)",rof:"Rombo",rom:"Romany",ru:"Russian",rup:"Aromanian",rw:"Kinyarwanda",rwk:"Rwa",sa:"Sanskrit",
sad:"Sandawe",sah:"Sakha",sam:"Samaritan Aramaic",saq:"Samburu",sas:"Sasak",sat:"Santali",sat_Olck:"Santali (Ol Chiki)",sba:"Ngambay",sbp:"Sangu",sc:"Sardinian",scn:"Sicilian",sco:"Scots",sd:"Sindhi",sd_Arab:"Sindhi (Arabic)",sd_Deva:"Sindhi (Devanagari)",se:"Northern Sami",see:"Seneca",seh:"Sena",sel:"Selkup",ses:"Koyraboro Senni",sg:"Sango",sga:"Old Irish",sh:"Serbo-Croatian",shi:"Tachelhit",shi_Latn:"Tachelhit (Latin)",shi_Tfng:"Tachelhit (Tifinagh)",shn:"Shan",shu:"Chadian Arabic",si:"Sinhala",
sid:"Sidamo",sk:"Slovak",sl:"Slovenian",sm:"Samoan",sma:"Southern Sami",smj:"Lule Sami",smn:"Inari Sami",sms:"Skolt Sami",sn:"Shona",snk:"Soninke",so:"Somali",sog:"Sogdien",sq:"Albanian",sr:"Serbian",sr_Cyrl:"Serbian (Cyrillic)",sr_Latn:"Serbian (Latin)",srn:"Sranan Tongo",srr:"Serer",ss:"Swati",ssy:"Saho",st:"Southern Sotho",su:"Sundanese",su_Latn:"Sundanese (Latin)",suk:"Sukuma",sus:"Susu",sux:"Sumerian",sv:"Swedish",sw:"Swahili",sw_CD:"Swahili (Congo - Kinshasa)",swb:"Comorian",syc:"Classical Syriac",
syr:"Syriac",ta:"Tamil",te:"Telugu",tem:"Timne",teo:"Teso",ter:"Tereno",tet:"Tetum",tg:"Tajik",th:"Thai",ti:"Tigrinya",tig:"Tigre",tiv:"Tiv",tk:"Turkmen",tkl:"Tokelau",tl:"Tagalog",tlh:"Klingon",tli:"Tlingit",tmh:"Tamashek",tn:"Tswana",to:"Tongan",tog:"Nyasa Tonga",tpi:"Tok Pisin",tr:"Turkish",trv:"Taroko",ts:"Tsonga",tsi:"Tsimshian",tt:"Tatar",tum:"Tumbuka",tvl:"Tuvalu",tw:"Twi",twq:"Tasawaq",ty:"Tahitian",tyv:"Tuvinian",tzm:"Central Atlas Tamazight",udm:"Udmurt",ug:"Uyghur",uga:"Ugaritic",uk:"Ukrainian",
umb:"Umbundu",ur:"Urdu",uz:"Uzbek",uz_Arab:"Uzbek (Arabic)",uz_Cyrl:"Uzbek (Cyrillic)",uz_Latn:"Uzbek (Latin)",vai:"Vai",vai_Latn:"Vai (Latin)",vai_Vaii:"Vai (Vai)",ve:"Venda",vi:"Vietnamese",vo:"Volap\u00fck",vot:"Votic",vun:"Vunjo",wa:"Walloon",wae:"Walser",wal:"Wolaytta",war:"Waray",was:"Washo",wo:"Wolof",xal:"Kalmyk",xh:"Xhosa",xog:"Soga",yao:"Yao",yap:"Yapese",yav:"Yangben",ybb:"Yemba",yi:"Yiddish",yo:"Yoruba",yue:"Cantonese",yue_Hans:"Cantonese (Simplified)",yue_Hant:"Cantonese (Traditional)",
za:"Zhuang",zap:"Zapotec",zbl:"Blissymbols",zen:"Zenaga",zgh:"Standard Moroccan Tamazight",zh:"Chinese",zh_Hans:"Chinese (Simplified)",zh_Hant:"Chinese (Traditional)",zh_TW:"Chinese (Taiwan)",zu:"Zulu",zun:"Zuni",zxx:"No linguistic content",zza:"Zaza"};v4.prototype.contains=function(a){a=g.xb(this.segments,a);return 0<=a||0>a&&1===(-a-1)%2};
v4.prototype.length=function(){return this.segments.length/2};
g.w(w4,g.H);g.k=w4.prototype;g.k.xa=function(){g.H.prototype.xa.call(this);this.u&&this.u.cancel()};
g.k.pG=function(){this.seekTo(this.player.getCurrentTime())};
g.k.seekTo=function(a){a-=this.player.Rc();var b=this.i;this.i=g.db(this.V.pn(a).i);b!==this.i&&this.N&&this.N()};
g.k.reset=function(){this.C=new v4;this.u&&(this.u.cancel(),this.u=null)};
g.k.bK=function(){var a;this.isDisposed();var b;if(b=null!=this.i)b=this.i,b=b.i.Bm(b);if(b&&!this.u&&!(this.i&&30<this.i.startTime-this.player.getCurrentTime())){b=this.i;b=b.i.xt(b);if(this.X.Y("enable_h5_ssdai_caption")&&(null===(a=this.player.getVideoData())||void 0===a?0:a.enableServerStitchedDai)){var c=this.player.Yu();if(c){var d=b.i[0].Na,e=c.Fr(b.i[0].C,d,b.i[0].i.info.id,3);if(e)if(c=c.Ru(d),0===c)e&&(b.B=new g.MB(e));else if(2===c){this.J.start();WNa(this)&&this.seekTo(this.player.getCurrentTime());
return}}}b.i[0].duration?(this.C.contains(b.i[0].Na)||XNa(this,b),this.i=g.db(b.i)):!g.T(this.X.experiments,"force_caption_seek_for_live_killswitch")&&WNa(this)&&this.seekTo(this.player.getCurrentTime())}this.J.start()};
g.k.oa=function(){};
g.w(x4,g.nN);g.k=x4.prototype;g.k.Fn=function(a,b,c){var d=this;this.wm();b=$Na(this,a.getId());b||(b=a.languageCode,b=this.i.isManifestless?aOa(this,b,"386"):aOa(this,b));if(b){var e=1E3*(b.index.getStartTimeInPeriod(b.index.getFirstSegmentNumber())-b.index.getStartTime(b.index.getFirstSegmentNumber())),f=new g.Ita(this.X);this.B=new w4(f,this.I,b,function(h,l){c(h,a,l,e)},this.J||g.vD(b.info),function(){d.B&&d.B.reset();
d.D=!0})}};
g.k.vE=function(){var a=this.D;this.D=!1;return a};
g.k.ds=function(a){var b=this.J?[new g.jG({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.jG({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]:this.i.isManifestless?ZNa(this,"386"):ZNa(this);b=g.r(b);for(var c=b.next();!c.done;c=b.next())g.mN(this.u,c.value);a()};
g.k.wm=function(){this.B&&(this.B.dispose(),this.B=null)};
g.k.Ap=function(){return""};
var L4=/^#(?:[0-9a-f]{3}){1,2}$/i,cOa=/#(.)(.)(.)/,bOa=/^#(?:[0-9a-f]{3}){1,2}$/i;var eOa=["left","right","center","justify"];g.w(z4,g.W);g.k=z4.prototype;g.k.vO=function(a,b){var c=g.Zl(this.element,this.element.parentElement);this.bb=a-c.x;this.fb=b-c.y;g.N(this.element,"ytp-dragging")};
g.k.uO=function(a,b){var c=g.am(this.element);a=a-this.bb-.02*this.playerWidth;var d=b-this.fb-.02*this.playerHeight,e=(a+c.width/2)/this.maxWidth*3;e=Math.floor(g.Rf(e,0,2));var f=(d+c.height/2)/this.Ta*3;f=Math.floor(g.Rf(f,0,2));b=e+3*f;a=(a+e/2*c.width)/this.maxWidth;a=100*g.Rf(a,0,1);c=(d+f/2*c.height)/this.Ta;c=100*g.Rf(c,0,1);this.u.params.di=b;this.u.params.Fj=c;this.u.params.eh=a;this.i.di=b;this.i.Fj=c;this.i.eh=a;this.Ha.di=b;this.Ha.Fj=c;this.Ha.eh=a;this.TL()};
g.k.tO=function(){g.Lq(this.element,"ytp-dragging")};
g.k.TL=function(){this.Ns(this.D)};
g.k.Mb=function(){return this.type};
g.k.Ns=function(a){var b=Math.min(this.TI(),this.maxWidth),c=this.SI(),d="";3===this.u.params.Ff&&(d="rotate(180deg)");g.Ml(this.element,{top:0,left:0,right:"",bottom:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"96%","max-height":"96%",margin:"",transform:""});this.LB(a);a={transform:d,top:"",left:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"","max-height":""};var e=.96*this.i.eh+2;d=this.i.di;switch(d){case 0:case 3:case 6:(b=this.i.jd.fontSizeIncrement)&&0<b&&2!==this.i.Ff&&3!==
this.i.Ff&&(e=Math.max(e/(1+2*b),2));a.left=e+"%";break;case 1:case 4:case 7:a.left=e+"%";e=this.C.offsetWidth;b||e?(b=b||e+1,a.width=b+"px",a["margin-left"]=b/-2+"px"):a.transform+=" translateX(-50%)";break;case 2:case 5:case 8:a.right=100-e+"%"}b=.96*this.i.Fj+2;switch(d){case 0:case 1:case 2:a.top=b+"%";break;case 3:case 4:case 5:a.top=b+"%";(c=c||this.element.clientHeight)?(a.height=c+"px",a["margin-top"]=c/-2+"px"):a.transform+=" translateY(-50%)";break;case 6:case 7:case 8:a.bottom=100-b+"%"}g.Ml(this.element,
a)};
g.k.LB=function(a){var b;for(b=0;b<a.length&&a[b]===this.D[b];b++);if(this.ya||this.D.length>b)b=0,this.ya=!1,this.D=[],this.J=this.Ca=this.Aa=null,g.ug(this.C);for(;b<a.length;b++)iOa(this,a[b])};
g.k.TI=function(){return 0};
g.k.SI=function(){return 0};
g.k.toString=function(){return g.W.prototype.toString.call(this)};g.w(A4,g.nN);A4.prototype.Fn=function(a,b,c){UNa(this.videoData.videoId,a.vssId,c)};
A4.prototype.ds=function(a){if(this.audioTrack)for(var b=g.r(this.audioTrack.captionTracks),c=b.next();!c.done;c=b.next())g.mN(this.u,c.value);a()};g.w(B4,z4);B4.prototype.LB=function(a){var b=this.u.i;z4.prototype.LB.call(this,a);for(a=a.length;a<b.length;a++){var c=b[a];if(f&&c.i===e)var d=f;else{d={};Object.assign(d,c.i);Object.assign(d,cPa);var e=c.i;var f=d}iOa(this,c,d)}};
var cPa={gR:!0};g.w(C4,z4);g.k=C4.prototype;g.k.TL=function(){g.Eq(this.Qa)};
g.k.sU=function(){g.Lq(this.element,"ytp-rollup-mode");this.Ns(this.tb,!0)};
g.k.SI=function(){return this.B?this.V:this.N};
g.k.TI=function(){return this.B?this.N:this.V};
g.k.Ns=function(a,b){this.tb=a;if(this.u.params.lm){for(var c=0,d=0;d<this.D.length&&c<a.length;d++)this.D[d]===a[c]&&c++;0<c&&c<a.length&&(a=this.D.concat(a.slice(c)));this.gb=this.V;this.N=this.V=0;z4.prototype.Ns.call(this,a);lOa(this,b)}z4.prototype.Ns.call(this,a)};g.w(D4,g.hA);D4.prototype.toString=function(){return g.hA.prototype.toString.call(this)};g.w(E4,g.hA);E4.prototype.toString=function(){return g.hA.prototype.toString.call(this)};
var F4=0;g.w(G4,g.H);G4.prototype.u=function(){return[]};
G4.prototype.reset=function(){};g.w(H4,G4);H4.prototype.reset=function(){this.N={};this.B=this.i=null;this.K=!0};
H4.prototype.u=function(a,b){a=a.firstChild;a.getAttribute("format");b=b||0;Number.isFinite(b);a=Array.from(a.childNodes);a=g.r(a);for(var c=a.next();!c.done;c=a.next())if(c=c.value,1===c.nodeType)switch(c.tagName){case "head":var d=c;break;case "body":var e=c}if(d)for(d=Array.from(d.childNodes),d=g.r(d),a=d.next();!a.done;a=d.next())if(a=a.value,1===a.nodeType)switch(a.tagName){case "pen":c=a.getAttribute("id");var f=this.C,h={},l=a.getAttribute("p");l&&Object.assign(h,this.C[l]);l=J4(a,"b");null!=
l&&(h.bold=l);l=J4(a,"i");null!=l&&(h.lj=l);l=J4(a,"u");null!=l&&(h.underline=l);l=K4(a,"et");null!=l&&(h.charEdgeStyle=l);l=K4(a,"of");null!=l&&(h.offset=l);l=M4(a,"bc");null!=l&&(h.background=l);l=M4(a,"ec");null!=l&&(h.bC=l);l=M4(a,"fc");null!=l&&(h.color=l);l=K4(a,"fs");null!=l&&0!==l&&(h.fontFamily=l);l=I4(a,"sz");void 0!==l&&(h.fontSizeIncrement=l/100-1);l=I4(a,"bo");void 0!==l&&(h.backgroundOpacity=l/255);l=I4(a,"fo");void 0!==l&&(h.textOpacity=l/255);l=K4(a,"rb");null!=l&&10!==l&&0!==l&&(h.Wd=
10<l?l-1:l);a=K4(a,"hg");null!=a&&(h.sJ=a);f[c]=h;break;case "ws":c=a.getAttribute("id");this.ea[c]=pOa(this,a);break;case "wp":c=a.getAttribute("id"),this.V[c]=qOa(this,a)}if(e){d=[];e=Array.from(e.childNodes);e=g.r(e);for(a=e.next();!a.done;a=e.next())if(a=a.value,1===a.nodeType)switch(a.tagName){case "w":this.i=rOa(this,a,b,!1);(a=this.N[this.i.id])&&a.end>this.i.start&&(a.end=this.i.start);this.N[this.i.id]=this.i;d.push(this.i);break;case "p":l=b;c=[];f=a.getAttribute("w")||this.J;h=!!J4(a,"a");
l=(I4(a,"t")||0)+l;var m=I4(a,"d")||5E3;h||(!this.K&&this.B&&this.B.windowId===f&&this.B.end>l&&(this.B.end=l),this.B&&"\n"===this.B.text&&(this.B.text=""));var n=h?6:5,p=a.getAttribute("p");p=p?this.C[p]:null;var q=Array.from(a.childNodes);q.length&&(this.K=null!=a.getAttribute("d"));for(var t=0;t<q.length;t++){var u=q[t],x=void 0;0<t&&(h=!0);var y=void 0;1===u.nodeType&&(y=u);if(y&&"s"===y.tagName){if((u=(u=y.getAttribute("p"))?this.C[u]:null)&&u.Wd&&(1===u.Wd?(u=q.slice(t,t+4),4===u.length&&(x=
oOa(l,m,f,h,n,u,this.C),t+=3)):x=oOa(l,m,f,h,n,[y],this.C)),!x){var B=y;x=l;y=m;u=f;var F=h,G=n,I=B.textContent?B.textContent:"",L=B.getAttribute("p");L=L?this.C[L]:null;B=I4(B,"t")||0;x=new D4(x+B,y-B,G,u,I,F,L)}}else x=new D4(l,m,n,f,u.textContent||"",h,p);c.push(x);this.B=x}if(0<c.length)for(c[0].windowId===this.J&&(this.i=rOa(this,a,b,!0),d.push(this.i)),a=g.r(c),c=a.next();!c.done;c=a.next())c=c.value,c.windowId=this.i.id,this.i.i.push(c),d.push(c)}b=d}else b=[];return b};var dPa=new Map([[9,1],[10,1],[11,2],[12,3],[13,4],[14,5]]);g.w(N4,G4);N4.prototype.reset=function(){this.B.clear()};
N4.prototype.u=function(a,b){var c=JSON.parse(a);if(!c)return[];if(c.pens){a=0;for(var d=g.r(c.pens),e=d.next();!e.done;e=d.next()){e=e.value;var f={},h=e.pParentId;h&&Object.assign(f,this.i.get(h));e.bAttr&&(f.bold=!0);e.iAttr&&(f.lj=!0);e.uAttr&&(f.underline=!0);h=e.ofOffset;null!=h&&(f.offset=h);void 0!==e.szPenSize&&(f.fontSizeIncrement=e.szPenSize/100-1);h=e.etEdgeType;null!=h&&(f.charEdgeStyle=h);void 0!==e.ecEdgeColor&&(f.bC=O4(e.ecEdgeColor));h=e.fsFontStyle;null!=h&&0!==h&&(f.fontFamily=
h);void 0!==e.fcForeColor&&(f.color=O4(e.fcForeColor));void 0!==e.foForeAlpha&&(f.textOpacity=e.foForeAlpha/255);void 0!==e.bcBackColor&&(f.background=O4(e.bcBackColor));void 0!==e.boBackAlpha&&(f.backgroundOpacity=e.boBackAlpha/255);(h=e.rbRuby)&&10!==h&&(f.Wd=10<h?h-1:h,f.Ej=dPa.get(f.Wd));e.hgHorizGroup&&(f.sJ=e.hgHorizGroup);this.i.set(a++,f)}}if(c.wsWinStyles)for(a=0,d=g.r(c.wsWinStyles),e=d.next();!e.done;e=d.next())e=e.value,f={},(h=e.wsParentId)?Object.assign(f,this.D.get(h)):Object.assign(f,
this.J),void 0!==e.mhModeHint&&(f.qs=e.mhModeHint),void 0!==e.juJustifCode&&(f.textAlign=e.juJustifCode),void 0!==e.pdPrintDir&&(f.Ff=e.pdPrintDir),void 0!==e.sdScrollDir&&(f.kF=e.sdScrollDir),void 0!==e.wfcWinFillColor&&(f.windowColor=O4(e.wfcWinFillColor)),void 0!==e.wfoWinFillAlpha&&(f.windowOpacity=e.wfoWinFillAlpha/255),this.D.set(a++,f);if(c.wpWinPositions)for(a=0,d=g.r(c.wpWinPositions),e=d.next();!e.done;e=d.next())e=e.value,f={},(h=e.wpParentId)&&Object.assign(f,this.C.get(h)),void 0!==e.ahHorPos&&
(f.eh=e.ahHorPos),void 0!==e.apPoint&&(f.di=e.apPoint),void 0!==e.avVerPos&&(f.Fj=e.avVerPos),void 0!==e.ccCols&&(f.Mm=e.ccCols),void 0!==e.rcRows&&(f.lm=e.rcRows),this.C.set(a++,f);if(c.events){a=[];c=g.r(c.events);for(d=c.next();!d.done;d=c.next()){var l=d.value;d=(l.tStartMs||0)+b;e=l.dDurationMs||0;if(l.id)f=String(l.id),d=sOa(this,l,d,e,f),a.push(d),this.B.set(f,d);else{l.wWinId?f=l.wWinId.toString():(f="_"+F4++,h=sOa(this,l,d,e,f),a.push(h),this.B.set(f,h));0===e&&(e=5E3);h=this.B.get(f);var m=
!!l.aAppend,n=m?6:5,p=l.segs,q=null;l.pPenId&&(q=this.i.get(l.pPenId));for(l=0;l<p.length;l++){var t=p[l],u=t.utf8;if(u){var x=t.tOffsetMs||0,y=null;t.pPenId&&(y=this.i.get(t.pPenId));if(2===(null!=h.params.qs?h.params.qs:1<h.i.length?1:0)&&m&&"\n"===u)continue;if(t=y&&1===y.Wd)if(t=l,t+3>=p.length||!p[t+1].pPenId||!p[t+2].pPenId||!p[t+3].pPenId)t=!1;else{var B=p[t+1].pPenId;(B=this.i.get(B))&&B.Wd&&2===B.Wd?(B=p[t+2].pPenId,B=this.i.get(B),!B||!B.Wd||3>B.Wd?t=!1:(B=p[t+3].pPenId,t=(B=this.i.get(B))&&
B.Wd&&2===B.Wd?!0:!1)):t=!1}if(t){x=p[l+1].utf8;t=p[l+3].utf8;B=p[l+2].utf8;var F=this.i.get(p[l+2].pPenId);u=nOa(u,x,B,t,F);m=new D4(d,e,n,f,u,m,y);l+=3}else m=new D4(d+x,e-x,n,h.id,u,m,y||q);m&&(a.push(m),h.i.push(m))}m=!0}}}b=a}else b=[];return b};Q4.prototype.clear=function(){this.B=this.time=this.mode=0;this.i=[];this.reset()};
Q4.prototype.reset=function(){this.mode=0;this.C.reset(0);this.D.reset(1)};
var tOa=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];R4.prototype.set=function(a){this.type=a};
R4.prototype.get=function(){return this.type};
S4.prototype.clear=function(){this.state=0};
S4.prototype.update=function(){this.state=2===this.state?1:0};
S4.prototype.isValid=function(){return 0!==this.state};
S4.prototype.matches=function(a,b){return this.isValid()&&a===this.Vo&&b===this.Hm};
yOa.prototype.reset=function(){this.timestamp=this.i=0};
T4.prototype.updateTime=function(a){for(var b=1;15>=b;++b)for(var c=1;32>=c;++c)this.B[b][c].timestamp=a};
T4.prototype.debugString=function(){for(var a="\n",b=1;15>=b;++b){for(var c=1;32>=c;++c){var d=this.B[b][c];a=0===d.i?a+"_":a+String.fromCharCode(d.i)}a+="\n"}return a};
T4.prototype.reset=function(a){for(var b=0;15>=b;b++)for(var c=0;32>=c;c++)this.B[b][c].reset();this.C=a;this.i=0;this.u=this.row=1};
var zOa=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],AOa=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],BOa=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],COa=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];Z4.prototype.reset=function(a,b){this.D=b;this.style.set(2);this.u=this.J;this.C=this.K;this.i=this.u;var c=(a<<2)+(b<<1);this.J.reset(c);this.K.reset(c);this.text.reset((a<<2)+(b<<1)+1)};
P4.prototype.reset=function(a){this.D=a;this.u.clear();this.C=this.B;this.B.reset(a,0);this.J.reset(a,1)};HOa.prototype.C=function(){};g.w(a5,HOa);a5.prototype.C=function(a,b,c,d,e){if(c<d){var f="_"+F4++;c=c/1E3-this.J;d=d/1E3-this.J;a=new E4(c,d-c,5,f,{textAlign:0,di:0,eh:2.5*b,Fj:5.33*a});e=new D4(c,d-c,5,f,e);this.u.push(a);this.u.push(e)}};
g.w(d5,G4);d5.prototype.u=function(a){a=new a5(a,a.byteLength,this.B);if(IOa(a)){for(;a.byteOffset<a.i.byteLength;)for(0===a.version?a.B=c5(a)*(1E3/45):1===a.version&&(a.B=4294967296*c5(a)+c5(a)),a.D=b5(a);0<a.D;a.D--){var b=b5(a),c=b5(a),d=b5(a);b&4&&(b&3)===this.track&&(0===this.track||1===this.track)&&(b=this.i,b.i.push({time:a.B,type:this.track,VH:c,WH:d,order:b.i.length}))}xOa(this.i,a);return a.u}return[]};
d5.prototype.reset=function(){this.i.clear()};g.w(f5,G4);
f5.prototype.u=function(a,b){var c=[];a=a.split(ePa);for(var d=1;d<a.length;d++){var e=a[d],f=b;if(""!==e&&!fPa.test(e)){var h=u5.exec(e);if(h&&4<=h.length){var l=g5(h[1]),m=g5(h[2])-l;l+=f;var n=(h=h[3])?h.split(" "):[];h={};var p=null;var q="";var t=null,u="";n=g.r(n);for(var x=n.next();!x.done;x=n.next())if(x=x.value.split(":"),2===x.length){var y=x[1];switch(x[0]){case "line":x=y.split(",");x[0].endsWith("%")&&(p=x[0],h.Fj=Number.parseInt(p,10),2===x.length&&(q=x[1].trim()));break;case "position":x=
y.split(",");t=x[0];h.eh=Number.parseInt(t,10);2===x.length&&(u=x[1].trim());break;case "align":switch(y){case "start":h.textAlign=0;break;case "middle":h.textAlign=2;break;case "end":h.textAlign=1}}}p||q||(q="end");if(!t)switch(h.textAlign){case 0:h.eh=0;break;case 1:h.eh=100;break;case 2:h.eh=50}if(null!=h.textAlign){p=0;switch(q){case "center":p+=3;break;case "end":p+=6;break;default:p+=0}switch(u){case "line-left":p+=0;break;case "center":p+=1;break;case "line-right":p+=2;break;default:switch(h.textAlign){case 0:p+=
0;break;case 2:p+=1;break;case 1:p+=2}}q=0>p||8<p?7:p;h.di=q}e=e.substring(u5.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");u=h;h=e;e={};if(0>h.indexOf("<")&&0>h.indexOf("&"))f=KOa(l,m,5,u),m=new D4(l,m,5,f.id,h,!1,g.Wb(e)?void 0:e),c.push(f),c.push(m),f.i.push(m);else for(q=h.split(gPa),1===q.length?(h=5,u=KOa(l,m,h,u)):(p=h=6,u=Object.assign({Mm:32},u),u=new E4(l,m,p,"_"+F4++,u)),c.push(u),p=l,t=0;t<q.length;t++)n=q[t],0===t%2?(x=g.U1("<html>"+n+"</html>"),x.getElementsByTagName("parsererror").length?
(y=x.createElement("span"),y.appendChild(x.createTextNode(n))):y=x.firstChild,JOa(this,p,m-(p-l),h,u,0<t,y,e,c)):p=g5(n)+f}u5.lastIndex=0}}return c};
var fPa=/^NOTE/,ePa=/(?:\r\n|\r|\n){2,}/,u5=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),gPa=RegExp("<((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})>");g.HS.Dy(f5,{u:"wvppt"});g.w(h5,g.H);h5.prototype.clear=function(){this.i&&this.i.dispose();this.i=null};
h5.prototype.reset=function(){this.i&&this.i.reset()};
h5.prototype.xa=function(){g.H.prototype.xa.call(this);this.clear()};var t5={windowColor:"#080808",windowOpacity:0,textAlign:2,di:7,eh:50,Fj:100,jd:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.w(k5,g.kN);g.k=k5.prototype;g.k.xa=function(){if(this.B||this.V){var a=this.I.dd();a&&!a.isDisposed()&&a.lr()}else bPa(this,!1);g.kN.prototype.xa.call(this)};
g.k.oq=function(){if(this.Ka)return this.B||this.V;var a=t4(this.player.getAudioTrack(),u4(this.X));return"CAPTIONS_INITIAL_STATE_ON_REQUIRED"===a?!0:"CAPTIONS_INITIAL_STATE_OFF_REQUIRED"===a?m5(this):l5(this)||m5(this)?!0:VOa(this)};
g.k.load=function(){var a=this;g.kN.prototype.load.call(this);var b=!g.T(this.X.experiments,"web_player_captions_track_list_changed_killswitch");this.J=this.player.getAudioTrack();this.u?(this.i&&(this.Qa.clear(),this.B?YOa(this,!0):3!==this.player.getPresentingPlayerType()&&this.u.Fn(this.i,"json3",function(c,d,e,f){c&&(a.u.vE()&&(a.ya=[],a.I.We("captions"),g.Aq(a.Aa),a.Qa.reset()),c=QOa(a.Qa,c,d,e,f),a.player.Hd(c),!a.ea||a.V||p5(a)||g.BF(a.X)||g.tF(a.X)||(g.Fq(a.Ca),c=mOa({di:0,eh:5,Fj:5,lm:2,
textAlign:0,Ff:0,lang:"id"}),a.Ha=[c],d=["Klik "," untuk mengubah setelan"],a.Xa||(e=new g.ZK(g.oL()),g.J(a,e),a.Xa=e.element),e=c.end-c.start,(f=g.kG(a.i))&&a.Ha.push(new D4(c.start,e,0,c.id,f)),a.Ha.push(new D4(c.start,e,0,c.id,d[0]),new D4(c.start,e,0,c.id,a.Xa,!0),new D4(c.start,e,0,c.id,d[1],!0)),a.player.Hd(a.Ha),g.Dq(a.Ca)),!a.ea||a.V||p5(a)||(g.PF(a.X)?r5(a,!0):s5(a,"module-enabled",!0),a.J&&(a.J.C=a.i),a.player.Bq()),a.ea=!1)}),!b||this.B||this.V||p5(this)||this.player.Ma("captionschanged",
g.lG(this.i))),b||(this.i&&!p5(this)?this.player.Ma("captionschanged",g.lG(this.i)):this.player.Ma("onCaptionsTrackListChanged"))):(this.u=WOa(this),g.J(this,this.u),this.u.ds(function(){XOa(a)}))};
g.k.unload=function(){this.B&&this.i?YOa(this,!1):(this.Ca&&g.Fq(this.Ca),this.player.We("captions"),this.ya=[],this.u&&this.u.wm(),this.Qa.clear(),this.K&&this.player.Hd(this.K),this.DF());g.kN.prototype.unload.call(this);this.player.Bq();this.player.Ma("captionschanged",{})};
g.k.create=function(){this.oq()&&this.load()};
g.k.YU=function(){for(var a=this.I.dd().Je().textTracks,b=null,c=0;c<a.length;c++)if("showing"===a[c].mode)a:{b=a[c].id;var d=g.lN(this.u.u,!0);for(var e=0;e<d.length;e++)if(d[e].toString()===b){b=d[e];break a}b=null}(this.loaded?this.i:null)!==b&&q5(this,b,!0)};
g.k.uW=function(){!this.i&&this.B||this.unload()};
g.k.Bd=function(a){this.ya.push(a);g.Aq(this.Aa)};
g.k.nf=function(a){g.ob(this.ya,a);this.u instanceof x4&&this.u.J&&this.player.Rf([a]);g.Aq(this.Aa)};
g.k.vV=function(a){if(a instanceof E4){var b=this.N[a.id];b&&b.u!==a&&(b.dispose(),delete this.N[a.id],b=null);b||(b=$Oa(this,a))&&(this.N[a.id]=b)}else b=a.windowId,this.La[b]||(this.La[b]=[]),this.La[b].push(a)};
g.k.getCaptionWindowContainerId=function(){return this.Ta.element.id};
g.k.BV=function(){aPa(this,this.Ha);this.Ha=null};
g.k.BF=function(){var a=this;if(!this.gb||!this.B){this.Aa.stop();g.Xb(this.La);this.ya.sort(g.jA);var b=this.ya;if(this.K){var c=g.Go(b,function(d){return-1===this.K.indexOf(d)},this);
c.length&&(b=c)}g.Db(b,this.vV,this);g.Gb(this.N,function(d,e){a.La[e]?(d.element.parentNode||(d instanceof C4||d instanceof B4||g.Jb(a.N,function(f,h){h!==e&&f.u.params.di===d.u.params.di&&f.u.params.eh===d.u.params.eh&&f.u.params.Fj===d.u.params.Fj&&(f.dispose(),delete a.N[h]);return h===e},a),ZOa(a,d.element)),d.Ns(a.La[e])):(d.dispose(),delete a.N[e])},this)}};
g.k.GV=function(){i5(this,{},!0);g.T(this.X.experiments,"web_player_disable_publish_captions_settings_changed_on_reset")||this.player.Ma("captionssettingschanged")};
g.k.CQ=function(){var a=t5.jd;a={background:a.background,backgroundOpacity:a.backgroundOpacity,charEdgeStyle:a.charEdgeStyle,color:a.color,fontFamily:a.fontFamily,fontSizeIncrement:a.fontSizeIncrement,fontStyle:a.bold&&a.lj?3:a.bold?1:a.lj?2:0,textOpacity:a.textOpacity,windowColor:t5.windowColor,windowOpacity:t5.windowOpacity};var b=j5(this,"display-settings")||{};null!=b.background&&(a.background=b.background);null!=b.backgroundOverride&&(a.backgroundOverride=b.backgroundOverride);null!=b.backgroundOpacity&&
(a.backgroundOpacity=b.backgroundOpacity);null!=b.backgroundOpacityOverride&&(a.backgroundOpacityOverride=b.backgroundOpacityOverride);null!=b.charEdgeStyle&&(a.charEdgeStyle=b.charEdgeStyle);null!=b.charEdgeStyleOverride&&(a.charEdgeStyleOverride=b.charEdgeStyleOverride);null!=b.color&&(a.color=b.color);null!=b.colorOverride&&(a.colorOverride=b.colorOverride);null!=b.fontFamily&&(a.fontFamily=b.fontFamily);null!=b.fontFamilyOverride&&(a.fontFamilyOverride=b.fontFamilyOverride);null!=b.fontSizeIncrement&&
(a.fontSizeIncrement=b.fontSizeIncrement);null!=b.fontSizeIncrementOverride&&(a.fontSizeIncrementOverride=b.fontSizeIncrementOverride);null!=b.fontStyle&&(a.fontStyle=b.fontStyle);null!=b.fontStyleOverride&&(a.fontStyleOverride=b.fontStyleOverride);null!=b.textOpacity&&(a.textOpacity=b.textOpacity);null!=b.textOpacityOverride&&(a.textOpacityOverride=b.textOpacityOverride);null!=b.windowColor&&(a.windowColor=b.windowColor);null!=b.windowColorOverride&&(a.windowColorOverride=b.windowColorOverride);
null!=b.windowOpacity&&(a.windowOpacity=b.windowOpacity);null!=b.windowOpacityOverride&&(a.windowOpacityOverride=b.windowOpacityOverride);return a};
g.k.RM=function(a,b){var c={};Object.assign(c,j5(this,"display-settings"));Object.assign(c,a);i5(this,c,b);this.player.Ma("captionssettingschanged")};
g.k.DF=function(){!this.B&&this.loaded&&(g.Gb(this.N,function(a,b){a.dispose();delete this.N[b]},this),this.BF())};
g.k.Ze=function(a,b){switch(a){case "fontSize":if(isNaN(b))break;var c=g.Rf(b,-2,4);this.RM({fontSizeIncrement:c});return c;case "reload":b&&!this.B&&q5(this,this.i,!0);break;case "stickyLoading":void 0!==b&&this.X.B&&(g.PF(this.X)?r5(this,!!b):s5(this,"module-enabled",!!b));break;case "track":if(!this.u)return{};if(b){if(this.B)break;if(!g.Ma(b))break;if(g.Wb(b)){q5(this,null,!0);break}a=g.lN(this.u.u,!0);for(var d=0;d<a.length;d++){var e=a[d];e.languageCode!==b.languageCode||c&&e.languageName!==
b.languageName||(c=b.translationLanguage?TNa(e,b.translationLanguage):e)}!c||c===this.i&&this.loaded||(b=g.Cla(),a=g.mG(c),b.length&&a===b[b.length-1]||(b.push(a),g.wz("yt-player-caption-language-preferences",b)),q5(this,c,!0))}else return this.loaded&&this.i&&!p5(this)?g.lG(this.i):{};return"";case "tracklist":return this.u?g.Se(g.lN(this.u.u,!(!b||!b.includeAsr)),function(f){return g.lG(f)}):[];
case "translationLanguages":return this.u?this.u.C.map(function(f){return Object.assign({},f)}):[];
case "sampleSubtitles":this.B||void 0===b||bPa(this,!!b)}};
g.k.getOptions=function(){var a="reload fontSize track tracklist translationLanguages sampleSubtitle".split(" ");this.X.B&&a.push("stickyLoading");return a};
g.k.VC=function(){var a=this.i;if(a){var b=a.vssId;a.translationLanguage&&b&&!this.X.Y("auto_translation_logging_killswitch")&&(b="t"+b+"."+g.mG(a));return{cc:b}}return{}};
g.k.jW=function(){this.loaded&&this.i&&!p5(this)?(g.PF(this.X)?r5(this,!1):s5(this,"module-enabled",!1),this.unload(),m5(this,!0)&&q5(this,n5(this),!1)):this.xM()};
g.k.xM=function(){this.loaded&&this.i||q5(this,p5(this)||!this.i?o5(this,!0):this.i,!0)};
g.k.xS=function(){var a=p5(this);m5(this,a)?q5(this,this.player.getAudioTrack().i,!1):this.videoData.captionTracks.length&&(this.loaded&&this.unload(),this.oq()&&(a?q5(this,o5(this),!1):this.load()))};
g.k.vT=function(){var a=this.I.dd();a&&!a.isDisposed()&&a.lr();this.I.isFullscreen()?(this.B=this.Ka=!0,this.loaded&&XOa(this)):(this.Ka="3"===this.X.controlsType,this.B=TOa(this));q5(this,this.i)};
g.HS.Dy(k5,{BF:"smucd"});g.vN.captions=k5;})(_yt_player);
