(function(g){var window=this;'use strict';var mPa=function(a,b){a.Ma("onAutonavCoundownStarted",b)},I5=function(a,b,c){g.O(a.element,"ytp-suggestion-set",!!b.videoId);
var d=b.playlistId;c=b.Ee(c?c:"mqdefault.jpg");var e=null,f=null;b instanceof g.CP&&(b.lengthText?(e=b.lengthText||null,f=b.Zr||null):b.lengthSeconds&&(e=g.YL(b.lengthSeconds),f=g.YL(b.lengthSeconds,!0)));var h=!!d;d=h&&"RD"===g.dN(d).type;var l=b instanceof g.CP?b.isLivePlayback:null,m=b instanceof g.CP?b.isUpcoming:null;c={title:b.title,author:b.author,author_and_views:b.shortViewCount?b.author+" \u2022 "+b.shortViewCount:b.author,aria_label:b.So||g.EI("Tonton $TITLE",{TITLE:b.title}),duration:e,
timestamp:f,url:b.Ak(),is_live:l,is_upcoming:m,is_list:h,is_mix:d,background:c?"background-image: url("+c+")":"",views_and_publish_time:b.shortViewCount?b.shortViewCount+" \u2022 "+b.publishedTimeText:b.publishedTimeText,autoplayAlternativeHeader:b.Uo};b instanceof g.BP&&(c.playlist_length=b.playlistLength);a.update(c)},J5=function(a){var b=a.U(),c=b.u;
g.W.call(this,{G:"a",L:"ytp-autonav-suggestion-card",W:{href:"{{url}}",target:c?b.K:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},T:[{G:"div",Ga:["ytp-autonav-endscreen-upnext-thumbnail","ytp-autonav-thumbnail-small"],W:{style:"{{background}}"},T:[{G:"div",W:{"aria-label":"{{timestamp}}"},Ga:["ytp-autonav-timestamp"],va:"{{duration}}"},{G:"div",Ga:["ytp-autonav-live-stamp"],va:"Live"},{G:"div",
Ga:["ytp-autonav-upcoming-stamp"],va:"Mendatang"},{G:"div",L:"ytp-autonav-list-overlay",T:[{G:"div",L:"ytp-autonav-mix-text",va:"Video Mix"},{G:"div",L:"ytp-autonav-mix-icon"}]}]},{G:"div",Ga:["ytp-autonav-endscreen-upnext-title","ytp-autonav-title-card"],va:"{{title}}"},{G:"div",Ga:["ytp-autonav-endscreen-upnext-author","ytp-autonav-author-card"],va:"{{author}}"},{G:"div",Ga:["ytp-autonav-endscreen-upnext-author","ytp-autonav-view-and-date-card"],va:"{{views_and_publish_time}}"}]});this.I=a;this.suggestion=
null;this.i=c;this.Sa("click",this.onClick);this.Sa("keypress",this.u)},L5=function(a,b){b=void 0===b?!1:b;
g.W.call(this,{G:"div",L:"ytp-autonav-endscreen-countdown-container"});var c=this;this.D=b;this.u=0;b=a.U();var d=b.u;this.I=a;this.suggestion=null;this.i=new g.W({G:"div",L:"ytp-autonav-endscreen-upnext-container",W:{"aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},T:[{G:"div",L:"ytp-autonav-endscreen-upnext-header"},{G:"div",L:"ytp-autonav-endscreen-upnext-alternative-header",va:"{{autoplayAlternativeHeader}}"},
{G:"a",L:"ytp-autonav-endscreen-link-container",W:{href:"{{url}}",target:d?b.K:""},T:[{G:"div",L:"ytp-autonav-endscreen-upnext-thumbnail",W:{style:"{{background}}"},T:[{G:"div",W:{"aria-label":"{{timestamp}}"},Ga:["ytp-autonav-timestamp"],va:"{{duration}}"},{G:"div",Ga:["ytp-autonav-live-stamp"],va:"Live"},{G:"div",Ga:["ytp-autonav-upcoming-stamp"],va:"Mendatang"}]},{G:"div",L:"ytp-autonav-endscreen-video-info",T:[{G:"div",L:"ytp-autonav-endscreen-premium-badge"},{G:"div",L:"ytp-autonav-endscreen-upnext-title",
va:"{{title}}"},{G:"div",L:"ytp-autonav-endscreen-upnext-author",va:"{{author}}"},{G:"div",L:"ytp-autonav-view-and-date",va:"{{views_and_publish_time}}"},{G:"div",L:"ytp-autonav-author-and-view",va:"{{author_and_views}}"}]}]}]});g.J(this,this.i);this.i.Da(this.element);d||this.S(this.i.Fa("ytp-autonav-endscreen-link-container"),"click",this.BG);this.I.Ub(this.element,this,115127);this.I.Ub(this.i.Fa("ytp-autonav-endscreen-link-container"),this,115128);this.overlay=new g.W({G:"div",L:"ytp-autonav-overlay"});
g.J(this,this.overlay);this.overlay.Da(this.element);this.B=new g.W({G:"div",L:"ytp-autonav-endscreen-button-container"});g.J(this,this.B);this.B.Da(this.element);this.cancelButton=new g.W({G:"button",Ga:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-cancel-button"],W:{"aria-label":"Batalkan pemutaran otomatis"},va:"Batalkan"});g.J(this,this.cancelButton);this.cancelButton.Da(this.B.element);this.cancelButton.Sa("click",this.DO,this);this.I.Ub(this.cancelButton.element,this,
115129);this.playButton=new g.W({G:"a",Ga:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-play-button"],W:{href:"{{url}}",role:"button","aria-label":"Putar video selanjutnya"},va:"Putar Sekarang"});g.J(this,this.playButton);this.playButton.Da(this.B.element);this.playButton.Sa("click",this.BG,this);this.I.Ub(this.playButton.element,this,115130);this.C=new g.K(function(){K5(c)},500);
g.J(this,this.C);this.AG();this.S(a,"autonavvisibility",this.AG)},O5=function(a){var b=a.I.ej(!0,a.I.isFullscreen());
g.O(a.element,"ytp-autonav-endscreen-small-mode",a.kf(b));g.O(a.element,"ytp-autonav-endscreen-is-premium",!!a.suggestion&&!!a.suggestion.dA);g.O(a.I.getRootNode(),"ytp-autonav-endscreen-cancelled-state",!a.I.Rd());g.O(a.I.getRootNode(),"countdown-running",a.Jh());g.O(a.element,"ytp-player-content",a.I.Rd());g.Ml(a.overlay.element,{width:b.width+"px"});if(!a.Jh()){a.I.Rd()?M5(a,Math.round(N5(a)/1E3)):M5(a);b=!!a.suggestion&&!!a.suggestion.Uo;var c=a.I.Rd()||!b;g.O(a.element,"ytp-autonav-endscreen-upnext-alternative-header-only",
!c&&b);g.O(a.element,"ytp-autonav-endscreen-upnext-no-alternative-header",c&&!b);g.bL(a.B,a.I.Rd())}},K5=function(a){var b=N5(a),c=Math,d=c.min;
var e=a.u?Date.now()-a.u:0;c=d.call(c,e,b);M5(a,Math.ceil((b-c)/1E3));500>=b-c&&a.Jh()?a.select(!0):a.Jh()&&a.C.start()},N5=function(a){var b=a.I.qp();
return 0<=b?b:g.U(a.I.U().experiments,"autoplay_time")||1E4},M5=function(a,b){b=void 0===b?-1:b;
a=a.i.Fa("ytp-autonav-endscreen-upnext-header");g.ug(a);if(0<=b){b=String(b);var c="Berikutnya dalam $SECONDS".match(RegExp("\\$SECONDS","gi"))[0],d="Berikutnya dalam $SECONDS".indexOf(c);if(0<=d){a.appendChild(g.tg("Berikutnya dalam $SECONDS".slice(0,d)));var e=g.sg("span");g.Iq(e,"ytp-autonav-endscreen-upnext-header-countdown-number");g.zg(e,b);a.appendChild(e);a.appendChild(g.tg("Berikutnya dalam $SECONDS".slice(d+c.length)));return}}g.zg(a,"Berikutnya")},P5=function(a,b){g.W.call(this,{G:"div",
Ga:["html5-endscreen","ytp-player-content",b||"base-endscreen"]});this.created=!1;this.player=a},R5=function(a){g.W.call(this,{G:"div",
Ga:["ytp-upnext","ytp-player-content"],W:{"aria-label":"{{aria_label}}"},T:[{G:"div",L:"ytp-cued-thumbnail-overlay-image",W:{style:"{{background}}"}},{G:"span",L:"ytp-upnext-top",T:[{G:"span",L:"ytp-upnext-header",va:"Berikutnya"},{G:"span",L:"ytp-upnext-title",va:"{{title}}"},{G:"span",L:"ytp-upnext-author",va:"{{author}}"}]},{G:"a",L:"ytp-upnext-autoplay-icon",W:{role:"button",href:"{{url}}","aria-label":"Putar video selanjutnya"},T:[{G:"svg",W:{height:"100%",version:"1.1",viewBox:"0 0 72 72",width:"100%"},
T:[{G:"circle",L:"ytp-svg-autoplay-circle",W:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{G:"circle",L:"ytp-svg-autoplay-ring",W:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{G:"path",L:"ytp-svg-fill",W:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{G:"span",L:"ytp-upnext-bottom",T:[{G:"span",L:"ytp-upnext-cancel"},{G:"span",L:"ytp-upnext-paused",
va:"Putar otomatis dijeda"}]}]});this.api=a;this.cancelButton=null;this.D=this.Fa("ytp-svg-autoplay-ring");this.B=this.notification=this.i=this.suggestion=null;this.C=new g.K(this.zx,5E3,this);this.u=0;var b=this.Fa("ytp-upnext-cancel");this.cancelButton=new g.W({G:"button",Ga:["ytp-upnext-cancel-button","ytp-button"],W:{tabindex:"0","aria-label":"Batalkan pemutaran otomatis"},va:"Batalkan"});g.J(this,this.cancelButton);this.cancelButton.Sa("click",this.EO,this);this.cancelButton.Da(b);this.cancelButton&&
this.api.Ub(this.cancelButton.element,this,115129);g.J(this,this.C);this.api.Ub(this.element,this,18788);b=this.Fa("ytp-upnext-autoplay-icon");this.S(b,"click",this.FO);this.api.Ub(b,this,115130);this.CG();this.S(a,"autonavvisibility",this.CG);this.S(a,"mdxnowautoplaying",this.xT);this.S(a,"mdxautoplaycanceled",this.yT);this.S(a,"mdxautoplayupnext",this.QM);Q5(this)&&(a=(a=g.UM(this.api.ub()))?a.BQ():null)&&this.QM(a);g.O(this.element,"ytp-upnext-mobile",this.api.U().i)},Q5=function(a){return 3===
a.api.getPresentingPlayerType()},nPa=function(a,b){return b?b:0<=a.api.qp()?a.api.qp():g.U(a.api.U().experiments,"autoplay_time")||1E4},S5=function(a,b){b=nPa(a,b);
var c=Math,d=c.min;var e=(0,g.Q)()-a.u;c=d.call(c,e,b);b=0===b?1:Math.min(c/b,1);a.D.setAttribute("stroke-dashoffset",""+-211*(b+1));1<=b&&a.Jh()&&!Q5(a)?a.select(!0):a.Jh()&&a.i.start()},T5=function(a){P5.call(this,a,"autonav-endscreen");
this.overlay=this.videoData=this.suggestions=null;this.table=new g.W({G:"div",L:"ytp-suggestion-panel",T:[{G:"div",Ga:["ytp-autonav-endscreen-upnext-header","ytp-autonav-endscreen-more-videos"],va:"Video lainnya"}]});this.K=new g.W({G:"div",L:"ytp-suggestions-container"});this.videos=[];this.B=null;this.D=this.J=!1;this.u=new L5(this.player);g.J(this,this.u);this.u.Da(this.element);a.getVideoData().dc?this.i=this.u:(this.i=new R5(a),g.YM(this.player,this.i.element,4),g.J(this,this.i));this.overlay=
new g.W({G:"div",L:"ytp-autonav-overlay-cancelled-state"});g.J(this,this.overlay);this.overlay.Da(this.element);this.C=new g.aN(this);g.J(this,this.C);g.J(this,this.table);this.table.Da(this.element);this.table.show();g.J(this,this.K);this.K.Da(this.table.element);this.hide()},oPa=function(a,b){return g.Se(b.suggestions,function(c){c=g.DP(a.player.U(),c);
g.J(a,c);return c})},U5=function(a){var b=a.Rd();
b!==a.D&&(a.D=b,a.player.Z("autonavvisibility"),a.D?(a.u!==a.i&&a.u.hide(),a.table.hide()):(a.u!==a.i&&a.u.show(),a.table.show()))},V5=function(a){P5.call(this,a,"subscribecard-endscreen");
this.i=new g.W({G:"div",L:"ytp-subscribe-card",T:[{G:"img",L:"ytp-author-image",W:{src:"{{profilePicture}}"}},{G:"div",L:"ytp-subscribe-card-right",T:[{G:"div",L:"ytp-author-name",va:"{{author}}"},{G:"div",L:"html5-subscribe-button-container"}]}]});g.J(this,this.i);this.i.Da(this.element);var b=a.getVideoData();this.subscribeButton=new g.pO("Subscribe",null,"Unsubscribe",null,!0,!1,b.Si,b.subscribed,"trailer-endscreen",null,null,a);g.J(this,this.subscribeButton);this.subscribeButton.Da(this.i.Fa("html5-subscribe-button-container"));
this.S(a,"videodatachange",this.Pa);this.Pa();this.hide()},W5=function(a){var b=a.U(),c=g.dj||g.jF?{style:"will-change: opacity"}:void 0,d=b.u,e=["ytp-videowall-still"];
b.i&&e.push("ytp-videowall-show-text");g.W.call(this,{G:"a",Ga:e,W:{href:"{{url}}",target:d?b.K:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},T:[{G:"div",L:"ytp-videowall-still-image",W:{style:"{{background}}"}},{G:"span",L:"ytp-videowall-still-info",T:[{G:"span",L:"ytp-videowall-still-info-bg",T:[{G:"span",L:"ytp-videowall-still-info-content",W:c,T:[{G:"span",L:"ytp-videowall-still-info-title",va:"{{title}}"},{G:"span",L:"ytp-videowall-still-info-author",
va:"{{author_and_views}}"},{G:"span",L:"ytp-videowall-still-info-live",va:"Live"},{G:"span",L:"ytp-videowall-still-info-duration",va:"{{duration}}"}]}]}]},{G:"span",Ga:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],T:[{G:"span",L:"ytp-videowall-still-listlabel-icon"},"Playlist",{G:"span",L:"ytp-videowall-still-listlabel-length",T:[" (",{G:"span",va:"{{playlist_length}}"},")"]}]},{G:"span",Ga:["ytp-videowall-still-listlabel-mix","ytp-videowall-still-listlabel"],T:[{G:"span",
L:"ytp-videowall-still-listlabel-mix-icon"},"Video Mix",{G:"span",L:"ytp-videowall-still-listlabel-length",va:" (50+)"}]}]});this.suggestion=null;this.u=d;this.api=a;this.i=new g.aN(this);g.J(this,this.i);this.Sa("click",this.onClick);this.Sa("keypress",this.B);this.i.S(a,"videodatachange",this.qb);a.Og(this.element,this);this.qb()},X5=function(a){P5.call(this,a,"videowall-endscreen");
var b=this;this.I=a;this.B=0;this.stills=[];this.C=this.videoData=this.suggestions=null;this.D=this.K=!1;this.N=null;this.u=new g.aN(this);g.J(this,this.u);this.J=new g.K(function(){g.N(b.element,"ytp-show-tiles")},0);
g.J(this,this.J);var c=new g.W({G:"button",Ga:["ytp-button","ytp-endscreen-previous"],W:{"aria-label":"Sebelumnya"},T:[g.gL()]});g.J(this,c);c.Da(this.element);c.Sa("click",this.JO,this);this.table=new g.ZK({G:"div",L:"ytp-endscreen-content"});g.J(this,this.table);this.table.Da(this.element);c=new g.W({G:"button",Ga:["ytp-button","ytp-endscreen-next"],W:{"aria-label":"Berikutnya"},T:[g.hL()]});g.J(this,c);c.Da(this.element);c.Sa("click",this.IO,this);a.getVideoData().dc?this.i=new L5(a,!0):this.i=
new R5(a);g.J(this,this.i);g.YM(this.player,this.i.element,4);this.hide()},Y5=function(a){return g.ZM(a.player)&&a.fu()&&!a.C},pPa=function(a,b){return g.Se(b.suggestions,function(c){c=g.DP(a.I.U(),c);
g.J(a,c);return c})},Z5=function(a){var b=a.Rd();
b!==a.K&&(a.K=b,a.player.Z("autonavvisibility"))},$5=function(a){g.kN.call(this,a);
var b=this;this.endScreen=null;this.i=this.u=this.B=!1;this.listeners=new g.aN(this);g.J(this,this.listeners);this.env=a.U();qPa(a)?(this.B=!0,rPa(this),this.i?this.endScreen=new T5(a):this.endScreen=new X5(this.player)):this.env.Qc?this.endScreen=new V5(this.player):this.endScreen=new P5(this.player);g.J(this,this.endScreen);g.YM(this.player,this.endScreen.element,4);sPa(this);this.listeners.S(a,"videodatachange",this.qb,this);this.listeners.S(a,g.kA("endscreen"),function(c){b.Bd(c)});
this.listeners.S(a,g.lA("endscreen"),function(c){b.nf(c)})},rPa=function(a){var b=a.player.getVideoData();
if(!b||a.i===b.Kh&&a.u===b.dc)return!1;a.i=b.Kh;a.u=b.dc;return!0},qPa=function(a){a=a.U();
return a.Db&&!a.Qc},sPa=function(a){a.player.We("endscreen");
var b=a.player.getVideoData();b=new g.hA(Math.max(1E3*(b.lengthSeconds-10),0),0x8000000000000,{id:"preload",namespace:"endscreen"});var c=new g.hA(0x8000000000000,0x8000000000000,{id:"load",priority:6,namespace:"endscreen"});a.player.Hd([b,c])};
g.RM.prototype.qp=g.ca(2,function(){return this.app.qp()});
g.$X.prototype.qp=g.ca(1,function(){return this.getVideoData().PJ});
g.w(J5,g.W);J5.prototype.select=function(){(this.I.Lj(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.Iu||void 0)||this.I.Y("web_player_endscreen_double_log_fix_killswitch"))&&this.I.Fb(this.element)};
J5.prototype.onClick=function(a){g.JN(a,this.I,this.i,this.suggestion.sessionData||void 0)&&this.select()};
J5.prototype.u=function(a){switch(a.keyCode){case 13:case 32:g.ru(a)||(this.select(),g.qu(a))}};g.w(L5,g.W);g.k=L5.prototype;g.k.Kt=function(a){this.suggestion!==a&&(this.suggestion=a,I5(this.i,a),this.playButton.Ua("url",this.suggestion.Ak()),O5(this))};
g.k.Jh=function(){return 0<this.u};
g.k.Os=function(){this.Jh()||(this.u=Date.now(),K5(this),mPa(this.I,N5(this)),g.O(this.I.getRootNode(),"countdown-running",this.Jh()))};
g.k.Zp=function(){this.qm();K5(this);var a=this.i.Fa("ytp-autonav-endscreen-upnext-header");a&&g.zg(a,"Berikutnya")};
g.k.qm=function(){this.Jh()&&(this.C.stop(),this.u=0)};
g.k.select=function(a){this.I.nextVideo(!1,void 0===a?!1:a);this.qm()};
g.k.BG=function(a){g.JN(a,this.I)&&(a.currentTarget===this.playButton.element?this.I.Fb(this.playButton.element):a.currentTarget===this.i.Fa("ytp-autonav-endscreen-link-container")&&(a=this.i.Fa("ytp-autonav-endscreen-link-container"),this.I.ib(a,!0),this.I.Fb(a)),this.select())};
g.k.DO=function(){this.I.Fb(this.cancelButton.element);g.TM(this.I,!0)};
g.k.AG=function(){var a=this.I.Rd();this.D&&this.zb!==a&&g.bL(this,a);O5(this);this.I.ib(this.element,a);this.I.ib(this.cancelButton.element,a);this.I.ib(this.i.Fa("ytp-autonav-endscreen-link-container"),a);this.I.ib(this.playButton.element,a)};
g.k.kf=function(a){return 400>a.width||459>a.height};g.w(P5,g.W);g.k=P5.prototype;g.k.create=function(){this.created=!0};
g.k.destroy=function(){this.created=!1};
g.k.fu=function(){return!1};
g.k.Rd=function(){return!1};
g.k.OJ=function(){return!1};g.w(R5,g.W);g.k=R5.prototype;g.k.zx=function(){this.notification&&(this.C.stop(),this.kc(this.B),this.B=null,this.notification.close(),this.notification=null)};
g.k.Kt=function(a){this.suggestion=a;I5(this,a,"hqdefault.jpg")};
g.k.CG=function(){g.bL(this,this.api.Rd());this.api.ib(this.element,this.api.Rd());this.api.ib(this.Fa("ytp-upnext-autoplay-icon"),this.api.Rd());this.cancelButton&&this.api.ib(this.cancelButton.element,this.api.Rd())};
g.k.HT=function(){window.focus();this.zx()};
g.k.Os=function(a){var b=this;this.Jh()||(g.Vu("a11y-announce","Berikutnya "+this.suggestion.title),this.u=(0,g.Q)(),this.i=new g.K(function(){S5(b,a)},25),S5(this,a),mPa(this.api,nPa(this,a)));
g.Lq(this.element,"ytp-upnext-autoplay-paused")};
g.k.hide=function(){g.W.prototype.hide.call(this)};
g.k.Jh=function(){return!!this.i};
g.k.Zp=function(){this.qm();this.u=(0,g.Q)();S5(this);g.N(this.element,"ytp-upnext-autoplay-paused")};
g.k.qm=function(){this.Jh()&&(this.i.dispose(),this.i=null)};
g.k.select=function(a){a=void 0===a?!1:a;if(g.T(this.api.U().experiments,"autonav_notifications")&&a&&window.Notification&&document.hasFocus){var b=Notification.permission;"default"===b?Notification.requestPermission():"granted"!==b||document.hasFocus()||(this.zx(),this.notification=new Notification("Berikutnya",{body:this.suggestion.title,icon:this.suggestion.Ee()}),this.B=this.S(this.notification,"click",this.HT),this.C.start())}this.qm();this.api.nextVideo(!1,a)};
g.k.FO=function(a){!g.yg(this.cancelButton.element,g.mu(a))&&g.JN(a,this.api)&&(this.api.Rd()&&this.api.Fb(this.Fa("ytp-upnext-autoplay-icon")),this.select())};
g.k.EO=function(){this.api.Rd()&&this.cancelButton&&this.api.Fb(this.cancelButton.element);g.TM(this.api,!0)};
g.k.xT=function(a){Q5(this);this.show();this.Os(a)};
g.k.QM=function(a){var b;Q5(this);(null===(b=this.suggestion)||void 0===b?void 0:b.videoId)!==a.videoId&&this.Kt(a)};
g.k.yT=function(){Q5(this);this.qm();this.hide()};
g.k.xa=function(){this.qm();this.zx();g.W.prototype.xa.call(this)};g.w(T5,P5);g.k=T5.prototype;g.k.create=function(){P5.prototype.create.call(this);this.C.S(this.player,"appresize",this.Jt);this.C.S(this.player,"onVideoAreaChange",this.Jt);this.C.S(this.player,"videodatachange",this.qb);this.C.S(this.player,"autonavchange",this.DG);this.C.S(this.player,"autonavcancel",this.GO);this.qb()};
g.k.show=function(){P5.prototype.show.call(this);(this.J||this.B&&this.B!==this.videoData.clientPlaybackNonce)&&g.TM(this.player,!1);g.ZM(this.player)&&this.fu()&&!this.B?(U5(this),2===this.videoData.autonavState?this.player.U().Y("fast_autonav_in_background")&&3===this.player.getVisibilityState()?this.i.select(!0):this.i.Os():3===this.videoData.autonavState&&this.i.Zp()):(g.TM(this.player,!0),U5(this));this.Jt()};
g.k.hide=function(){P5.prototype.hide.call(this);this.i.Zp();U5(this)};
g.k.Jt=function(){var a=this.player.ej(!0,this.player.isFullscreen());U5(this);O5(this.u);g.O(this.element,"ytp-autonav-cancelled-small-mode",this.kf(a));g.O(this.element,"ytp-autonav-cancelled-tiny-mode",this.Hy(a));g.O(this.element,"ytp-autonav-cancelled-mini-mode",400>=a.width||360>=a.height);this.overlay&&g.Ml(this.overlay.element,{width:a.width+"px"});if(!this.D){a=g.r(this.videos.entries());for(var b=a.next();!b.done;b=a.next()){var c=g.r(b.value);b=c.next().value;c=c.next().value;g.O(c.element,
"ytp-suggestion-card-with-margin",1===b%2)}}};
g.k.qb=function(){var a=this.player.getVideoData();if(this.videoData!==a&&a){this.videoData=a;if((this.suggestions=oPa(this,a))&&this.suggestions.length)for(this.i.Kt(this.suggestions[0]),this.i!==this.u&&this.u.Kt(this.suggestions[0]),a=0;a<tPa.length;++a){var b=tPa[a];if(this.suggestions&&this.suggestions[b]){this.videos[a]=new J5(this.player);var c=this.videos[a];b=this.suggestions[b];c.suggestion!==b&&(c.suggestion=b,I5(c,b));g.J(this,this.videos[a]);this.videos[a].Da(this.K.element)}}this.Jt()}};
g.k.DG=function(a){1===a?(this.J=!1,this.B=this.videoData.clientPlaybackNonce,this.i.qm(),this.zb&&this.Jt()):(this.J=!0,this.Rd()&&(2===a?this.i.Os():3===a&&this.i.Zp()))};
g.k.GO=function(a){a?this.DG(1):(this.B=null,this.J=!1)};
g.k.fu=function(){return 1!==this.videoData.autonavState};
g.k.kf=function(a){return(910>a.width||459>a.height)&&!this.Hy(a)&&!(400>=a.width||360>=a.height)};
g.k.Hy=function(a){return 800>a.width&&!(400>=a.width||360>=a.height)};
g.k.Rd=function(){return this.zb&&g.ZM(this.player)&&this.fu()&&!this.B};
var tPa=[1,3,2,4];g.w(V5,P5);V5.prototype.Pa=function(){var a=this.player.getVideoData();this.i.update({profilePicture:a.Ph,author:a.author});this.subscribeButton.channelId=a.Si;var b=this.subscribeButton;a.subscribed?b.u():b.B()};g.w(W5,g.W);W5.prototype.select=function(){(this.api.Lj(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.Iu||void 0)||this.api.Y("web_player_endscreen_double_log_fix_killswitch"))&&this.api.Fb(this.element)};
W5.prototype.onClick=function(a){g.JN(a,this.api,this.u,this.suggestion.sessionData||void 0)&&this.select()};
W5.prototype.B=function(a){switch(a.keyCode){case 13:case 32:g.ru(a)||(this.select(),g.qu(a))}};
W5.prototype.qb=function(){var a=this.api.getVideoData(),b=this.api.U();this.u=a.D?!1:b.u};g.w(X5,P5);g.k=X5.prototype;g.k.create=function(){P5.prototype.create.call(this);var a=this.player.getVideoData();a&&(this.suggestions=pPa(this,a),this.videoData=a);this.Yk();this.u.S(this.player,"appresize",this.Yk);this.u.S(this.player,"onVideoAreaChange",this.Yk);this.u.S(this.player,"videodatachange",this.qb);this.u.S(this.player,"autonavchange",this.jB);this.u.S(this.player,"autonavcancel",this.HO);a=this.videoData.autonavState;a!==this.N&&this.jB(a);this.u.S(this.element,"transitionend",this.ZU)};
g.k.destroy=function(){g.Lx(this.u);g.lf(this.stills);this.stills=[];this.suggestions=null;P5.prototype.destroy.call(this);g.Lq(this.element,"ytp-show-tiles");this.J.stop();this.N=this.videoData.autonavState};
g.k.fu=function(){return 1!==this.videoData.autonavState};
g.k.show=function(){P5.prototype.show.call(this);g.Lq(this.element,"ytp-show-tiles");this.player.U().i?g.Eq(this.J):this.J.start();(this.D||this.C&&this.C!==this.videoData.clientPlaybackNonce)&&g.TM(this.player,!1);Y5(this)?(Z5(this),2===this.videoData.autonavState?this.player.U().Y("fast_autonav_in_background")&&3===this.player.getVisibilityState()?this.i.select(!0):this.i.Os():3===this.videoData.autonavState&&this.i.Zp()):(g.TM(this.player,!0),Z5(this))};
g.k.hide=function(){P5.prototype.hide.call(this);this.i.Zp();Z5(this)};
g.k.ZU=function(a){g.mu(a)===this.element&&this.Yk()};
g.k.Yk=function(){if(this.suggestions&&this.suggestions.length){g.N(this.element,"ytp-endscreen-paginate");var a=this.I.ej(!0,this.I.isFullscreen()),b=g.OM(this.I);b&&(b=b.Oe()?48:32,a.width-=2*b);var c=a.width/a.height,d=96/54,e=b=2,f=Math.max(a.width/96,2),h=Math.max(a.height/54,2),l=this.suggestions.length,m=Math.pow(2,2);var n=l*m+(Math.pow(2,2)-m);n+=Math.pow(2,2)-m;for(n-=m;0<n&&(b<f||e<h);){var p=b/2,q=e/2,t=b<=f-2&&n>=q*m,u=e<=h-2&&n>=p*m;if((p+1)/q*d/c>c/(p/(q+1)*d)&&u)n-=p*m,e+=2;else if(t)n-=
q*m,b+=2;else if(u)n-=p*m,e+=2;else break}d=!1;n>=3*m&&6>=l*m-n&&(4<=e||4<=b)&&(d=!0);m=96*b;n=54*e;c=m/n<c?a.height/n:a.width/m;c=Math.min(c,2);m=Math.floor(Math.min(a.width,m*c));n=Math.floor(Math.min(a.height,n*c));a=this.table.element;g.$l(a,m,n);g.Ml(a,{marginLeft:m/-2+"px",marginTop:n/-2+"px"});this.i.Kt(this.suggestions[0]);this.i instanceof L5&&O5(this.i);g.O(this.element,"ytp-endscreen-takeover",Y5(this));Z5(this);m+=4;n+=4;for(f=c=0;f<b;f++)for(h=0;h<e;h++)if(p=c,q=0,d&&f>=b-2&&h>=e-2?q=
1:0===h%2&&0===f%2&&(2>h&&2>f?0===h&&0===f&&(q=2):q=2),p=g.Sf(p+this.B,l),0!==q){t=this.stills[c];t||(t=new W5(this.player),this.stills[c]=t,a.appendChild(t.element));u=Math.floor(n*h/e);var x=Math.floor(m*f/b),y=Math.floor(n*(h+q)/e)-u-4,B=Math.floor(m*(f+q)/b)-x-4;g.Tl(t.element,x,u);g.$l(t.element,B,y);g.Ml(t.element,"transitionDelay",(h+f)/20+"s");g.O(t.element,"ytp-videowall-still-mini",1===q);g.O(t.element,"ytp-videowall-still-large",2<q);q=t;p=this.suggestions[p];q.suggestion!==p&&(q.suggestion=
p,t=q.api.U(),u=g.Jq(q.element,"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg",I5(q,p,u),g.lF(t)&&(t=p.Ak(),t=g.si(t,g.GM("emb_rel_end")),q.Ua("url",t)),(p=(p=p.sessionData)&&p.itct)&&q.api.nm(q.element,p));c++}g.O(this.element,"ytp-endscreen-paginate",c<l);for(b=this.stills.length-1;b>=c;b--)e=this.stills[b],g.wg(e.element),g.hf(e);this.stills.length=c}};
g.k.qb=function(){var a=this.player.getVideoData();this.videoData!==a&&(this.B=0,this.suggestions=pPa(this,a),this.videoData=a,this.Yk())};
g.k.IO=function(){this.B+=this.stills.length;this.Yk()};
g.k.JO=function(){this.B-=this.stills.length;this.Yk()};
g.k.OJ=function(){return this.i.Jh()};
g.k.jB=function(a){1===a?(this.D=!1,this.C=this.videoData.clientPlaybackNonce,this.i.qm(),this.zb&&this.Yk()):(this.D=!0,this.zb&&Y5(this)&&(2===a?this.i.Os():3===a&&this.i.Zp()))};
g.k.HO=function(a){if(a){for(a=0;a<this.stills.length;a++)this.I.ib(this.stills[a].element,!0);this.jB(1)}else this.C=null,this.D=!1;this.Yk()};
g.k.Rd=function(){return this.zb&&Y5(this)};g.w($5,g.kN);g.k=$5.prototype;g.k.oq=function(){var a=this.player.getVideoData(),b=!!(a&&a.suggestions&&a.suggestions.length);b=!qPa(this.player)||b;var c=a.Ce||g.wF(a.C),d=this.player.Ou();a=a.mutedAutoplay;return b&&!c&&!d&&!a};
g.k.Rd=function(){return this.endScreen.Rd()};
g.k.nR=function(){return this.Rd()?this.endScreen.OJ():!1};
g.k.xa=function(){this.player.We("endscreen");g.kN.prototype.xa.call(this)};
g.k.load=function(){var a=this.player.getVideoData();var b=a.NH;if(b&&b.videoId){var c=this.player.ub().ud.get("heartbeat");a&&a.suggestions&&a.suggestions.length&&b.videoId===a.suggestions[0].id&&!a.NG?a=!1:(this.player.Lj(b.videoId,void 0,void 0,!0,!0,b),c&&c.Qy("HEARTBEAT_ACTION_TRIGGER_AT_STREAM_END","HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT"),a=!0)}else a=!1;a||(g.kN.prototype.load.call(this),this.endScreen.show())};
g.k.unload=function(){g.kN.prototype.unload.call(this);this.endScreen.hide();this.endScreen.destroy()};
g.k.Bd=function(a){this.oq()&&(this.endScreen.created||this.endScreen.create(),"load"===a.getId()&&this.load())};
g.k.nf=function(a){"load"===a.getId()&&this.loaded&&this.unload()};
g.k.qb=function(){sPa(this);this.B&&rPa(this)&&(this.endScreen&&(this.endScreen.hide(),this.endScreen.created&&this.endScreen.destroy(),this.endScreen.dispose()),this.i?this.endScreen=new T5(this.player):this.endScreen=new X5(this.player),g.J(this,this.endScreen),g.YM(this.player,this.endScreen.element,4))};g.vN.endscreen=$5;})(_yt_player);
